### ISSUE TITLE
Crash when returning a class with an interface with FluentValidator

### ISSUE THREAD

**Issue by thomasd3** [ChilliCream/hotchocolate#1016]
I have this interface:

	internal interface IValidate
	{
		Task<ValidationResult> ValidateAsync();
	}

ValidationResult is from the package FluentValidator.

If I return any class that implements this interface, the graph initialization will crash.
Any class that derives from a class implementing this interface will cause the same crash.

The crash is this:

```
Unhandled Exception: HotChocolate.SchemaException: Unable to resolve type reference `Output: System.Object[]`. - Type: ValidationFailure
   at HotChocolate.Configuration.CompletionContext.GetType[T](ITypeReference reference)
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ICompletionContext context, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`2.CompleteField(ICompletionContext context)
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ICompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ICompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__44_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.InitializeTypes(IServiceProvider services, IDescriptorContext descriptorContext, IBindingLookup bindingLookup, IEnumerable`1 types, Func`1 schemaResolver)
   at HotChocolate.SchemaBuilder.Create()
```

**Comment by michaelstaib** [comment]
This is not an issue. You have to tell the schema builder what these objects are. GraphQL is strongly typed meaning we cannot infer types from object.

I will close this, since the schema builder is working as expected.
