### ISSUE TITLE
Custom paths Voyager and Playground not working on AspNetCore 3.0

### ISSUE THREAD

**Issue by lucas-mv** [ChilliCream/hotchocolate#1203]
The endpoints for `voyager` and `playground` always default to `/voyager` and `/playground`, respectively, even when I specify a Path and QueryPath, as shown below.

Also the QueryPath does not seem to be working either, since the paths I input in these variables don't seem to be doing anything (voyager stays loading forever and playground can never initialize the path correctly).

```
app.UsePlayground(new PlaygroundOptions {
                Path = "/something/playground",
                QueryPath = "/something/graphql"
            });
            app.UseVoyager(new VoyagerOptions {
                Path = "/something/voyager",
                QueryPath = "/something/graphql"
            });
//DEFAULTS TO /voyager AND /playground
```

My project is using the current library configuration:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <DockerTargetOS>Linux</DockerTargetOS>
    <UserSecretsId>b1bfa585-75c5-4919-ad45-48468e169ee3</UserSecretsId>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
...
  <ItemGroup>
    <PackageReference Include="HotChocolate" Version="10.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore.GraphiQL" Version="10.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore.Playground" Version="10.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="10.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="10.1.0" />
    <PackageReference Include="HotChocolate.AspNetCore.Voyager" Version="10.1.0" />
    <PackageReference Include="HotChocolate.Subscriptions" Version="10.1.0" />
  </ItemGroup>
...
</Project>
```

**Comment by michaelstaib** [comment]
Hi @lucas-mv,

I will look into it.

**Comment by RehanSaeed** [comment]
Also, setting a path of `/` like so:

```c#
new PlaygroundOptions() { Path = "/", QueryPath = "/graphql" }
```

Results in the following exception:

```
System.ArgumentException
  HResult=0x80070057
  Message=Request path must not end in a slash
  Source=Microsoft.AspNetCore.StaticFiles
  StackTrace:
   at Microsoft.AspNetCore.StaticFiles.Infrastructure.SharedOptions.set_RequestPath(PathString value)
   at Microsoft.AspNetCore.StaticFiles.Infrastructure.SharedOptionsBase.set_RequestPath(PathString value)
   at HotChocolate.AspNetCore.ApplicationBuilderExtensions.UsePlaygroundFileServer(IApplicationBuilder applicationBuilder, String path)
   at HotChocolate.AspNetCore.ApplicationBuilderExtensions.UsePlayground(IApplicationBuilder applicationBuilder, PlaygroundOptions options)
   at StarWars.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\GitHub\hotchocolate-examples-master\PureCodeFirst\Startup.cs:line 53
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
```

**Comment by michaelstaib** [comment]
we have now replaced playground with bcp and use the new endpoint api.
