### ISSUE TITLE
"Unexpected Execution Error" in star wars example when query for character

### ISSUE THREAD

**Issue by christianMurschall** [ChilliCream/hotchocolate#1295]
**Describe the bug**

Query for character will throw an `"Unexpected Execution Error"` with message `"Object reference not set to an instance of an object."`. 

**To Reproduce **
Go to `http://localhost:port/graphql/playground/` and insert the following queries
 
```
{
  character{
    id
    name
  }
}
```
**Expected behavior**
I'd like go get a list of characters but I get an "Unexpected Execution Error":
```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "extensions": {
        "message": "Object reference not set to an instance of an object.",
        "stackTrace": "   
   at StarWars.Query.GetCharacter(String[] characterIds, IResolverContext context)+MoveNext() in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\examples\\AspNetCore.StarWars\\Query.cs:line 51
   at HotChocolate.Execution.ValueCompletion.CompleteList(ICompleteValueContext context, IType elementType, Object result) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Utilities\\ValueCompletion.cs:line 90
   at HotChocolate.Execution.ValueCompletion.CompleteValue(ICompleteValueContext context, IType type, Object result) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Utilities\\ValueCompletion.cs:line 63
   at HotChocolate.Execution.ValueCompletion.CompleteValue(ICompleteValueContext context, IType type, Object result) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Utilities\\ValueCompletion.cs:line 50
   at HotChocolate.Execution.ValueCompletion.CompleteValue(Action`1 enqueueNext, ResolverContext resolverContext) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Utilities\\ValueCompletion.cs:line 28
   at HotChocolate.Execution.ExecutionStrategyBase.EndExecuteResolverBatchAsync(IEnumerable`1 batch, Action`1 enqueueNext, CancellationToken cancellationToken) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\ExecutionStrategyBase.cs:line 183
   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteResolversAsync(IExecutionContext executionContext, IEnumerable`1 initialBatch, BatchOperationHandler batchOperationHandler, CancellationToken cancellationToken) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\ExecutionStrategyBase.cs:line 92
   at HotChocolate.Execution.ExecutionStrategyBase.ExecuteQueryAsync(IExecutionContext executionContext, BatchOperationHandler batchOperationHandler, CancellationToken cancellationToken) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\ExecutionStrategyBase.cs:line 34
   at HotChocolate.Execution.QueryExecutionStrategy.ExecuteInternalAsync(IExecutionContext executionContext, CancellationToken cancellationToken) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\QueryExecutionStrategy.cs:line 31
   at HotChocolate.Execution.ExecuteOperationMiddleware.InvokeAsync(IQueryContext context) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Middleware\\ExecuteOperationMiddleware.cs:line 54
   at HotChocolate.Execution.ValidateQueryMiddleware.InvokeAsync(IQueryContext context) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Middleware\\ValidateQueryMiddleware.cs:line 67
   at HotChocolate.Execution.ParseQueryMiddleware.InvokeAsync(IQueryContext context) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Middleware\\ParseQueryMiddleware.cs:line 91
   at HotChocolate.Execution.ExceptionMiddleware.InvokeAsync(IQueryContext context) in C:\\Users\\currentUser\\Documents\\projects\\temp\\hotchocolate\\src\\Core\\Core\\Execution\\Middleware\\ExceptionMiddleware.cs:line 26"
      }
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by michaelstaib** [comment]
Character erwartet eine liste von character ids als argument.
