### ISSUE TITLE
Does IdType need to be defined even if with interface?

### ISSUE THREAD

**Issue by gongdo** [ChilliCream/hotchocolate#1379]
I have tested with v10.3.4.

I have designed models:
```csharp
public class Query
{
    public Foo GetFoo() => new Foo();
}
public class Foo
{
    public string Id { get; set; }
    public string Name { get; set; }
    public int MyProperty { get; set; }
}
public class FooType : ObjectType<Foo>
{
    protected override void Configure(IObjectTypeDescriptor<Foo> descriptor)
    {
        descriptor.Interface<ContentType>();
        // to comment bellow makes schema failure(1).
        // why should I define 'id' again?
        // while the 'name' field doesn't need to define again.
        descriptor.Field(t => t.Id).Type<NonNullType<IdType>>();
    }
}
public class ContentType : InterfaceType
{
    protected override void Configure(IInterfaceTypeDescriptor descriptor)
    {
        descriptor.Name("Content");
        descriptor.Field("id").Type<NonNullType<IdType>>();
        descriptor.Field("name").Type<StringType>();
    }
}
```
It defines a POCO model, `Foo` and makes that as an implementation of the interface, `ContentType`.

And here's the test:
```csharp
[TestClass]
public class SchemaTest
{
    [TestMethod]
    public void InterfaceType_test()
    {
        var schema = SchemaBuilder.New()
        .AddType<FooType>()
        // to uncomment bellow makes schema failure(2)...why?
        // .AddInterfaceType<ContentType>()
        .AddQueryType<Query>()
        .Create();

        Console.WriteLine(schema);
    }
}
```

As I commented inside the code, there's two strange things(for me).

1. The `FooType` describes that it is an implementation of the interface `ContentType`. The `ContentType` already describes that it has an `id` field. However if I don't describe the `id` field in the `FooType`, the schema won't be created like this:
```
HotChocolate.SchemaException: The return type of the interface field id does not match the field declared by object type Foo. - Type: Foo
    Stack Trace:
        at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
```
It seems that HC schema complains only if the `IdType` field was not defined in the each concrete types.

2. Of course the HC schema infers the interface type, but if I add the interface type explicitly, the schema won't be created like this:
```
HotChocolate.SchemaException: Multiple schema errors occured:
Unable to create instance of type ``.
Unable to create instance of type ``.
...bunch of same messages...
    Stack Trace:
        at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
```

I didn't test further detail for generic interface type, but I bet it'll show same result.

Is this an expected behaviour?

**Comment by michaelstaib** [comment]
This is defined as this in the GraphQL spec and you actually do this also in C# lso since you define the actual implementation of the field where you restate the type.

**Comment by michaelstaib** [comment]
I am closing this one since the .net api is consistent with the GraphQL SDL.
