### ISSUE TITLE
[StrawberryShake] Allow for @name directive in schema

### ISSUE THREAD

**Issue by Alxandr** [ChilliCream/hotchocolate#1382]
**Is your feature request related to a problem? Please describe.**
I added a `@name` directive to my schema cause then I could write an extension method on `IEnumTypeDescriptor<T>` to emit the original enum names as part of the schema (as opposed to having to stitch them together later). This results in a schema that looks like this:

```grahpql
enum DiscountType {
  AGREEMENT @name(value: "Agreement")
  INTERNET @name(value: "Internet")
  CUSTOMERBENEFIT @name(value: "CustomerBenefit")
}

directive @name(value: String!) on ENUM_VALUE
```

This throws an exception when building the client, because it adds its own `@name` directive.

```
  Unhandled Exception: HotChocolate.SchemaException: The name `name` was already registered by another type. - Type: name
     at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors() in D:\a\1\s\src\Core\Types\Configuration\TypeInitializer.cs:line 673
     at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options) in D:\a\1\s\src\Core\Types\Configuration\TypeInitializer.cs:line 113
     at HotChocolate.SchemaBuilder.Create() in D:\a\1\s\src\Core\Types\SchemaBuilder.Create.cs:line 41
     at StrawberryShake.Generators.ClientGenerator.Validate() in D:\a\1\s\src\Client\Generators\ClientGenerator.cs:line 284
     at StrawberryShake.Tools.GenerateCommandHandler.Compile(GenerateCommandContext context, String path, Configuration config, ClientGenerator generator, IReadOnlyList`1 documents, ICollection`1 errors) in D:\a\1\s\src\Client\dotnet-graphql\GenerateCommandHandler.cs:line 66
     at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path, Configuration configuration) in D:\a\1\s\src\Client\dotnet-graphql\CompileCommandHandlerBase.cs:line 121
     at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path) in D:\a\1\s\src\Client\dotnet-graphql\CompileCommandHandlerBase.cs:line 92
     at StrawberryShake.Tools.CompileCommandHandlerBase`2.ExecuteAsync(TCtx context, CancellationToken cancellationToken) in D:\a\1\s\src\Client\dotnet-graphql\CompileCommandHandlerBase.cs:line 72
     at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
     at StrawberryShake.Tools.Program.<Main>(String[] args)
  Contracts.Communication -> C:\Git\PolicyStaging\src\contracts\Contracts.Communication\bin\Debug\netstandard2.0\IfInsurance.PolicyStaging.Contracts.Communication.dll
```

**Describe the solution you'd like**
StrawberryShake should probably detect that a `@name` directive already exists, and not add it's own. Same for other similar directives.

**Describe alternatives you've considered**
Currently I've just deleted the directive declaration line from my schema (in the client project). However, this means I can't just do `dotnet graphql update` (or similar).

**Comment by michaelstaib** [comment]
Just to get this right. 

So, you're schema has a `@name` directive in it?

Directive naming is at the moment in discussion on the spec repository. The current solution would be that we prefix our directives. `@cc_name` although I do not like this solution. 

I cannot simple merge existing directives since their semantics could be something completely different and also these directives could have the wrong structure.
 
We could also remove type system directives from the introspection result since those are irrelevant for the client.

I think we will go for the latter.

**Comment by michaelstaib** [comment]
https://github.com/graphql/graphql-spec/pull/657

**Comment by michaelstaib** [comment]
TODOs

- [ ] Discuss Directive Names
- [ ] Rename Directives
- [ ] Do not include type system directives into the local _Strawberry Shake_ schema.

**Comment by Alxandr** [comment]
This still doesn't help with my issue. My goal is to emit the directive used by berry from the server, so the client don't have to extend the schema to get the correct enum names. The directive name itself is irrelevant to me.

**Comment by rstaib** [comment]
@michaelstaib I don't really like the prefix solution and also agree about what you said in terms of semantics and respectively merging directives. However, if thats the way to go I'm fine with it except ss_ is probably not a good idea.

**Comment by michaelstaib** [comment]
@Alxandr completely misunderstood you :)

Actually a good idea, but we should build that into HotChocolate so that the directives are and all are correctly included into the schema. We actually could fetch the schema in case of hc from our schema middleware.

If we added a special flag this could be done by just saying `http://{server}/schema?format=strawberry`.

This would then output the SDL with additional information. Actually with that we could also enrich the enums further and add even the underlying value:

```GraphQL
enum DiscountType @Type(name: "System.Int32") {
  AGREEMENT @name(value: "Agreement") @value(value: 1)
  INTERNET @name(value: "Internet") @value(value: 2)
  CUSTOMERBENEFIT @name(value: "CustomerBenefit") @value(value: 2)
}
```

What do you think?

**Comment by Alxandr** [comment]
I think it would be perfect. Though as discussed in this thread, maybe do some namespacing. `@berry_enum_value(name: "name", value: 8)`

**Comment by michaelstaib** [comment]
Yeah something like that ... :)

**Comment by emiliodel83** [comment]
Hi, is there a way with strawberryshake to also generate the Description attribute in the downloaded schema? Thanks.
