### ISSUE TITLE
Stitched schema not handling error from external schema

### ISSUE THREAD

**Issue by SniC** [ChilliCream/hotchocolate#1606]
**Describe the bug**
I noticed that when my external graphql api returns an error, the gateway graphql server (using a stitched schema) returns invalid json and throws the following exception:

```
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_StatusCode(Int32 value)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**To Reproduce**
I've created a minimal repository to reproduce the error: https://github.com/SniC/hotchocolate-stitching-error

**Expected behavior**
A valid response from the gateway with an error.

**Desktop:**
 - OS: Windows 10
 - Hotchocolate Version 10.4.0

**Comment by michaelstaib** [comment]
Thanks for creating a repro. Will look into this. We are at the moment collecting issues for a patch release. We probably start working on this next week.
