### ISSUE TITLE
Subscription CancellationToken cancelled on Startup

### ISSUE THREAD

**Issue by Zaixu** [ChilliCream/hotchocolate#1694]
When using pure code first subscriptions i keep getting these operation canceled exceptions on first request when starting up. Thereafter it does not come again. Im a bit confused whether this is expected or not.

InMemorySubscriptions

> fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUUB8IK9689", Request id "0HLUUB8IK9689:00000001": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.WriteMessageDelimiterAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.ReceiveAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.SubscriptionMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HLUUB8IK9689", Request id "0HLUUB8IK9689:00000001": An unhandled exception was thrown by the application.

> System.OperationCanceledException: The operation was canceled.
>    at System.Threading.CancellationToken.ThrowOperationCanceledException()
>    at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
>    at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
>    at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.WriteMessageDelimiterAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.ReceiveAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
>    at HotChocolate.AspNetCore.Subscriptions.SubscriptionMiddleware.InvokeAsync(HttpContext context)
>    at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
>    at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
>    at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```
```
    [ExtendObjectType(Name = "Subscription")]
    public class OrganizationSubscriptions
    {
        [SubscribeAndResolve]
        public async Task<IAsyncEnumerable<OrganizationDTO>> OrganizationAdded([Service]ITopicEventReceiver eventReceiver, CancellationToken cancellationToken) {
            return await eventReceiver.SubscribeAsync<string, OrganizationDTO>(SubscriptionConstants.OrganizationAdded, cancellationToken);
        }
    }
```
    [ExtendObjectType(Name = "Mutation")]
    public class OrganizationMutations
    {
        public async Task<Guid> CreateOrganization(
            CreateOrganizationInput input,
            [Service] DatabaseContext dbContext,
            [Service]ITopicEventSender eventSender,
            [Service]IMapper mapper,
            CancellationToken cancellationToken
            )
        {

            var organization = new Organization
            {
                Name = input.Name
            };

            dbContext.Organizations.Add(organization);
            await dbContext.SaveChangesAsync();

            var converted = mapper.Map<OrganizationDTO>(organization);
            await eventSender.SendAsync(SubscriptionConstants.OrganizationAdded, converted, cancellationToken);

            return organization.Id;
        }
    }
```

**Comment by ademchenko** [comment]
After about 10-20 times of requesting GraphQL API which is hosted on Fedora ver. 32 get a similar error:
```
2020-08-05 13:44:09.335 +04:00 [ERR]  { Id: 1, Name: "UnhandledException" } Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware An unhandled exception has occurred while executing the request.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException() in /_/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:line 354
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.WriteMessageDelimiterAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.ReceiveAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.SubscriptionMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05 13:44:09.422 +04:00 [ERR]  { Id: 13, Name: "ApplicationError" } Microsoft.AspNetCore.Server.Kestrel Connection id "0HM1P4G3F62DJ", Request id "...": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException() in /_/src/System.Private.CoreLib/shared/System/Threading/CancellationToken.cs:line 354
   at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.WriteMessageDelimiterAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.MessageReceiver.ReceiveAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.WebSocketSession.HandleAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Subscriptions.SubscriptionMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)


```

The server just stops responding and needs to be restarted to start working again. That's an absolute blocker of pushing out to production.

**Comment by IlyaMatsuev** [comment]
Are there any updates on this?
Maybe there is an option to disable output for this type of error?

**Comment by michaelstaib** [comment]
This is fixed with the latest builds.
