### ISSUE TITLE
Strayberry Shake Unhandled Exception during code generation with query and mutation

### ISSUE THREAD

**Issue by raphaabreu** [ChilliCream/hotchocolate#1696]
**Describe the bug**
I have observed that when using both queries and mutations simultaneously, the ``11.0.0-preview.123`` version is throwing an ``Unhandled Exception`` during the build phase. The final output is also invalid.

**To Reproduce**
1. Schema:
````
schema {
  query: InternalQuery
  mutation: InternalMutation
}

directive @cost(
  complexity: Int! = 1
  multipliers: [MultiplierPath!]
) on FIELD_DEFINITION

type InternalMutation {
  setCount(value: Int!): Int!
}

type InternalQuery {
  count: Int!
}

scalar MultiplierPath
````
2. Query:
````
query GetCount{
  count
}
````
3. Mutation:
````
mutation SetCount($count: Int!) {
	setCount(value: $count)
}
````
````
1>Unhandled Exception: System.InvalidOperationException: The file name `C:\Users\rapha\Projects\QueryAndMutationTest\QueryAndMutationTest\GraphQL\Generated\ITestClient.cs` was already used.
1>   at StrawberryShake.Generators.DirectoryFileHandler.ExecuteGeneratorAsync(GeneratorTask task, ITypeLookup typeLookup, ISet`1 usedNames) in D:\a\1\s\src\StrawberryShake\CodeGeneration\src\Generators\DirectoryFileHandler.cs:line 69
1>   at StrawberryShake.Generators.DirectoryFileHandler.WriteAllAsync(ITypeLookup typeLookup) in D:\a\1\s\src\StrawberryShake\CodeGeneration\src\Generators\DirectoryFileHandler.cs:line 58
1>   at StrawberryShake.Generators.ClientGenerator.BuildAsync() in D:\a\1\s\src\StrawberryShake\CodeGeneration\src\Generators\ClientGenerator.cs:line 362
1>   at StrawberryShake.Tools.GenerateCommandHandler.Compile(GenerateCommandContext context, String path, Configuration config, ClientGenerator generator, IReadOnlyList`1 documents, ICollection`1 errors) in D:\a\1\s\src\StrawberryShake\Tooling\src\dotnet-graphql\GenerateCommandHandler.cs:line 84
1>   at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path, Configuration configuration) in D:\a\1\s\src\StrawberryShake\Tooling\src\dotnet-graphql\CompileCommandHandlerBase.cs:line 121
1>   at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path) in D:\a\1\s\src\StrawberryShake\Tooling\src\dotnet-graphql\CompileCommandHandlerBase.cs:line 91
1>   at StrawberryShake.Tools.CompileCommandHandlerBase`2.ExecuteAsync(TCtx context) in D:\a\1\s\src\StrawberryShake\Tooling\src\dotnet-graphql\CompileCommandHandlerBase.cs:line 70
1>   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
1>   at StrawberryShake.Tools.Program.<Main>(String[] args)
````
**Expected behavior**
The generated code to work properly with both queries and mutations

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.18363 Build 18363

**Additional context**
Failing sample code:
https://github.com/raphaabreu/QueryAndMutationTest

**Comment by michaelstaib** [comment]
Please check with the new version again.
