### ISSUE TITLE
Error using Authorize attribute on classes marked as ExtendObjectType

### ISSUE THREAD

**Issue by jchannon** [ChilliCream/hotchocolate#1822]
I am looking to add ASP.NET Core policy support to my query and mutation classes.  I currently use the approach of the below to register my classes:

```
 services.AddGraphQL(
                SchemaBuilder.New()
                    .AddAuthorizeDirectiveType()
                    .AddQueryType(t => t.Name("Query"))
                    .AddType<SearchClientsQuery>()
);
```

**To Reproduce**
Add `[Authorize]` attribute to the class like so:

```
   [ExtendObjectType(Name = "Query")]
    [Authorize(Policy = "AdminIMSRole")]
    public class SearchClientsQuery
    {
        
        public async Task<ListClientsResult> SearchClients(string searchTerm, 
            SearchType searchType, 
            IResolverContext context, 
            [Service] ManagementApiClient managementApiClient,
            [Service] IHttpContextAccessor contextAccessor, 
            CancellationToken cancellationToken)
        {
              ....
        }
    }
```

Start ASP.NET app and get an error:

```
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at HotChocolate.Types.DirectiveCollection.TryCompleteDirective(ICompletionContext context, DirectiveDefinition definition, ISet`1 processed, Directive& directive)
   at HotChocolate.Types.DirectiveCollection.CompleteCollection(ICompletionContext context)
   at HotChocolate.Types.NamedTypeBase`1.OnCompleteType(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.ObjectType.OnCompleteType(ICompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ICompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__43_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes, TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)

```

**Expected behavior**
No error and for it to handle authorization via the policy name

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version [e.g. 22] : 11.0.0-preview.84

**Additional context**
I tried moving the `[Authorize]` attribute to the method name instead of the class and got the below error:

```
Application startup exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at HotChocolate.Types.DirectiveCollection.TryCompleteDirective(ICompletionContext context, DirectiveDefinition definition, ISet`1 processed, Directive& directive)
   at HotChocolate.Types.DirectiveCollection.CompleteCollection(ICompletionContext context)
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ICompletionContext context, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`2.CompleteField(ICompletionContext context)
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ICompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ICompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__43_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes, TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at HotChocolate.Execution.QueryExecutionBuilder.<>c__DisplayClass9_0.<Populate>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at HotChocolate.AspNetCore.Subscriptions.SubscriptionServiceCollectionExtensions.<>c.<AddMessageHandlers>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)

```

**Comment by PascalSenn** [comment]
Discussion on Slack:
https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1587735980443300

**Comment by michaelstaib** [comment]
@PascalSenn this is a general issue with extension types and attributes. Middleware in general do not seem to work.

**Comment by michaelstaib** [comment]
Related to  #2510

**Comment by michaelstaib** [comment]
This one is fixed.
