### ISSUE TITLE
How to define a field with List<List<int>> type?

### ISSUE THREAD

**Issue by repal-ganut** [ChilliCream/hotchocolate#2123]
I have been using graphql-dotnet and wanted to try hotchocolate

here is code that worked with graphql-dotnet but fails with hotchocolate

`
Field<NonNullGraphType<ListGraphType<NonNullGraphType<ListGraphType<IntGraphType>>>>, List<List<int>>>()
                .Name("screens")
                .Resolve(context => context.Source.Screens);
`
**Describe the bug**

tried code below
`
            descriptor
                .Field(context => context.Screens)
                .Type<NonNullType<ListType<NonNullType<ListType<IntType>>>>>()
                .Name("screens");
`

hotchocolate throws exception
Unable to resolve type reference `Output: HotChocolate.Types.NonNullType<HotChocolate.Types.ListType<HotChocolate.Types.NonNullType<HotChocolate.Types.ListType<HotChocolate.Types.IntType>>>>`. - 

   at HotChocolate.Configuration.CompletionContext.GetType[T](ITypeReference reference)
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ICompletionContext context, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ICompletionContext context, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`2.CompleteField(ICompletionContext context)
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ICompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields)
   at HotChocolate.Types.ObjectType.OnCompleteType(ICompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ICompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__42_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes, TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(DiscoveredTypes discoveredTypes)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()

**To Reproduce**
define a new field with as code below

``
            descriptor
                .Field(context => context.Screens)
                .Type<NonNullType<ListType<NonNullType<ListType<IntType>>>>>()
                .Name("screens");
``
**Expected behavior**
Expect without error to run and schema would be like below as graphql-dotnet does generate;

`type FooType {
  screens: [[Int]!]!}
`

**Comment by michaelstaib** [comment]
Hi @repal-ganut,

we actually left support for nested listed out of version 10. It is implemented with version 11 however. 

Version 11 implements the GraphQL 2020 spec and we are still working on a lot of features there.
