### ISSUE TITLE
CollectFields fails when query by node includes stitched field

### ISSUE THREAD

**Issue by benmccallum** [ChilliCream/hotchocolate#2206]
**Describe the bug**
CollectFields fails when query includes stitched field.

**To Reproduce**
1. Go to https://github.com/benmccallum/HotChocolateRepos (master)
2. Run up just the GatewayService (others aren't needed)
3. Run the following queries and notice how the second fails with marked inclusion of stitched field
```
query getArticleByDbId {
  article(dbId: 1) {
    id
    fieldsCollected
    relatedTasks {
      __typename
      ... on Repair {
        id
        name
      }
    }
  }
}

query getArticleByNode{  
  node(id: "QXJ0aWNsZQppMQ==") {
    ... on Article {
      id
      fieldsCollected
      author
      
      # Inclusion of below breaks things
      # ctx.CollectFields(this); in ArticleType.cs fails
      relatedTasks {
        __typename
        ... on Repair {
          id
          name
        }
      }
    }
  }
}
```

Error in response:
```
"extensions": {
        "message": "Object reference not set to an instance of an object.",
        "stackTrace": "   
   at HotChocolate.Execution.FragmentCollection.CreateInlineFragmentName(InlineFragmentNode inlineFragment)
   at HotChocolate.Execution.FragmentCollection.GetFragment(ObjectType parentType, InlineFragmentNode inlineFragment)
   at HotChocolate.Execution.FieldCollector.ResolveFields(ObjectType type, ISelectionNode selection, Path path, FieldVisibility fieldVisibility, IDictionary`2 fields)
   at HotChocolate.Execution.FieldCollector.CollectFields(ObjectType type, SelectionSetNode selectionSet, Path path, FieldVisibility fieldVisibility, IDictionary`2 fields)
   at HotChocolate.Execution.FieldCollector.CollectFields(ObjectType type, SelectionSetNode selectionSet, Path path)
   at HotChocolate.Execution.CachedQuery.GetOrCollectFields(ObjectType type, SelectionSetNode selectionSet, Func`1 collectFields)
   at HotChocolate.Execution.ExecutionContext.CollectFields(ObjectType objectType, SelectionSetNode selectionSet, Path path)
   at HotChocolate.Execution.ResolverContext.CollectFields(ObjectType typeContext, SelectionSetNode selectionSet, Path path)
   at HotChocolate.Execution.ResolverContext.CollectFields(ObjectType typeContext, SelectionSetNode selectionSet)
   at HotChocolate.Execution.ResolverContext.CollectFields(ObjectType typeContext)
   at HotChocolate.Execution.ResolverContext.HotChocolate.Resolvers.IResolverContext.CollectFields(ObjectType typeContext)
```

**Expected behavior**
I guess the current schema in which node is being resolved (in this case AG_Content) doesn't have the type info of the stitched thing, so perhaps it can just skip those fields, and not return them, but return what it can resolve.

It seems like this works when the `article` field is used, as you can see in the output of `fieldsCollected`, but there's some missing in the `node` field pipeline that isn't able to recognize that stitched fields need to be ignored when collecting.

**HC version**
10.5.2

**Comment by benmccallum** [comment]
Another fun one for you Michael. Not to stress you out or anything on hols :P

**Comment by benmccallum** [comment]
It seems like it's not all fields that cross schema boundaries, as other ones I've got to work. Bizarre. 

FYI, just `relatedTasks { __typename }` is enough to make it break. But it's not `__typename` causing the problem either. e.g. `relatedTasks { ... on Repair { name } }` also fails.

**Comment by michaelstaib** [comment]
This is simple, we have a rewriter for that, which can figure out which fields belong to which schema.
