### ISSUE TITLE
AllowSynchronousIO for batch queries

### ISSUE THREAD

**Issue by joshhubers** [ChilliCream/hotchocolate#2273]
**Describe the bug**
I am getting the following exception when running a batched graphql query:

```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteByte(Byte value)
   at HotChocolate.Execution.Batching.JsonArrayResponseStreamSerializer.SerializeAsync(IResponseStream responseStream, Stream outputStream, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.ExecuteQueryBatchAsync(HttpContext context, IServiceProvider services, IReadOnlyList`1 batch)
   at HotChocolate.AspNetCore.HttpPostMiddleware.ExecuteRequestAsync(HttpContext context, IServiceProvider services)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**To Reproduce**
Running a kestrel server WITHOUT:
```
            services.Configure<KestrelServerOptions>(options =>
            {
                options.AllowSynchronousIO = true;
            });
```
And running a batch query throws an exception

**Expected behavior**
It does not throw an exception

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Related slack thread: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1599066858410900

Hot Chocolate version 10.5.2
Framework netcoreapp3.1

**Comment by michaelstaib** [comment]
We have now integrated the fix into the new version 11 ASP.NET Core middleware. I will port it also back onto version 10.5.x.

**Comment by michaelstaib** [comment]
#2274

**Comment by michaelstaib** [comment]
We have decided to not port it back. We are currently focusing on version 11 where it is now fixed.
