### ISSUE TITLE
StrawberryShakel @delegate Conflict 

### ISSUE THREAD

**Issue by alisan3** [ChilliCream/hotchocolate#2388]
**Describe the bug**
Generate a client of a stiched schema produces the exception below

**Additional context**
1. The name `delegate` was already registered by another type.

   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors() in /home/vsts/work/1/s/src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs:line 681
   at HotChocolate.Configuration.TypeInitializer.CompleteNames(DiscoveredTypes discoveredTypes, Func`1 schemaResolver) in /home/vsts/work/1/s/src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs:line 441
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options) in /home/vsts/work/1/s/src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs:line 111
   at HotChocolate.SchemaBuilder.Create() in /home/vsts/work/1/s/src/HotChocolate/Core/src/Types/SchemaBuilder.Create.cs:line 43
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create() in /home/vsts/work/1/s/src/HotChocolate/Core/src/Types/SchemaBuilder.Create.cs:line 64
   at StrawberryShake.Generators.ClientGenerator.Validate() in /home/vsts/work/1/s/src/StrawberryShake/CodeGeneration/src/Generators/ClientGenerator.cs:line 287
   at StrawberryShake.Tools.GenerateCommandHandler.Compile(GenerateCommandContext context, String path, Configuration config, ClientGenerator generator, IReadOnlyList`1 documents, ICollection`1 errors) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/GenerateCommandHandler.cs:line 72
   at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path, Configuration configuration) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/CompileCommandHandlerBase.cs:line 121
   at StrawberryShake.Tools.CompileCommandHandlerBase`2.Compile(TCtx context, String path) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/CompileCommandHandlerBase.cs:line 91
   at StrawberryShake.Tools.CompileCommandHandlerBase`2.ExecuteAsync(TCtx context) in /home/vsts/work/1/s/src/StrawberryShake/Tooling/src/dotnet-graphql/CompileCommandHandlerBase.cs:line 80
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)

**Comment by michaelstaib** [comment]
This should already work with the new implementation but we still need a test for this.
