### ISSUE TITLE
Error bind-value in blazor with entity  Generated by Strawberryshake

### ISSUE THREAD

**Issue by thiemdp** [ChilliCream/hotchocolate#2594]
hi!
I'm using Strawberryshake Generated from queries.graphql.
but when @bind entity to template error!
Please help me!
> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type 'StrawberryShake.Optional`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.
System.InvalidOperationException: The type 'StrawberryShake.Optional`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.
   at Microsoft.AspNetCore.Components.BindConverter.ParserDelegateCache.MakeTypeConverterConverter[Optional`1]()
   at Microsoft.AspNetCore.Components.BindConverter.ParserDelegateCache.Get[Optional`1]()
   at Microsoft.AspNetCore.Components.EventCallbackFactoryBinderExtensions.CreateBinder[Optional`1](EventCallbackFactory factory, Object receiver, Action`1 setter, Optional`1 existingValue, CultureInfo culture)
   at GraphQLBlazor.Client.Pages.NhomVatTu.NhomVatTu.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by michaelstaib** [comment]
Looks like this is due to the optional type of the input objects. We are working on refining that.

**Comment by tobias-tengler** [comment]
I'm closing this for now. If there is still an issue feel free to re-open.
