### ISSUE TITLE
extend type in Stitching.json breaks an app

### ISSUE THREAD

**Issue by lawrentiy** [ChilliCream/hotchocolate#2683]
**Describtion**
Clone https://github.com/ChilliCream/hotchocolate-examples 
And it isn`t work properly

**Steps to reproduce**
1. Clone https://github.com/ChilliCream/hotchocolate-examples 
2. Fix urls in appsettings.json for projects  https://github.com/lawrentiy/hotchocolate-examples/pull/1/commits/a028b87b8a3d1d6dd03a85535eb90e5a744dbdaf
3. Run all projects with debug config
4. Try to get schema for Gateway project
5. 500 error with callstack bellow

```
 Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM4IKKNJGTF2", Request id "0HM4IKKNJGTF2:00000003": An unhandled exception was thrown by the application.
      System.ArgumentException: An item with the same key has already been added. Key: Query
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
         at HotChocolate.Stitching.Merge.AddSchemaExtensionRewriter.MergeContext..ctor(DocumentNode schema, DocumentNode extensions)
         at HotChocolate.Stitching.Merge.AddSchemaExtensionRewriter.AddExtensions(DocumentNode schema, DocumentNode extensions)
         at HotChocolate.Stitching.Utilities.StitchingSchemaInterceptor.AddExtensions(DocumentNode schema, IReadOnlyCollection`1 typeExtensions)
         at HotChocolate.Stitching.Utilities.StitchingSchemaInterceptor.OnBeforeCreate(IDescriptorContext context, ISchemaBuilder schemaBuilder)
         at HotChocolate.Configuration.AggregateSchemaInterceptor.OnBeforeCreate(IDescriptorContext context, ISchemaBuilder schemaBuilder)
         at HotChocolate.SchemaBuilder.Setup.CreateContext(SchemaBuilder builder, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
         at HotChocolate.SchemaBuilder.Create()
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Expected**
I`ll see an stitched scheme for gateway project

**Desktop**
 - OS: Windows
 - .NET 5
 - Rider

**Additional**
If i concatenate all extended types in Stitching.json in separated types with unigue names all works fine.

PS: what can I help to solve that problem?

**Comment by sgebhardt** [comment]
I'm currently working on upgrading from v10.5.3 to v11 and have the same problem.

If I set ignoreRootTypes, the error disappears, but I struggle to extend the query properly.
`.AddRemoteSchema("users", true)`

Is there any documentation to Shema Stitching with v11?

**Comment by michaelstaib** [comment]
We are working on the documentation at the moment. It will take a couple more days.

**Comment by michaelstaib** [comment]
We are also working on the examples... the centralized example is corrupt. The federated examples work.

**Comment by sgebhardt** [comment]
Do i have to set ignoreRootTypes always to true if i want to stitch a other GraphQL API? 
Otherwise I got the Exception: "An item with the same key has already been added. Key: Query".

**Comment by lawrentiy** [comment]
The first point (federated)
ignoreRootTypes can`t solve taht problem.
ignoreRootTypes = true, then error **The object type `Query` has to at least define one field in order to be valid** happens
ignoreRootTypes = false, then error **The name `Query` was already registered by another type** happens

The second point (sentrilized)
As I see, federated and centrilized examples have on one difference - 
.AddTypeExtensionsFromFile("./Stitching.graphql")

That means. There are at least 3 problems in exmples "out of the box".
@michaelstaib, what can I do to start? Or how can I help you to solve?
