### ISSUE TITLE
Assembly Issue

### ISSUE THREAD

**Issue by Sujit115** [ChilliCream/hotchocolate#2693]
1. Could not load type 'HotChocolate.Types.IInputType' from assembly 'HotChocolate.Types, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null'. (RootQUery), 

         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
         at HotChocolate.SchemaBuilder.Create()
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by PascalSenn** [comment]
make sure all versions of HotChocolate.xx.xx and StrawBerryShake.xx.xx are aligned

**Comment by Sujit115** [comment]
I have not used any StrawBerryShake.

**Comment by PascalSenn** [comment]
how does you csproj look like?

**Comment by Sujit115** [comment]
Guy's I have solved the problem, The problem was I was using Hotchocolate.Types.Selection but it was 10.5.5 and it don't work on hotchocolate 11 now the question is how can I use the selection middlware.

**Comment by Sujit115** [comment]
thanks to @PascalSenn  for giving me a hint.

**Comment by Sujit115** [comment]
Is it the issue that it is not working with hothocolate 11??? because no release for selections.

**Comment by PascalSenn** [comment]
@Sujit115  you have to use UseProjections

https://chillicream.com/docs/hotchocolate/fetching-data/projections/

**Comment by michaelstaib** [comment]
Can this be closed?

**Comment by Sujit115** [comment]
use projection is also not working guys.



{
  "message": "Server Not Reachable",
  "name": "ServerNetworkError",
  "statusText": "Failed to fetch"
}


should I fallback @michaelstaib to 10.5.5 because there are so many bugs. in 11. 

error message pipeline is also not working.

**Comment by michaelstaib** [comment]
What bugs are you talking about?

**Comment by Sujit115** [comment]
okay maybe it's my machine problem you can close it.

**Comment by michaelstaib** [comment]
We also have a slack channel where you can sort things out. Look at the readme for the link.
