### ISSUE TITLE
Unable to resolve type reference `Output: [Object!]!`

### ISSUE THREAD

**Issue by Damon-cxl** [ChilliCream/hotchocolate#2763]
In my owner model, i need a `public` method that return type is `object[]` or `IEnumerable<object>`
```C#
public class Speaker
     {
         public Guid Id { get; set; }

        public object[] GetKeys()
        {
            return new object[1]
            {
                Id
            };
        }
```
the exception i get like this:
```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `Output: [Object!]!`. (HotChocolate.Types.ObjectType<ConferencePlanner.GraphQL.Data.Speaker>)

   at HotChocolate.Configuration.TypeCompletionContext.GetType[T](ITypeReference typeRef) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeCompletionContext.cs:line 100
   at HotChocolate.Types.FieldBase`2.OnCompleteField(ITypeCompletionContext context, TDefinition definition) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\FieldBase.cs:line 63
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, TDefinition definition) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\OutputFieldBase.cs:line 47
   at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ObjectFieldDefinition definition) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\ObjectField.cs:line 86
   at HotChocolate.Types.FieldBase`2.CompleteField(ITypeCompletionContext context) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\FieldBase.cs:line 52
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ITypeCompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\Helpers\FieldInitHelper.cs:line 67
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\ObjectType.cs:line 109
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Types\TypeSystemObjectBase~1.cs:line 120
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|29_0(RegisteredType registeredType) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 429
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 458
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes() in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 434
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeInitializer.cs:line 126
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Setup.cs:line 181
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Setup.cs:line 35
   at HotChocolate.SchemaBuilder.Create() in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Create.cs:line 5
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create() in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Types\SchemaBuilder.Create.cs:line 7
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 265
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 226
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 80
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorResolver.cs:line 56
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\Core\src\Execution\RequestExecutorProxy.cs:line 156
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\AspNetCore\src\AspNetCore\HttpPostMiddleware.cs:line 61
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\AspNetCore\src\AspNetCore\HttpPostMiddleware.cs:line 51
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context) in D:\PlanE\Learn2\Graphql\hotchocolate\src\HotChocolate\AspNetCore\src\AspNetCore\WebSocketSubscriptionMiddleware.cs:line 35
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
my Query object is:
```C#
public class Query
    {
        public IQueryable<Speaker> GetSpeakers([Service] ApplicationDbContext context) =>
            context.Speakers;
    }
```
in my startup:
```C#
public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
             services.AddDbContext<ApplicationDbContext>(options => options.UseSqlite("Data Source=conferences.db"));

             services.AddGraphQLServer()
                    .AddQueryType<Query>()
                    .AddMutationType<Mutation>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGraphQL();
            });
        }
    }
```
Versions:

- HC Version 11.1.0-preview.6

- Net 5

**any way to avoid this exception？ please help!**

**Comment by Damon-cxl** [comment]
[https://github.com/abpframework/abp/issues/6007](url)
