### ISSUE TITLE
UseFirstOrDefault and UseSingleOrDefault cause type errors when used with mutations. 

### ISSUE THREAD

**Issue by Kcola** [ChilliCream/hotchocolate#2917]
When a mutation returns an IQueryable and uses the UseFirstOrDefault / UseSingleOrDefault attribute it causes an error. (11.0.9-preview.3) 

**To Reproduce**
Create a mutation resolver that returns an IQueryable with the `[UseFirstOrDefault]` or `[UseSingleOrDefault]` attribute.
```csharp
    [UseFirstOrDefault, UseProjection]
    public IQueryable<Document> AddBook([Service] Repository _repository, Book book){
        _repository.Add(book);
        return _repository.Get<Document>().Where(x=>x.Docid == book.Docid);
    } 
```
**Error**
```logs
      1. Unable to resolve type reference `None: Document`. (HotChocolate.Types.ObjectType<Mutation>)
      
         at HotChocolate.Configuration.TypeCompletionContext.GetType[T](ITypeReference typeRef)
         at HotChocolate.Types.FieldBase`2.OnCompleteField(ITypeCompletionContext context, TDefinition definition)
         at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, TDefinition definition)
         at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ObjectFieldDefinition definition)
         at HotChocolate.Types.FieldBase`2.CompleteField(ITypeCompletionContext context)
         at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ITypeCompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields)
         at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|32_0(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
         at HotChocolate.SchemaBuilder.Create()
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetSchemaAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.ToolOptionsFileMiddleware.Invoke(HttpContext context)
         at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.1

**Comment by PascalSenn** [comment]
Hi @Kcola 

I try to reproduce this issue in #2921 but the tests passes. Can you provide a failing tests?

**Comment by Kcola** [comment]
I added #2924 with failing tests. The bug shows up when the input type of the mutation has a many to many relationship with the output type. It might also show up in other cases but that was the simplest case I could find after playing around with my models for a bit. I'm like 70% sure the bug has to do with the input type though. Hopefully this helps.

**Comment by PascalSenn** [comment]
fixed and pushed 👍 
Thanks for the repro!

**Comment by PascalSenn** [comment]
I think this is fixed

**Comment by lucas-garrido** [comment]
This still an issue
