### ISSUE TITLE
No compatible constructor found for input type type `System.Security.Claims.Claim`

### ISSUE THREAD

**Issue by AliHadiOzturk** [ChilliCream/hotchocolate#3007]
Hi, i'm trying add Hotchocolate to my project. 

I just followed [Adding GraphQL Section](https://github.com/ChilliCream/graphql-workshop/blob/c07b36885d7e2a1822171c8a1c2bfad393cf946e/docs/1-creating-a-graphql-server-project.md#adding-graphql) nothing else.

I'm using ASP.Net Identity with Jwt authentication.

Getting this error

```
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM6BEDVGVU5G", Request id "0HM6BEDVGVU5G:0000000B": An unhandled exception was thrown by the application.
      System.InvalidOperationException: No compatible constructor found for input type type `System.Security.Claims.Claim`.
      Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties.There was no way to set the following properties: Issuer, OriginalIssuer, Properties, Subject, Type, Value, ValueType.
         at HotChocolate.Utilities.Serialization.InputObjectConstructorResolver.GetCompatibleConstructor(Type type, IReadOnlyDictionary`2 properties)
         at HotChocolate.Utilities.Serialization.InputObjectConstructorResolver.GetConstructor(Type type, IEnumerable`1 properties)
         at HotChocolate.Types.InputObjectType.OnCompleteType(ITypeCompletionContext context, InputObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|32_0(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)        
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
         at HotChocolate.SchemaBuilder.Create()
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Necommerce.app.infrastructure.middleware.OptionsMiddleware.Invoke(HttpContext context) in D:\netinux\ecommerce\server\app\infrastructure\middleware\OptionsMiddleware.cs:line 21      
         at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
         at AutoWrapper.AutoWrapperMiddleware.InvokeAsync(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

This is my startup.cs

```csharp
    public void ConfigureServices(IServiceCollection services)
        {
            var conString = Configuration.GetConnectionString("DefaultConnection");
            services.AddDbContext<DataContext>(context =>
            {
                context.UseNpgsql(conString);
            });


            services
                .AddGraphQLServer()
                .AddQueryType<Query>();

            services.Configure<IdentityOptions>(options =>
            {
                options.Password.RequireDigit = false;
                options.Password.RequireLowercase = false;
                options.Password.RequireUppercase = false;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequiredLength = 3;
            });

            services.AddControllers();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Swagger", Version = "v1" });
            });

            services.AddAutoMapper(typeof(MappingProfiles));
            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<DataContext>()
                .AddDefaultTokenProviders();

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear(); // => remove default claims

            services.AddAuthorization(options =>
                {
                    options.AddPolicy("RequireAdminRole", policy => policy.RequireRole("Admin"));
                    options.AddPolicy("AuthenticatedUser", policy => policy.RequireAuthenticatedUser());
                });
            services
                .AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.RequireAuthenticatedSignIn = false;
                })
                .AddJwtBearer(cfg =>
                {
                    cfg.RequireHttpsMetadata = false;
                    cfg.SaveToken = true;
                    cfg.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidIssuer = Configuration.GetValue<string>("JwtConfiguration:Issuer"),
                        ValidAudience = Configuration.GetValue<string>("JwtConfiguration:Issuer"),
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Configuration.GetValue<string>("JwtConfiguration:Key"))),
                        ClockSkew = TimeSpan.Zero
                    };
                });


            services.AddMvc(config =>
            {
                var policy = new AuthorizationPolicyBuilder()
                .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)
                .RequireAuthenticatedUser()
                .Build();

                // config.Filters.Add(new JwtAuthenticationFilter(policy));
            }
            ).AddNewtonsoftJson(options =>
            {
                options.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.Local;
            });

            services.AddLogging(config =>
                {
                    config.ClearProviders();
                    config.AddConsole();
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IConfiguration configuration)
        {

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                app.UseSwaggerUI(c =>
                    {
                        c.SwaggerEndpoint("/swagger/v1/swagger.json", "Swagger");
                    });
            });

            app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(configuration.GetValue<string>("StoragePath")),
                RequestPath = "/files/images"
            });
            app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { UseCustomSchema = true, IsApiOnly = false, BypassHTMLValidation = true });

            app.UseOptions();
            app.UseLogFilter();
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
            app.UseCors(opt => opt.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod());
            //app.UseAuthentication();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();



            if (env.EnvironmentName == Environments.Development)
            {
                app.UseDeveloperExceptionPage();
            }


            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGraphQL();
                endpoints.MapControllers().RequireAuthorization();
            });

        }
```

**Comment by AliHadiOzturk** [comment]
Hi, i resolve the issue. I'm going to try to explain why i'm getting this exception.

When i start my project i wan't to customize the Identity models.
I follow an article provided by [Microsoft](https://docs.microsoft.com/en-US/aspnet/core/security/authentication/customize-identity-model?view=aspnetcore-5.0#add-all-user-navigation-properties) and this article show how to customize the Identity models.
Like shown in the article i added all navigation properties to the user. I don't know why i added there navigation properties. Maybe ı thought i needed there properties :)
```csharp
public class ApplicationUser : IdentityUser
{
    public virtual ICollection<IdentityUserClaim<string>> Claims { get; set; }
    public virtual ICollection<IdentityUserLogin<string>> Logins { get; set; }
    public virtual ICollection<IdentityUserToken<string>> Tokens { get; set; }
    public virtual ICollection<IdentityUserRole<string>> UserRoles { get; set; }
}
```

Then like shown in the article i configure my `ApplicationDbContext `
```csharp
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ApplicationUser>(b =>
        {
            // Each User can have many UserClaims
            b.HasMany(e => e.Claims)
                .WithOne()
                .HasForeignKey(uc => uc.UserId)
                .IsRequired();

            // Each User can have many UserLogins
            b.HasMany(e => e.Logins)
                .WithOne()
                .HasForeignKey(ul => ul.UserId)
                .IsRequired();

            // Each User can have many UserTokens
            b.HasMany(e => e.Tokens)
                .WithOne()
                .HasForeignKey(ut => ut.UserId)
                .IsRequired();

            // Each User can have many entries in the UserRole join table
            b.HasMany(e => e.UserRoles)
                .WithOne()
                .HasForeignKey(ur => ur.UserId)
                .IsRequired();
        });
    }
}
```

As you can see i just added all properties and configure there many-to-many relationships.

Now i coming to the where it gives exception.
I have an object lets say it `Product` and then in the product object i have an relationship to the `ApplicatinUser`.

```csharp
public class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public ApplicationUser User { get;set; }
    }
```


This was fine until i added [Hot Chocolate](https://github.com/ChilliCream/hotchocolate)  to the project and configure GraphQL.
Like i said in the issue i just followed the basic [adding graphql docs](https://github.com/ChilliCream/graphql-workshop/blob/c07b36885d7e2a1822171c8a1c2bfad393cf946e/docs/1-creating-a-graphql-server-project.md#adding-graphql)

And i create a `Query ` class. Inside this class has an method
```csharp
public IQueryable<Product> GetProducts([Service] DataContext context) =>
             context.Products;
```
I started my project and go to `/graphql `path on browser. Then i get the exception. 

I resolved the issue with removing the configuration i made in my `ApplicationUser ` and `ApplicationDbContext ` classes.
```csharp
public class ApplicationUser : IdentityUser
{
}
```
```csharp
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<ApplicationUser>(b =>
        {
           
        });
    }
}
```

Then i start my project and go to `/graphql` path on browser again. And it's just working like a charm.

I think the exception caused because `IdentityUserClaim<string>` object has `System.Security.Claims.Claim` object in it. When hotchocolate try to create the schema throwing the exception because `Claim `object has no constructor that getting `Issuer, OriginalIssuer, Properties, Subject, Type, Value, ValueType` parameters.

You can check the constructors in the [Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim.-ctor?view=net-5.0)

**Comment by hassanrazakhalid** [comment]
I'm sorry but what if IdentityDbContext needs to customized. You removed all the params. Its ok as a work around but definitely not a permanent solution.

**Comment by AliHadiOzturk** [comment]
> Sorry but what if IdentityDbContext needs to customized. You removed all the params. Its ok as a work around but definitely not a permanent solution.

Yes, i agree it's not a permanent solution. Maybe new releases fixed the issue i don't know exactly. After 3 years i didn't try it again.
