### ISSUE TITLE
UseProjection broken after upgrading from HC version 11.0.8 to 11.0.9

### ISSUE THREAD

**Issue by msmolcic** [ChilliCream/hotchocolate#3028]
**Describe the bug**
I upgraded HC from version 11.0.8 to 11.0.9 and queries that worked before started throwing an `Unexpected Execution Error`. When I remove `[UseProjection]` attribute above the query, it starts working again, but I'd like to be able to use projections.

```
"message": "Unexpected Execution Error",
"extensions": {
  "message": "Operation is not valid due to the current state of the object.",
  "stackTrace": "
    at HotChocolate.Data.Projections.Handlers.QueryablePagingProjectionOptimizer.RewriteSelection(SelectionOptimizerContext context, Selection selection)
    at HotChocolate.Data.Projections.ProjectionProvider.RewriteSelection(SelectionOptimizerContext context, Selection selection)
    at HotChocolate.Data.Projections.ProjectionOptimizer.OptimizeSelectionSet(SelectionOptimizerContext context)
    at HotChocolate.Execution.Processing.OperationCompiler.OptimizeSelectionSet(CompilerContext context)
    at HotChocolate.Execution.Processing.OperationCompiler.Visit(Stack`1 backlog)
    at HotChocolate.Execution.Processing.OperationCompiler.Compile(String operationId, DocumentNode document, OperationDefinitionNode operation, ISchema schema, ObjectType rootType, IEnumerable`1 optimizers)
    at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.WritePersistedQueryMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.ReadPersistedQueryMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)
    at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)"
}
```

**To Reproduce**
I've created a separate branch on one of the GitHub repositories I used for the previous bug report, you can find it [here](https://github.com/msmolcic/HotChocolateDemo/tree/bug/projections-not-working-with-HC.11.0.9).

1. Run the project.
2. Go to Banana Cake Pop IDE in the browser.
3. Try executing a simple query:
```
query GetBorrowers {
  borrowers(skip: 0, take: 10) {
    items {
      id
      name
    }
  }
}
```
4. Check an error in the result window of Banana Cake Pop IDE.

**Expected behavior**
The query should return an actual result set.

**Desktop:**
 - OS: Windows 10 Pro 64-bit (20H2)
 - HC version: 11.0.9

**Comment by bram209** [comment]
I can confirm this issue on `11.1.0-preview.57`, it has something to do with `UseOffsetPaging` in combination with `UseProjections`.
Cursor-based `UsePaging` middleware seems to work fine.

**Comment by msmolcic** [comment]
I tested this one with the `11.1.0-rc.6` and it seems to be working now. @bram209 could you also confirm this so that we can close it?

**Comment by michaelstaib** [comment]
Closing this issue.

**Comment by reinux** [comment]
I'm having this issue on 11.3.4. It happens for me when the result is an interface or a collection of interfaces.
