### ISSUE TITLE
Changed argument name with NamingConventions is not found on mutations

### ISSUE THREAD

**Issue by nkovacic** [ChilliCream/hotchocolate#3088]
**Describe the bug**
When argument name in pure code first is changed with extending DefaultNamingConventions and GetArgumentMethod, it is not found on subsequent mutation execution, it returns that the old argument name is not found on the field

**To Reproduce**
1. Extend DefaultNamingConventions
````csharp
public class ExtendedNamingConventions: DefaultNamingConventions
    {
        public override NameString GetTypeName(Type type, TypeKind kind)
        {
            if (kind == TypeKind.InputObject)
            {
                var name = CleanInputEnding(type.Name);

                return new NameString(name);
            }
            
            else if (kind == TypeKind.Object)
            {
                var name = CleanEnding(type.Name);

                return new NameString(name);
            }

            return base.GetTypeName(type, kind);
        }

        public override NameString GetArgumentName(ParameterInfo parameter)
        {
            var nameString = base.GetArgumentName(parameter);

            if (nameString == null)
            {
                return nameString;
            }

            var name = CleanInputEnding(nameString.ToString());

            return new NameString(name.ToCamelCase());
        }

        private string CleanInputEnding(string name)
        {
            name = CleanEnding(name);

            if (!name.EndsWith("input", StringComparison.OrdinalIgnoreCase))
            {
                name += "Input";
            }

            return name;
        }

        private string CleanEnding(string name)
        {
            if (name.EndsWith("command", StringComparison.OrdinalIgnoreCase))
            {
                name = name.Replace("command", "", StringComparison.OrdinalIgnoreCase);
            }

            if (name.EndsWith("viewModel", StringComparison.OrdinalIgnoreCase))
            {
                name = name.Replace("viewModel", "", StringComparison.OrdinalIgnoreCase);
            }

            return name;
        }
    }
````
2. Create pure code first mutation extension
````csharp
[ExtendObjectType(nameof(Mutation))]
    public class IdentityMutation
    {
        public async Task<TokenResponseViewModel> Login(
            PasswordRequestTokenCommand passwordRequestTokenCommand, [Service] IMediator mediator, CancellationToken cancellationToken)
        {
            return await mediator.Send(passwordRequestTokenCommand, cancellationToken);
        }
}
````
3. Test in BCP
![image](https://user-images.githubusercontent.com/3670753/108597635-4a0d5180-738a-11eb-8e0b-decd7d898cac.png)

**Expected behavior**
It should find the rewritten argument name which is `passwordRequestTokenInput` instead of `passwordRequestTokenCommand`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v11,0.9

**Comment by PascalSenn** [comment]
Hi @nkovacic  

I added a test for this in #3092 
Could not reproduce this behaviour, could you provide a reproduction of this?

**Comment by nkovacic** [comment]
@PascalSenn had a quick look at your tests, but they only test if the arguments, types are correctly renamed in the schema? 
The issue arises when a mutation is called from bcp (or probably any graphql client).  Schema is renamed correctly.

**Comment by PHILLIPS71** [comment]
It looks as though this is still occurring in HotChocolate v13.7.0. I've setup a snake case naming convention and mutation conventions @PascalSenn can this be re-opened?

![image](https://github.com/ChilliCream/graphql-platform/assets/6015550/c58ceb99-c286-4b7a-bdb8-0c246b5304c9)

![image](https://github.com/ChilliCream/graphql-platform/assets/6015550/46aa9886-1b08-4682-b107-2b144100b08e)

**Comment by sergiu-enache** [comment]
after upgrading to 13.8.1 only for one subgraph I get this `System.NullReferenceException: 'Object reference not set to an instance of an object.'` exception at startup.

I think is related to last fix for this issue, I will try to figure out what causes this only on this project (maybe some mutation input)

here is the StackTrace
`   at HotChocolate.Types.EnumType.ParseValue(Object runtimeValue)
   at HotChocolate.Types.InputFormatter.FormatValueLeaf(Object runtimeValue, ILeafType type, Path path)
   at HotChocolate.Types.MutationConventionTypeInterceptor.TryApplyInputConvention(IResolverCompiler resolverCompiler, ObjectFieldDefinition mutation, Options options)
   at HotChocolate.Types.MutationConventionTypeInterceptor.OnBeforeCompleteMutation(ITypeCompletionContext completionContext, ObjectTypeDefinition definition)
   at HotChocolate.Configuration.TypeInitializer.MergeTypeExtensions()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.Warmup.ExecutorWarmupService.ExecuteAsync(CancellationToken stoppingToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at RFERL.Modules.CMSModule.API.Program.Main(String[] args) in C:\Repos\rferl.modules.cms\src\RFERL.Modules.CMSModule.API\Program.cs:line 33`
