### ISSUE TITLE
The type of the member of the declaring type is unknown

### ISSUE THREAD

**Issue by dominik4545** [ChilliCream/hotchocolate#3114]
Dear ChilliCream-team,

unfortunately I am facing an issue when using `uint` as type of properties in my class. Is the type `uint` not supported by HC?

My class is looking like this:
```
using core.util.extensions;
using core.util.validation;
using core.util.validation.provider;
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using System.Linq;
using System.Runtime.CompilerServices;

namespace core.data.setting {

    /// <summary>
    /// Represents one setting.
    /// </summary>
    public class Setting : IDataValidationProvider {

 	// [...]

        /// <summary>
        /// Maximum length of a string or maximum size of a list/array/dictionary
        /// </summary>
        public uint MaxLength {
            get;
            protected set;
        }

        /// <summary>
        /// Highest value of a numeric value
        /// </summary>
        public string? MaxValue {
            get;
            protected set;
        }

 	// [...]

        /// <summary>
        /// Checks whether the given value is valid for the <see cref="Setting"/>.
        /// </summary>
        /// <param name="value">Value to be checked</param>
        /// <returns>True if it is valid and false otherwise</returns>
        public bool IsValid(string value) {
            return DataValidator.GetValidator(this).IsValid(value, this.DataType, false);
        }

 	// [...]

    }
}
```

My query-class looks like this:
```
using core.data;
using core.data.setting;
using core.util.extensions;
using HotChocolate;
using HotChocolate.Data;
using HotChocolate.Types;
using HotChocolate.Types.Relay;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace core.graphql.setting {

    /// <summary>
    /// Collection of GraphQL-queries for <see cref="Setting"/>.
    /// </summary>
    [ExtendObjectType(Name = "Query")]
    public class SettingQueryCollection {

        /// <summary>
        /// Return all <see cref="Setting"/>-elements.
        /// </summary>
        /// <param name="context"></param>
        /// <returns></returns>
        [UseApplicationDatabaseContext]
        [UsePaging(typeof(NonNullType<SettingType>))]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Setting> GetSettings([ScopedService] ApplicationDatabaseContext context) {
            // TODO: Sortierung nach HumanReadableName
            return context.Settings.OrderBy(x => x.Name);
        }

        /// <summary>
        /// Return one <see cref="Setting"/> using its identifier.
        /// </summary>
        /// <param name="identifier"></param>
        /// <param name="dataLoader"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        public Task<Setting> GetSettingByIdentifierAsync([ID(nameof(Setting))] long identifier, SettingByIdentifierDataLoader dataLoader, CancellationToken cancellationToken) {
            return dataLoader.LoadAsync(identifier, cancellationToken);
        }
    }
}
```

The exception thrown is the following:
```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. The type of the member MaxLength of the declaring type Setting is unknown
 (HotChocolate.Data.Filters.FilterInputType<core.data.setting.Setting>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetSchemaAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.ToolOptionsFileMiddleware.Invoke(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

My problem is, there is no `Errors` property as I tried to open BCP in this case and it was not able to refresh the schema.

Thanks in advance,
Dominik

**Comment by michaelstaib** [comment]
Hi Dominik,

support is coming with 11.1

https://github.com/ChilliCream/hotchocolate/pull/3048

@wonbyte and @joslat are working on many new scalars.

**Comment by dominik4545** [comment]
Thanks @michaelstaib for clarification! I am waiting for this release then :)

PS: Many thanks for your excelent documentation! This was one of the main reasons why I chose your project instead of any other GraphQL-library.

**Comment by michaelstaib** [comment]
I am closing this issue since it is already tracked under pr #3048
