### ISSUE TITLE
An issue when bringing spatial data on schema stitching feature

### ISSUE THREAD

**Issue by aouimar** [ChilliCream/hotchocolate#3215]
Hi,
I'm trying to use the schema stitching feature; it worked fine on the gateway
until i changed my services, to support spatial data and the spatial data it works fine on his own services

but on the gateway, after those changes i occured on services, the gateway send me an error;
saying that unable to resolve type reference `input: Position`

`fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to resolve type reference `Input: Position`. (HotChocolate.Types.InputObjectType)

         at HotChocolate.Configuration.TypeCompletionContext.GetType[T](ITypeReference typeRef) in C:\Users\sprinter\source\repos\hotchocolate\src\HotChocolate\Core\src\Types\Configuration\TypeCompletionContext.cs:line 101
         at HotChocolate.Types.FieldBase`2.OnCompleteField(ITypeCompletionContext context, TDefinition definition) in C:\Users\sprinter\source\repos\hotchocolate\src\HotChocolate\Core\src\Types\Types\FieldBase.cs:line 68
         at HotChocolate.Types.InputField.OnCompleteField(ITypeCompletionContext context, InputFieldDefinition definition) in C:\Users\sprinter\source\repos\hotchocolate\src\HotChocolate\Core\src\Types\Types\InputField.cs:line 176
         at HotChocolate.Types.FieldBase`2.CompleteField(ITypeCompletionContext context) in C:\Users\sprinter\source\repos\hotchocolate\src\HotChocolate\Core\src\Types\Types\FieldBase.cs:line 57`

my cofigure services is like:

`public void ConfigureServices(IServiceCollection services)
        {
            //services.AddHttpClient(Travelers, c => c.BaseAddress = new Uri("http://localhost:8081/graphql"));
            services.AddHttpClient(Drivers, c => c.BaseAddress = new Uri("http://localhost:8080/graphql"));
            //services.AddHttpClient(Paths, c => c.BaseAddress = new Uri("http://localhost:8082/graphql"));

            services
                .AddGraphQLServer()
                .AddRemoteSchema(Drivers)
                .AddSpatialTypes()
}`

Any help, will be apprecited,
Thanks, in Advance

**Comment by aouimar** [comment]
@PascalSenn gived me a workaround for this is including the GeoJsonPositionType
If anyone facing the same issue

```
//services.AddHttpClient(Travelers, c => c.BaseAddress = new Uri("http://localhost:8081/graphql"));
            services.AddHttpClient(Drivers, c => c.BaseAddress = new Uri("http://localhost:8080/graphql"));
            //services.AddHttpClient(Paths, c => c.BaseAddress = new Uri("http://localhost:8082/graphql"));

            services
                .AddGraphQLServer()
                .AddType<GeoJsonPositionType>()
                //.AddRemoteSchema(Travelers)
                //.AddRemoteSchema(Paths)
                .AddRemoteSchema(Drivers);

            services
               .AddGraphQL(Drivers)
               .AddType<GeoJsonPositionType>();
```

Thanks
