### ISSUE TITLE
UnionType marker interface is treated as invalid due to having no fields

### ISSUE THREAD

**Issue by oising** [ChilliCream/hotchocolate#3348]
Using sdl first:

```gql
union Device = A | B | C
```

My complex type and marker:
```c#
public class Device : UnionType<IDeviceUnionType> {}
public interface IDeviceUnionType   {}
```

My model types implement the marker interface, and all the above are bound using `BindComplexType<..>()`.

Attempts to query (using BCP) yield:

```
HotChocolate.SchemaException: For more details look at the `Errors` property.
1. Interface `IDeviceUnionType` has no fields declared. (HotChocolate.Types.InterfaceType<MyTypes.GraphQL.IDeviceUnionType>)
   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
   at HotChocolate.SchemaBuilder.Create()
   ...
```

versions tested:
v87 - rc.0

**Comment by michaelstaib** [comment]
Can you post a repro. I think there is something wrong with your setup.

**Comment by oising** [comment]
something was, indeed, wrong with my repo.
