### ISSUE TITLE
The error "String cannot parse the given literal of type `VariableNode`" when using query variables and ListType

### ISSUE THREAD

**Issue by yansklyarenko** [ChilliCream/hotchocolate#3606]
There's a simple model class (note the `AND` property):

```csharp
public class SearchPredicate
{
    public string? Name { get; set; }
    public string? Value { get; set; }
    public IEnumerable<SearchPredicate>? AND { get; set; }
}
```

And there's a corresponding graph type class:

```csharp
  public class SearchPredicateGraphType : InputObjectType<SearchPredicate>
  {
      protected override void Configure(IInputObjectTypeDescriptor<SearchPredicate> descriptor)
      {
          descriptor.Field(t => t.Name).Type<StringType>().Name("name");
          descriptor.Field(t => t.Value).Type<StringType>().Name("value");
          descriptor.Field(t => t.AND).Type<ListType<SearchPredicateGraphType>>().Name("AND");

          base.Configure(descriptor);
      }
  }

```

The main query type defines the field called `Search` with the argument called `where` of type `SearchPredicateGraphType`:

```csharp
descriptor
    .Field("search")
    .Argument("where", a => a.Type<NonNullType<SearchPredicateGraphType>>())
    .Type<SearchResultsGraphType>()
    .Resolver(ResolveSearchResults);

```

So, with this simple setup in place, one can run the following query:

```graphql
query {
  search (where: { AND: [
    { name: "A1" value:"B1" }
    { name: "A2" value:"B2" }
  ] }) {
    total
  }
}
```

This works just fine. 
Now replace the second value (`B2`) with the query variable. Like this:

```graphql
query ($var2: String!) {
  search (where: { AND: [
    { name: "A1" value:"B1" }
    { name: "A2" value:$var2 }
  ] }) {
    total
  }
}
```

where the `$var2` is defined like: `{ "var2":"B2" }`.

This one also works fine, but **_as soon as I change the order of the objects inside the `AND` list_**:

```graphql
query ($var2: String!) {
  search (where: { AND: [
    { name: "A2" value:$var2 }
    { name: "A1" value:"B1" }
  ] }) {
    total
  }
}

```
It explodes with the following error: _String cannot parse the given literal of type `VariableNode`._
The stack trace is the following:

```
   at HotChocolate.Types.StringType.ParseLiteral(IValueNode literal)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode source, IDictionary`2 target, ITypeConversion converter)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode value, InputObjectFactory factory, ITypeConversion converter)
   at HotChocolate.Types.InputObjectType.<>c__DisplayClass28_1.<OnCompleteType>b__4(ObjectValueNode ov)
   at HotChocolate.Types.InputObjectType.ParseLiteral(IValueNode literal)
   at HotChocolate.Types.ListType.CreateList(ListValueNode listLiteral)
   at HotChocolate.Types.ListType.ParseLiteral(IValueNode literal)
   at HotChocolate.Types.NonNamedType.HotChocolate.Types.IInputType.ParseLiteral(IValueNode literal)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode source, IDictionary`2 target, ITypeConversion converter)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode value, InputObjectFactory factory, ITypeConversion converter)
   at HotChocolate.Types.InputObjectType.<>c__DisplayClass28_1.<OnCompleteType>b__4(ObjectValueNode ov)
   at HotChocolate.Types.InputObjectType.ParseLiteral(IValueNode literal)
   at HotChocolate.Types.NonNullType.ParseLiteral(IValueNode literal)
   at HotChocolate.Types.NonNamedType.HotChocolate.Types.IInputType.ParseLiteral(IValueNode literal)
   at HotChocolate.Execution.ResolverContext.CoerceArgumentValue[T](String name, ArgumentValue argumentValue)
   at HotChocolate.Execution.ResolverContext.Argument[T](NameString name)
   at DemoServer10.QueryGraphType.ResolveSearchResults(IResolverContext context) in C:\Users\...\source\repos\DemoServer10\QueryGraphType.cs:line 73
   at HotChocolate.Types.ResolverObjectFieldDescriptorExtensions.<>c__DisplayClass2_0`1.<Resolver>b__0(IResolverContext ctx)
   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext()

```

The scenario is stable. I can reproduce this with version 10.5.5 (latest stable 10.x) and with version 11.2.2 (the latest stable 11.x). Although the error message and stack trace are slightly different for 11.x.
The error message is: _Value cannot be null. (Parameter 'valueSyntax')_
The stack trace is the following:

```
   at HotChocolate.Types.InputObjectType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)
   at HotChocolate.Types.ListType.CreateList(ListValueNode listLiteral, Boolean withDefaults)
   at HotChocolate.Types.ListType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)
   at HotChocolate.Types.NonNamedType.HotChocolate.Types.IParsableType.ParseLiteral(IValueNode literal, Boolean withDefaults)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.Parse(InputObjectType type, ObjectValueNode source, IDictionary`2 target, ITypeConverter converter)
   at HotChocolate.Utilities.Serialization.InputObjectParserHelper.ParseLiteral(InputObjectType type, ObjectValueNode value, InputObjectFactory factory, ITypeConverter converter)
   at HotChocolate.Types.InputObjectType.<>c__DisplayClass31_1.<OnCompleteType>b__4(ObjectValueNode ov)
   at HotChocolate.Types.InputObjectType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)
   at HotChocolate.Types.NonNullType.ParseLiteral(IValueNode literal, Boolean withDefaults)
   at HotChocolate.Types.NonNamedType.HotChocolate.Types.IParsableType.ParseLiteral(IValueNode literal, Boolean withDefaults)
   at HotChocolate.Execution.Processing.MiddlewareContext.CoerceArgumentValue[T](ArgumentValue argument)
   at HotChocolate.Execution.Processing.MiddlewareContext.ArgumentValue[T](NameString name)
   at HotChocolate.Execution.Processing.MiddlewareContext.Argument[T](NameString name)
   at DemoServer11.QueryGraphType.ResolveSearchResults(IResolverContext context) in C:\Users\...\source\repos\DemoServer11\QueryGraphType.cs:line 73
   at HotChocolate.Types.ResolverObjectFieldDescriptorExtensions.<>c__DisplayClass2_0`1.<Resolver>b__0(IResolverContext ctx)
   at HotChocolate.Types.FieldMiddlewareCompiler.<>c__DisplayClass3_0.<<CreateResolverMiddleware>b__0>d.MoveNext()

```

I'm attaching both sample projects to reproduce that.

If there's a way to work around this issue for 10.x, I would appreciate a hint. Thanks in advance!

[DemoServer10.zip](https://github.com/ChilliCream/hotchocolate/files/6385703/DemoServer10.zip)
[DemoServer11.zip](https://github.com/ChilliCream/hotchocolate/files/6385704/DemoServer11.zip)

**Comment by yansklyarenko** [comment]
Thanks for the fix! That was extremely fast! 
@michaelstaib @PascalSenn Is it by any chance possible to merge it to the 10.x branch if you plan to have more 10.x builds?
