### ISSUE TITLE
JsonQueryResultSerializer throws OperationCanceledException

### ISSUE THREAD

**Issue by dannyheard7** [ChilliCream/hotchocolate#3657]
**Describe the bug**
When making requests to a live hotchocolate server, we  get an OperationCanceledException thrown by the JsonQueryResultSerializer if the request has been cancelled.

```
An unhandled exception was thrown by the application.
 System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at async System.Text.Json.Utf8JsonWriter.FlushAsync(?)
   at async HotChocolate.Execution.Serialization.JsonQueryResultSerializer.SerializeAsync(?)
   at async HotChocolate.Execution.Serialization.JsonQueryResultSerializer.SerializeAsync(?)
   at async HotChocolate.AspNetCore.Serialization.DefaultHttpResultSerializer.SerializeAsync(?)
   at async HotChocolate.AspNetCore.MiddlewareBase.WriteResultAsync(?)
   at async HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(?)
   at async HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(?)
   at async HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(?)
   at async Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(?)
   at async RuntimeService.Startup.<>c.<Configure>b__9_1(?) in /src/src/RuntimeService/Startup.cs:line 152
   at async Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(?)
   at async Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(?)
   at async Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(?)
   at async NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(?)
   at async NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(?)
   at async NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(?)
   at async Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[](?)
```

Hotchocolate version 11.1.0

**Expected behavior**
Operation cancelled exceptions should be handled by HC. It might be similar to https://github.com/ChilliCream/hotchocolate/pull/3075?

**Desktop (please complete the following information):**
 - OS: Alpine Linux (Docker)
 - Version 3.13.5

**Comment by mvestergaard** [comment]
How quickly do you get that error? HC has a default request execution timeout of 30 seconds, and if that timeout is exceeded, you would see an error like that.
That it's coming from something Json related isn't necessarily because it has anything to do with Json. That's just the first place the cancellationToken is checked for abort.

**Comment by dannyheard7** [comment]
It takes about that much time, I can replicate it by making some requests to my server that take a small amount of time to fetch the data and stopping the requests (by closing the tab in chrome)

**Comment by mvestergaard** [comment]
Ah, so you're just saying that you would expect it to be handled along the way, and not bubble all the way out? I believe that can be accomplished with middleware. Not sure what the stance is on handling it by default.

**Comment by dannyheard7** [comment]
Ok will look into adding some middleware to handle.

However I don't believe this was an issue HC 10, I've only started seeing these since upgrading to 11
