### ISSUE TITLE
HotChocolate.SchemaException when add remote schema with UploadType

### ISSUE THREAD

**Issue by solov-da** [ChilliCream/hotchocolate#3760]
**Describe the bug**
If UploadType (GraphQL multipart request specification) is an input parameter of some mutation in a remote schema, then adding this remote schema using the HotChocolate.Stitching package will throw a HotChocolate.SchemaException "Unable to resolve dependencies".

**To Reproduce**
Add a remote schema with an input parameter UploadType using the HotChocolate package .

**Expected behavior**
Supporting UploadType (GraphQL multipart request specification) for schema stitching.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2004

**Additional context**
![image](https://user-images.githubusercontent.com/79281869/120199746-41030a80-c22c-11eb-877a-b9047454986e.png)

**Comment by tobias-tengler** [comment]
This is currently not supported. 
I would suggest either calling the stitched service directly or even better, let clients upload the file to your used storage mechanism directly (S3 with presigned URLs, Azure Blob Storage with SAS, etc.).

@michaelstaib I think supporting this scenario would add unnecessary special cases in the stitching code. I haven't looked at it yet, but we would have to build our own Multipart client and once we encounter an upload type create a special request. With the current code the file would also buffer on the gateway before being transferred, which would be really inefficient.

**Comment by matt-psaltis** [comment]
Could we get an initial patch here so the stitching process doesn't blow up? I'd like to still add upload types to our microservices for use outside of stitching scenarios. With the exception thrown, we can't add them at all. I'd prefer a warning is logged in the stitching process and the endpoint ignored. Thoughts?

**Comment by Oceanswave** [comment]
Encountering this as well - in its current form, if someone does the right thing (TM) and implements IFile as part of a mutation that breaks the gateway.

**Comment by svelue** [comment]
Shouldn't at least ignoring the specific field and the UploadType in the gateway be possible? Currently it seems like we need to run a second server on the backend system for a single upload mutation only.

**Comment by viktor-nikolaev** [comment]
@michaelstaib @tobias-tengler same problem occurs with any custom scalar. We used LocalDate from HotChocolate.Types.Scalars and we get this error:

````
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve type reference `None: LocalDate`. (HotChocolate.Types.ObjectType)

   at HotChocolate.Configuration.RegisteredType.GetType[T](ITypeReference typeRef)
   at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
   at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
   at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
   at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|27_0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.MiddlewareAnalysis.AnalysisMiddleware.Invoke(HttpContext httpContext)
   at Ozon.Platform.RateLimiter.PlatformRequestsRateLimiterMiddleware.InvokeAsync(HttpContext context, IRequestMatcher requestMatcher)
   at Ozon.Platform.Overload.OverloadHttpMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Ozon.Platform.Http.S2SAuthorization.AuthorizationMiddleware.CheckAuthorizationHeader(HttpContext context, Boolean failIfUnauthorized)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
````
