### ISSUE TITLE
Inhection of HotChocolate.Path into a mutation causes shema building error

### ISSUE THREAD

**Issue by ademchenko** [ChilliCream/hotchocolate#3860]
**To Reproduce**
Inject HotChocolate.Path into a mutation method like in the below example:

 ```
public async Task<TestResult> TestMutation1(Path path, FieldNode syntaxNode)
        {
            return new TestResult { Result = "OK1" };
        }

```

**Current behavior**
Error on schema building stage happens:
`HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to infer or resolve a schema type from the type reference `Input: Path`.

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
   at HotChocolate.SchemaBuilder.Create()
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create()
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, IServiceProvider serviceProvider, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpGetMiddleware.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.ToolOptionsFileMiddleware.Invoke(HttpContext context)
   at HotChocolate.AspNetCore.HttpGetSchemaMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpMultipartMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`

**Desktop (please complete the following information):**
 - Version 11.2.2

**Additional context**
FieldNode after removing path is injected successfully.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/11.3.1-preview.4
