### ISSUE TITLE
"System.InvalidOperationException: The LinkedList node does not belong to current LinkedList"

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#3945]
**Describe the bug**
In 11.3, on rare occasions I will get an error like the below:

```
      Unexpected Execution Error
      System.InvalidOperationException: The LinkedList node does not belong to current LinkedList.
         at System.Collections.Generic.LinkedList`1.ValidateNode(LinkedListNode`1 node)
         at HotChocolate.Utilities.Cache`1.TouchEntry(LinkedListNode`1 rank)
         at HotChocolate.Utilities.Cache`1.GetOrCreate(String key, Func`1 create)
         at HotChocolate.Execution.Caching.DefaultPreparedOperationCache.TryAddOperation(String operationId, IPreparedOperation operation)
         at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.TimeoutMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)
```

Re-running the query will work fine, and it will be a good while before I see the error again. 

**To Reproduce**
I have not found a reliable way to reproduce it.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.2.3

**Additional context**
HotChocolate version 11.3.0

**Comment by michaelstaib** [comment]
This one is now fixed

**Comment by michaelstaib** [comment]
We will issue a hotfix 11.3.2

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/11.3.2
https://github.com/ChilliCream/hotchocolate/releases/tag/12.0.0-preview.26
