### ISSUE TITLE
Workbacklog throws null reference exception 12.0.0-preview.26

### ISSUE THREAD

**Issue by sjefvanleeuwen** [ChilliCream/hotchocolate#3989]
After upgrading to: 12.0.0-preview.26  (from 12.0.0-preview.25) during project startup before any injection occurs (on .net 6.0.100-preview.5.21302.13) :

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=HotChocolate.Execution
  StackTrace:
   at HotChocolate.Execution.Processing.WorkBacklog.TryStopProcessing() in /home/vsts/work/1/s/src/HotChocolate/Core/src/Execution/Processing/WorkBacklog.cs:line 318
   at HotChocolate.Execution.Processing.WorkBacklog.<ProcessTasksAsync>d__38.MoveNext() in /home/vsts/work/1/s/src/HotChocolate/Core/src/Execution/Processing/WorkBacklog.Processing.cs:line 82
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    HotChocolate.Execution.Processing.WorkBacklog.TryStopProcessing() in WorkBacklog.cs
    HotChocolate.Execution.Processing.WorkBacklog.ProcessTasksAsync() in WorkBacklog.Processing.cs
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

My dependencies:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RuntimeIdentifier Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">alpine-x64</RuntimeIdentifier>
    <UserSecretsId>7a7f989a-3c9f-404b-9903-7b8bf3e5cf49</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>../../doc/generated/CCMixter.ORM.Service.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotChocolate" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.AspNetCore.Voyager" Version="10.5.5" />
    <PackageReference Include="HotChocolate.Data" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Data.EntityFramework" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Stitching" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Subscriptions" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Types" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Types.CursorPagination" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Types.Filters" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Types.OffsetPagination" Version="12.0.0-preview.26" />
    <PackageReference Include="HotChocolate.Types.Selections" Version="10.5.5" />
    <PackageReference Include="HotChocolate.Types.Sorting" Version="12.0.0-preview.26" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0-preview.6.21355.2" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0-preview.6.21352.12" />
    <PackageReference Include="MimeMapping" Version="1.0.1.37" />
    <PackageReference Include="Minio" Version="3.1.13" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="6.0.0-preview.5" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="6.0.0-preview.4.21253.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.6.21352.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.0-preview.6.21352.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.14" />
    
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.12.0" />
    <PackageReference Include="z440.atl.core" Version="3.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CCMixter.ORM.FakeData\CCMixter.ORM.FakeData.csproj" />
    <ProjectReference Include="..\ccmixter.orm\CCMixter.ORM.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Rest\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Extensions.graphql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
```

**Comment by michaelstaib** [comment]
This is fixed with preview 27.
