### ISSUE TITLE
SS 12.0.0-preview.27 gives "There is no parser registered the specified type" exception when uuid appears in schema

### ISSUE THREAD

**Issue by stephenaggett** [ChilliCream/hotchocolate#4010]
The client code works fine with SS 11.3.2, but after upgrading StrawberryShake.Transport.Http and  StrawberryShake.CodeGeneration.CSharp.Analyzers from 11.3.2 to 12.0.0-preview.27 (changing nothing else) then executing a query that returns a uuid field I receive the following exception:

```
Unhandled exception. System.ArgumentException: There is no parser registered the specified type.
   at StrawberryShake.Serialization.SerializerResolver.GetLeafValueParser[TSerialized,TRuntime](String typeName)
   at Mass.MassApi.Api.ExampleClient.State.GetFilesBuilder..ctor(IEntityStore entityStore, IEntityIdSerializer idSerializer, IOperationResultDataFactory`1 resultDataFactory, ISerializerResolver serializerResolver) in C:\Code\MASS\API\MassApi\Test\Mass.MassApi.Ap
i.ExampleClient\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\MassApiClient.StrawberryShake.cs:line 663
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.MassApiClientServiceCollectionExtensions.<>c__DisplayClass1_2.<ConfigureClientDefault>b__9() in C:\Code\MASS\API\MassApi\Test\Mass.MassApi.Api.ExampleClient\StrawberryShake.CodeGeneration.CSharp.Analyzers\Strawberry
Shake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\MassApiClient.StrawberryShake.cs:line 951
   at StrawberryShake.OperationExecutor`2.ExecuteAsync(OperationRequest request, CancellationToken cancellationToken)
```

**Comment by getcashier** [comment]
Same issue occurring with 12.0.1.  Any work arounds (aside from downgrading)?

**Comment by tretyakov-d** [comment]
Same on 12.0.1

**Comment by PascalSenn** [comment]
@tretyakov-d  you have to add the parser to SS if there is no parsed for the type. There was a breaking change in v12 of the type name UUID. We aligned the scalar name with all the other graphql servers. (Uuid => UUID)
This probably fixes your problem:
```csharp
service.AddSingleton<ISerializer>(new UUIDSerializer("Uuid));
```
