### ISSUE TITLE
Improve logging when an invalid variable is provided

### ISSUE THREAD

**Issue by hognevevle** [ChilliCream/hotchocolate#4047]
**Is your feature request related to a problem? Please describe.**
```
HC0016: Variable `eventTypes` got an invalid value.
      HotChocolate.Types.SerializationException: AppEventType cannot parse the given literal of type `StringValueNode`.
         at HotChocolate.Types.EnumType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)
         at HotChocolate.Types.NonNullType.ParseLiteral(IValueNode literal, Boolean withDefaults)
         at HotChocolate.Types.NonNamedType.HotChocolate.Types.IParsableType.ParseLiteral(IValueNode literal, Boolean withDefaults)
         at HotChocolate.Types.ListType.CreateList(ListValueNode listLiteral, Boolean withDefaults)
         at HotChocolate.Types.ListType.ParseLiteral(IValueNode valueSyntax, Boolean withDefaults)
         at HotChocolate.Types.NonNamedType.HotChocolate.Types.IParsableType.ParseLiteral(IValueNode literal, Boolean withDefaults)
         at HotChocolate.Execution.Processing.VariableCoercionHelper.CoerceVariableValue(VariableDefinitionNode variableDefinition, IInputType variableType, Object value)
```

**Describe the solution you'd like**
It would help greatly if the error could tell me exactly which value has failed.

**Comment by tobias-tengler** [comment]
@michaelstaib is working on improving the error handling of variables this very minute: #4037 
Look forward to it in v12 🚀

**Comment by michaelstaib** [comment]
We will need at least two more days to get that merged. The errors now exactly specify what is wrong and where:

```json
{
  "errors": [
    {
      "message": "The required input field \u0060name\u0060 is missing.",
      "path": [
        "user",
        "name"
      ],
      "extensions": {
        "field": "UserInput.name"
      }
    }
  ]
}
```

```json
{
  "errors": [
    {
      "message": "The required input field \u0060name\u0060 is missing.",
      "path": [
        "user",
        "name"
      ],
      "extensions": {
        "field": "UserInput.name"
      }
    }
  ]
}
```
