### ISSUE TITLE
Try to have object of an object in Input But I get : "The name `linkedWorkEnvironmentInput` was already registered by another type."

### ISSUE THREAD

**Issue by bruno1407** [ChilliCream/hotchocolate#4213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi everybody,

I'm trying to create a GraphQL server that can understand this kind of queries:

```
mutation {
sendLinkRequest(input: {
linkedWorkEnvironment: {
name: "Beeple",
url: "https://example-planning.acme.com",
externalLinkUuid: "de86b988-153d-4261-b2d0-358ad123ab02",
linkToken: "Secret Token" }) {
errors {
scope
message
}}} 
```

For now, here is what is coded 
the configuration 

```
 services.AddGraphQL(p => SchemaBuilder.New().AddServices(p)
                    .AddType<linkedLoginsType>()
                    .AddType<sendLinkRequestType>()    
                    .AddQueryType<Query>()
                    .AddMutationType<Mutation>()
                    .Create()
            );

```

The classes of the input : 

```
   public class linkedWorkEnvironmentInput
    {
        public linkedWorkEnvironment linkedWorkEnvironment { get; set; }
    }

    public class linkedWorkEnvironment
    {
        public string name { get; set; }
        public string url { get; set; }
        public string externalLinkUuid { get; set; }
        public string linkToken { get; set; }
    }
```

The mutation class : 

```
public class Mutation
    {    
        IsendLinkRequestService _sendLinkRequestService = null;
        public Mutation( IsendLinkRequestService sendLinkRequestService)
        {
            _sendLinkRequestService = sendLinkRequestService;
        }
        [UseFiltering]
        public sendLinkRequest sendLinkRequest(linkedWorkEnvironmentInput input)
        {
            return _sendLinkRequestService.sendLinkRequest(input);
        }
    }
```
the sendLinkRequest, that just return a test : 

 ```
public sendLinkRequest sendLinkRequest(linkedWorkEnvironmentInput input)
        {
            sendLinkRequest response = new sendLinkRequest();
            response.errors = new errors() { message = "test", scope = "test" };
            return response;
        }
```

inputType : 

```
public class linkedWorkEnvironmentInputType : InputObjectGraphType
    {
        public linkedWorkEnvironmentInputType()
        {
            Field(typeof(linkedWorkEnvironmentType), "linkedWorkEnvironment");
  
        }
    }
    public class linkedWorkEnvironmentType : InputObjectGraphType
    {

        public linkedWorkEnvironmentType()
        {
            Field(typeof(StringGraphType), "externalLinkUuid");
            Field(typeof(StringGraphType), "linkToken");
            Field(typeof(StringGraphType), "name");
            Field(typeof(StringGraphType), "url");

        }
    }

```

and reponse type : 

```
public class sendLinkRequestType : ObjectType<sendLinkRequest>
    {
        protected override void Configure(IObjectTypeDescriptor<sendLinkRequest> descriptor)
        {
            descriptor.Field(x => x.errors)
                .Type<ResponseType>();           
        }   

      
    }
    public class ResponseType : ObjectType<errors>
    {
        protected override void Configure(IObjectTypeDescriptor<errors> descriptor)
        {                 
            descriptor.Field(x => x.scope)
                .Type<StringType>();
            descriptor.Field(x => x.message)
               .Type<StringType>();
        }
    }

```

As you can see I have tried lots of different things, check lot of differents tutoriels but at the moment i'm blocking on something I didn't understand with GraphQL maybe..
Everytime i'm starting the application i got this error in the configuration "The name linkedWorkEnvironmentInput was already registered by another type"

But if i modify the input with this 

```
  public class linkedWorkEnvironmentInput
    {
         public string name { get; set; }
        public string url { get; set; }
        public string externalLinkUuid { get; set; }
        public string linkToken { get; set; }
    }
```
and the query by this, it is working : 

```
mutation{sendLinkRequest(input:
  {name:"e",externalLinkUuid:"e",linkToken:"f",url:"t"})}
{errors{scope
message
}}
```

If somone have some time for me it will be a pleasur :)

### Steps to reproduce

1. I'm just lunching the application and i go to playground

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The name `linkedWorkEnvironmentInput` was already registered by another type. (HotChocolate.Types.InputObjectType<Beeple_API.GraphQL_Models.linkedWorkEnvironment>)

   at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<>c__DisplayClass23_0.<CompleteNames>g__CompleteName|0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteNames(Func`1 schemaResolver)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, DescriptorContext context, IBindingLookup bindingLookup, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder)
   at HotChocolate.SchemaBuilder.Create()
```

### Product

Hot Chocolate

### Version

11.3.7

**Comment by michaelstaib** [comment]
The issue here is that Hot Chocolate by default applies input to input types.... 

Meaning, your type `linkedWorkEnvironment` will become `linkedWorkEnvironmentInput` and collide with your already existing type  `linkedWorkEnvironmentInput`.

In GraphQL its best practice to postfix all input object types with `Input`. However, you can override the convention by inheriting from `DefaultNamingConventions` and overriding `NameString GetTypeName(Type type, TypeKind kind). In the case of `TypeKind.Input` return `type.Name` in all other cases return `base.GetTypeName(type, kind)`.

Register your custom naming convention class like:

```csharp
services
    .AddGraphQLServer()
    .AddConvention<INamingConventions>(new MyCustomConvention())
    ...
```
