### ISSUE TITLE
StrawberryShake Any input type missing formatter

### ISSUE THREAD

**Issue by jsnoyes** [ChilliCream/hotchocolate#4244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using StrawberryShake.Tools, the generated client doesn't contain an InputValueFormatter for type "Any" even though it expects it for variables passed in. This causes an exception to be thrown while trying to resolve the dependency for the formatter in the generated code's constructor.

All other formatters appear to exist in the serializerResolver except for "Any".

### Steps to reproduce

1. Follow the steps to produce the demo project here: https://chillicream.com/docs/strawberryshake/get-started/console 
2. Instead of using the example GraphQL query for "sessions", use the following query(Note the parameter type of [Any!]!):
query GetSessions($input: [Any!]!) {
  sessionsById(ids: $input) {
    id
  }
}
3. Change the Query type for sessionsById to be:
  sessionsById(ids: [Any!]!): [Track!]!
4. Generate the client.
5. Run the program using code like this:
        static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();

            serviceCollection
                .AddConferenceClient()
                .ConfigureHttpClient(client => client.BaseAddress = new Uri("https://workshop.chillicream.com/graphql"));

            IServiceProvider services = serviceCollection.BuildServiceProvider();

            IConferenceClient client = services.GetRequiredService<IConferenceClient>();

            var fds = client.GetSessions.ExecuteAsync(new List<string> { "test" }).Result;

        }

6. The code throws an exception in the generated client because it tries to find a registered formatter that doesn't exist on this line:
_anyFormatter = serializerResolver.GetInputValueFormatter("Any");
 'There is no formatter registered the specified type.'

### Relevant log output

```shell
System.ArgumentException
  HResult=0x80070057
  Message=There is no formatter registered the specified type.
  Source=StrawberryShake.Core
  StackTrace:
   at StrawberryShake.Serialization.SerializerResolver.GetInputValueFormatter(String typeName)
   at Demo.GraphQL.GetSessionsQuery..ctor(IOperationExecutor`1 operationExecutor, ISerializerResolver serializerResolver) in C:\Repos\testtest\Demo\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\ConferenceClient.StrawberryShake.cs:line 206
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ConferenceClientServiceCollectionExtensions.<>c.<ConfigureClientDefault>b__1_6(IServiceProvider sp) in C:\Repos\testtest\Demo\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\ConferenceClient.StrawberryShake.cs:line 643
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ConferenceClientServiceCollectionExtensions.<>c.<ConfigureClientDefault>b__1_7(IServiceProvider sp) in C:\Repos\testtest\Demo\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\ConferenceClient.StrawberryShake.cs:line 646
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ConferenceClientServiceCollectionExtensions.ClientServiceProvider.GetService(Type serviceType) in C:\Repos\testtest\Demo\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\ConferenceClient.StrawberryShake.cs:line 660
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ConferenceClientServiceCollectionExtensions.<>c.<AddConferenceClient>b__0_4(IServiceProvider sp) in C:\Repos\testtest\Demo\StrawberryShake.CodeGeneration.CSharp.Analyzers\StrawberryShake.CodeGeneration.CSharp.Analyzers.CSharpClientGenerator\ConferenceClient.StrawberryShake.cs:line 607
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Demo.Program.Main(String[] args) in C:\Repos\testtest\Demo\Program.cs:line 20
```

### Product

Strawberry Shake

### Version

11.3.7

**Comment by michaelstaib** [comment]
Did you follow the documentation on how to enable `Any`?
https://chillicream.com/docs/strawberryshake/scalars/#any-or-json

**Comment by jsnoyes** [comment]
Maybe I'm not understanding it correctly, but aren't the docs saying that if you just want the standard serialization you don't need to do anything extra? JsonDocuments would be fine for my case. 

Or do I have to create a custom serializer? I can create a custom serializer if needed, but based on the docs I don't think I should need to. The generated client is trying to access a _anySerializer, but one doesn't exist in the generated code.

"By default Strawberry Shake will use the built-in JsonSerializer to represent these fields as JsonDocument. If you want a different representation or use a different JSON library you can do so by providing a custom serializer that handles JSON scalars."

**Comment by jsnoyes** [comment]
I have a follow up question, @michaelstaib. I have cases where I use an Any type for both an input type and an output type. If I try to create a ScalarSerializer implementation where the TRuntime type is Object, the abstract method that must be implemented for Format(TRuntime runtimeValue) clashes with Format(object? runtimeValue). (two methods on ScalarSerializer shown below). How should we be enabling Any if "object" can't be used as a runtime type? I would imagine that Any maps to "object" more often than not.

![image](https://user-images.githubusercontent.com/30099749/134581286-db5ddc39-b97b-4563-bb43-4fb1b9a052a0.png)

![image](https://user-images.githubusercontent.com/30099749/134582157-59bccc0c-a6f3-45ac-8427-26e27adff0cc.png)

**Comment by gerwim** [comment]
I have the same issue. I'm trying to write to a `jsonb` field in Hasura. Implementing a custom scalar serializer (as seen here: https://chillicream.com/docs/strawberryshake/scalars#any-or-json) does not work. Using the code specified in the docs:

```
public class MyJsonSerializer : ScalarSerializer<JsonElement, object>
{
    public JsonSerializer(string typeName = BuiltInScalarNames.Any)
        : base(typeName)
    {
    }
    public override object Parse(JsonElement serializedValue)
    {
        // hand the serialization of the JsonElement
    }
    protected override JsonElement Format(object runtimeValue)
    {
        // handle the serialization of the runtime representation in case
        // the scalar is used as a variable.
    }
}
```

gives compiler error CS0462: `The inherited members 'ScalarSerializer<TSerialized, TRuntime>.Format(object?)' and 'ScalarSerializer<TSerialized, TRuntime>.Format(TRuntime)' have the same signature in type 'JsonbSerializer', so they cannot be overridden`.
