### ISSUE TITLE
Stitching: The name `ApplyPolicy` was already registered by another type

### ISSUE THREAD

**Issue by mickdelaney** [ChilliCream/hotchocolate#4261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Gateway Service, using Stitching which sits in front of 3 downstream services.
I have Authorization Policies on these downstream services. 
e.g descriptor.Authorize(Policies.CanAccessProducts);

I have also added a type GlobalSettings to the Gateway itself, it then stitches that Type. 
If I add an Authorize call to the ObjectType Descriptor for GlobalSettings 
e.g descriptor.Authorize(Policies.CanReadGlobalSettings);

I then get an error **The name `ApplyPolicy` was already registered by another type.** 

https://hotchocolategraphql.slack.com/archives/CN3EZ03U1/p1628178524026600

### Steps to reproduce

1. Create a gateway/stitching service
2. Add a type at the gateway and authorize it
3. Create a downstream service with a type and authorize it
4. stitch the downstream service into the gateway
5. Query for the gateway type

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The name `ApplyPolicy` was already registered by another type. (HotChocolate.Types.EnumType<HotChocolate.AspNetCore.Authorization.ApplyPolicy>)

   at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<>c__DisplayClass20_0.<CompleteNames>g__CompleteName|0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteNames(Func`1 schemaResolver)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Product

Hot Chocolate

### Version

12.0.0-rc.11

**Comment by michaelstaib** [comment]
you just need to remove the auth declarations from the downstream services when merging the schema. This can be done with a directive merge rule.... essentially skip all incoming auth directive types. The merged schema will then use the auth directive from the gateway itself.

**Comment by martinmesserli** [comment]
I have exactly the same problem. Is there any example on how to achieve that with a directive merge rule? Thx.

**Comment by PascalSenn** [comment]
Answered in : https://github.com/ChilliCream/hotchocolate/discussions/4606


The solution:

Define a `IDirectiveMergeHanlder`:
```csharp
 public class IgnoreAuthroizeDirectiveHanlder
        : IDirectiveMergeHandler
    {
        private readonly MergeDirectiveRuleDelegate _next;

        public IgnoreAuthroizeHanlder(MergeDirectiveRuleDelegate next)
        {
            _next = next;
        }

        public void Merge(
            ISchemaMergeContext context,
            IReadOnlyList<IDirectiveTypeInfo> directives)
        {
            IDirectiveTypeInfo? directive = directives.First();

            if (
                !directive.Definition.Name.Value.Equals(
                    "authorize",
                    StringComparison.InvariantCultureIgnoreCase))
            {
                _next(context, directives);
            }
        }
    }
```

Add it to the schema:
```csharp
# Startup
services
  .AddGraphQLServer()
  .AddDirectiveMergeHandler<IgnoreAuthorizeDirectiveHandler>();
```

**Comment by SAssassin** [comment]
.IgnoreType("ApplyPolicy", "your schema")
