### ISSUE TITLE
Alternative for dotnet build command.

### ISSUE THREAD

**Issue by sathaker** [ChilliCream/hotchocolate#4274]
### Is your feature request related to a problem?

It's not possible for me to use `dotnet build` on my project. How can I generate files(Strawberryshake Clients)

### The solution you'd like

I wanted to understand how the files are generated via `dotnet build` . Also, is there a way to generate the files(GraphQL Clients) without using `dotnet build` . What are the commands that are run as a part of `dotnet build` which generates the code?

Any help would be appreciated.

### Product

Strawberry Shake

**Comment by michaelstaib** [comment]
Starting with version 12.4.0-preview.6 ww support tool based generation without the need for source generators... you can switch between those two generators.

```bash
dotnet graphql generate [--path] [--defaultNamespace] [--persistedQueryDirectory]  
```

**Comment by ahmad2smile** [comment]
I have preview tools but still `generate` command isn't avaible:

![image](https://user-images.githubusercontent.com/6108922/143765997-0cdd9565-bd9b-4b8b-82d3-d967f9201394.png)


Error:

```bash
> dotnet graphql generate

Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized command or argument 'generate'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrParameter(CommandOrParameterArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)
```

**Comment by ahmad2smile** [comment]
Just checked `preview.6`, `generate` option was there but it was removed later on.
