### ISSUE TITLE
Output Geometry type

### ISSUE THREAD

**Issue by DigSan** [ChilliCream/hotchocolate#4326]
### Describe the bug

Hello, I am trying to output **Geometry** type but this error apears:

```
HotChocolate.SchemaException: 'For more details look at the Errors property.
1. Unable to infer or resolve a schema type from the type reference Input: Geometry. (HotChocolate.Types.ObjectType<NetTopologySuite.Geometries.Geometry>)
2. Unable to infer or resolve a schema type from the type reference Input: XPathNavigator. 
```

Hotchocolate suppurts outputting Geometry type?

### Steps to reproduce

services.AddGraphQLServer()
      .AddQueryType<GraphQlQuery>()
      .AddProjections()
      .AddSpatialProjections()
      .AddSpatialTypes();

Add property with Geometry type to class

        public class Test
        {
            public string SomeThing { get; set; }

            public Geometry Geometry { get; set; }
        }

ErrorProject [example](https://github.com/DigSan/HotChocolateGeometryError/blob/master/HotChocolateGeometryError/Startup.cs)

I have attached example project. All logic in startup.
[HotChocolateGeometryError.zip](https://github.com/ChilliCream/hotchocolate/files/7378552/HotChocolateGeometryError.zip)

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMCJICHE6FT7", Request id "0HMCJICHE6FT7:00000004": An unhandled exception was thrown by the application.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to infer or resolve a schema type from the type reference `Input: Geometry`. (HotChocolate.Types.ObjectType<NetTopologySuite.Geometries.Geometry>)
      2. Unable to infer or resolve a schema type from the type reference `Input: XPathNavigator`. (HotChocolate.Types.ObjectType<System.Xml.XPath.XPathNavigator>)
      3. Unable to infer or resolve a schema type from the type reference `Input: XmlNode`. (HotChocolate.Types.ObjectType<System.Xml.XmlAttribute>)
      4. Unable to infer or resolve a schema type from the type reference `Input: Char`.
      5. Unable to infer or resolve a schema type from the type reference `Input: XmlReader`.
      6. Unable to infer or resolve a schema type from the type reference `Output: Char`.
      7. Unable to infer or resolve a schema type from the type reference `Input: XmlSchemaDatatype`.
      8. Unable to infer or resolve a schema type from the type reference `Input: XmlSchemaObject`. (HotChocolate.Types.InputObjectType<System.Xml.Schema.XmlSchema>)
      9. Unable to infer or resolve a schema type from the type reference `Input: XmlNameTable`.
      10. Unable to infer or resolve a schema type from the type reference `Input: XPathExpression`.
      11. Unable to infer or resolve a schema type from the type reference `Input: IXmlSchemaInfo`.
      12. Unable to infer or resolve a schema type from the type reference `Input: XmlNodeList`.
      13. Unable to infer or resolve a schema type from the type reference `Input: Byte*`.
      14. Unable to infer or resolve a schema type from the type reference `Input: ICollection`.
      15. Unable to infer or resolve a schema type from the type reference `Output: DictionaryEntry`.

         at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
         at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Product

Hot Chocolate

### Version

12.0.1

**Comment by alienwareone** [comment]
Hope this get fixed soon. I couldn't find a way to work around this issue even if I exclude the Geometry properties.
```
public class PlaceType : ObjectType<Place>
{
    protected override void Configure(IObjectTypeDescriptor<Place> descriptor)
    {
        descriptor.BindFieldsImplicitly();
        descriptor.Ignore(x => x.Location); // typeof Geometry
    }
}
```

**Comment by alienwareone** [comment]
The problem in my case was inheritance.
```
[NotMapped]
public class PlaceEx : Place
{
  // ...
}
```
Just removed the base class and copied all props to the extended type. Solves the problem.
