### ISSUE TITLE
InvalidFormatException when a field is overflowed

### ISSUE THREAD

**Issue by ignj** [ChilliCream/hotchocolate#4378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I perform a query or mutation, and I send a value that can be overflowed, the server crashes and returns a `500 Internal Server Error` due an InvalidFormatException

I expect to receive a `400 Bad Request` with a description of the error, helping the UI to realize what went wrong to notify the user.

### Steps to reproduce

You will need a query that receives a field that can be overflowed (such as a `long` value) or a mutation with a payload that contains a field that can be overflowed

1. Perform the query / mutation with a value that makes the assignation to overflow during the query execution

Expected Result: A `400 Bad Request` pointing that the query cannot be executed, giving information about the error (which given value was invalid). For example if I try to assign a `string` to a `long` I get:
```json
{
    "errors": [
        {
            "message": "The specified value type of field `test` does not match the field type.",
            "locations": [
                {
                    "line": 5,
                    "column": 11
                }
            ],
            "extensions": {
                "fieldName": "test",
                "fieldType": "Long!",
                "locationType": "Long!",
                "specifiedBy": "http://spec.graphql.org/June2018/#sec-Values-of-Correct-Type"
            }
        }
    ]
}
```
Actual Result: A 500 error 
```json
{
    "errors": [
        {
            "message": "Unexpected Execution Error",
            "extensions": {
                "message": "Exception of type 'HotChocolate.Language.InvalidFormatException' was thrown.",
                "stackTrace": "// ... Removed for brevity"
            }
        }
    ]
}
```

### Relevant log output

```shell
// I overflow a Long! in this example, the server crashes with the exception

HotChocolate.Language.InvalidFormatException: Exception of type 'HotChocolate.Language.InvalidFormatException' was thrown.
   at HotChocolate.Language.IntValueNode.ToInt64()
   at HotChocolate.Types.LongType.ParseLiteral(IntValueNode valueSyntax)
   at HotChocolate.Types.IntegerTypeBase`1.IsInstanceOfType(IntValueNode valueSyntax)
   at HotChocolate.Types.ScalarType`2.IsInstanceOfType(IValueNode valueSyntax)
   at HotChocolate.Validation.Rules.ValueVisitor.IsInstanceOfType(IDocumentValidatorContext context, IInputType inputType, IValueNode value)
   at HotChocolate.Validation.Rules.ValueVisitor.Enter(IValueNode valueNode, IDocumentValidatorContext context)
   at HotChocolate.Language.Visitors.SyntaxWalker`1.Enter(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ArgumentNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(FieldNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(SelectionSetNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(OperationDefinitionNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Validation.DocumentValidatorVisitor.VisitChildren(DocumentNode node, IDocumentValidatorContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.VisitChildren(ISyntaxNode node, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit[T,P](T node, P parent, TContext context)
   at HotChocolate.Language.Visitors.SyntaxVisitor`1.Visit(ISyntaxNode node, TContext context)
   at HotChocolate.Validation.DocumentValidatorRule`1.Validate(IDocumentValidatorContext context, DocumentNode document)
   at HotChocolate.Validation.DocumentValidator.Validate(ISchema schema, DocumentNode document, IEnumerable`1 contextData)
   at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)
   at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)
   at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)
   at HotChocolate.Execution.Pipeline.TimeoutMiddleware.InvokeAsync(IRequestContext context)
   at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)
```

### Additional Context?

In this particular use case, I want to create a form in which I make a mutation and send multiple fields to the server to be processed.
I can make many DTO validations when it comes to the business logic, but I can't handle in any way that the query crashes due an overflow for a property (in this case a Long! type) when it is trying to be assigned

As a backend developer, I would like to serve a message that the client can handle to display the appropriate error:
When the mutation of the form fails because an overflow, I can only tell to the client "hey, something went wrong", without being able to point the specific field of the form that caused the issue (in my scenario, an overflowed Long!)

### Product

Hot Chocolate

### Version

12.0.1

**Comment by seantleonard** [comment]
Is there any way that we can add our own code, i.e. error filter that would change this behavior? I would prefer not to have bad requests result in HTTP 500 errors.

**Comment by michaelstaib** [comment]
Let me check...

**Comment by michaelstaib** [comment]
OK ... its fixed ... will do a patch release for 12.

**Comment by michaelstaib** [comment]
I have patched the issue in the IntTypeBase. But I also made the Validation rule more robust for the case that there is an issue with other scalar implementations.

We will revisit the scalar in version 14 for next year and will make sure that the IsInstanceOf check does not lead to such errors in future. In general this method should never throw.

**Comment by michaelstaib** [comment]
Fixed in:
12.15.1
13.0.0-preview.74

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/releases/tag/13.0.0-preview.74
