### ISSUE TITLE
Issues filtering when entities use Nodatime

### ISSUE THREAD

**Issue by Aeseir** [ChilliCream/hotchocolate#4417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to load BananacakePop to  view graphql schema from server throws a error that it doesn't recognize types associated with entity.
These types are Nodatime types, which have been added into the schema as per instructions [Hotchocolate NodaTime plugin](https://chillicream.com/docs/hotchocolate/defining-a-schema/scalars/#nodatime).

Expected:
Schema loads and is consumable

### Steps to reproduce

1. Followed the instructions to implement NodaTime support as per [Hotchocolate NodaTime plugin](https://chillicream.com/docs/hotchocolate/defining-a-schema/scalars/#nodatime).

The end result as follows:

```
services.AddGraphQLServer()
                .AddAuthorization()
                .AddType(new UuidType('D'))
                .AddQueryType<Queries>()
                .AddFiltering()
                .AddSorting()
                .AddProjections()
                .AddType<Car>()
                .AddType<InstantType>()
                .AddInMemorySubscriptions();
```

The Queries type looks as follows:

        [UseDbContext(typeof(AppDbContext))]
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Car> GetCars([ScopedService] AppDbContext context) => context.Car;

Car entity looks as follows:
```
public class Car: BaseEntity
    {
        public string Name { get; set; }
        public string Model{ get; set; }
    }
```
BaseEntity looks as follows:

```
public abstract class BaseEntity : IBaseEntity
    {
        public Guid Id { get; set; }
        public Instant CreatedDate { get; set; } = SystemClock.Instance.GetCurrentInstant();
        public string CreatedBy { get; set; }
        public Instant? ModifiedDate { get; set; } = null;
        public string ModifiedBy { get; set; } = null;
        public bool IsDeleted { get; set; } = false;
    }

    [UnionType("GroupMember")]
    public interface IBaseEntity { }
```

Startup looks as follows
```
app.UseEndpoints(endpoints =>
            {
               // omitted for brevity
                    endpoints.MapGraphQL("/api/graphql");
                // omitted for brevity
            });
```

2. Launch server and go to "/api/graphql"endpoint
3.  Reload schema via BanacakePop
4.  Fun Error

### Relevant log output

```shell
Error message attempting to get schema from server:


HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. The type of the member CreatedDate of the declaring type BaseEntity is unknown
 (HotChocolate.Data.Filters.FilterInputType<Infrastructure.Entities.Cars>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12

**Comment by mlibk** [comment]
I was converting my codebase to use NodaTime and just ran into this issue too (using HC 12.3.2).

**Comment by Arbyy** [comment]
I ran into this issue as well, I managed to resolve it using the solution described in [this issue comment](https://github.com/ChilliCream/hotchocolate/issues/3433#issuecomment-813786044)
