### ISSUE TITLE
Compilation fails on .net 6.0 + HotChocolate 12

### ISSUE THREAD

**Issue by dylantf** [ChilliCream/hotchocolate#4426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After creating a project using .net 6.0 and adding minimal setup code, the `MapGraphQL()` method triggers an error:
> Unable to resolve service for type 'HotChocolate.AspNetCore.Serialization.IHttpResultSerializer' while attempting to activate 'HotChocolate.AspNetCore.HttpGetMiddleware'.

### Steps to reproduce

Create a new project `dotnet new web -n Foo`

Follow the instructions on the website for Hot Chocolate v12:
- Add HotChocolate.AspNetCore
- Add service:
  `builder.Services.AddGraphQL().AddQueryType<Query>();`
- Add GraphQL server:
  `app.MapGraphQL();`
- Add a simple Query class:
  ```cs
  public class Query
  {
      public string Hello() => "Hello world";
  }
  ```

Example repo:
https://github.com/dylantf/DotNet6-HotChocolate-Minimal

### Relevant log output

```shell
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.Http.Abstractions.dll: 'Unable to resolve service for type 'HotChocolate.AspNetCore.Serialization.IHttpResultSerializer' while attempting to activate 'HotChocolate.AspNetCore.HttpGetMiddleware'.'
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGraphQL(IEndpointRouteBuilder endpointRouteBuilder, PathString path, NameString schemaName)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGraphQL(IEndpointRouteBuilder endpointRouteBuilder, String path, NameString schemaName)
   at Program.<Main>$(String[] args) in Path\To\My\Project\DotNet6-HotChocolate-Minimal\Program.cs:line 11
```

### Additional Context?

This example is using the new "minimal" syntax, but it still seems to fail after switching to standard/old/.netcore 5 style with a startup class. Disabling the new implicit usings feature also does not seem to have any effect.

### Product

Hot Chocolate

### Version

12.2.1

**Comment by dylantf** [comment]
Sorry I am an idiot, it's AddGraphQLServer not AddGraphQL. I blame autocomplete ;)
