### ISSUE TITLE
 Stitching The name `authorize` was already registered by another type. (HotChocolate.Types.DirectiveType)

### ISSUE THREAD

**Issue by ZephiroRB** [ChilliCream/hotchocolate#4468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Gateway.GraphQL/program.cs
`
var builder = WebApplication.CreateBuilder(args);

var Auth = "auth";
builder.Services.Configure<TokenSettings>(builder.Configuration.GetSection("TokenSettings"));

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidIssuer = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Issuer"),
        ValidateIssuer = true,
        ValidAudience = builder.Configuration.GetSection("TokenSettings").GetValue<string>("Audience"),
        ValidateAudience = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration.GetSection("TokenSettings").GetValue<string>("Key"))),
        ValidateIssuerSigningKey = true
    };
});

builder.Services.AddHttpClient(Auth, c => c.BaseAddress = new Uri("https://localhost:7132/graphql"));

builder.Services.AddAuthorization();
builder.Services.AddGraphQLServer()
    .AddRemoteSchema(Auth)
    .AddAuthorization();

var app = builder.Build();

app.MapGraphQL();
app.UseAuthentication();
app.UseAuthorization();

app.Run();`

### Steps to reproduce

1.  I use .NET 6 in Windows
2. Create Project Gateway.GraphQL and write code for authorize with JWT
3. Create Project Auth.GraphQL  and write code for authorize with JWT
4. Run Auth.Graphql Works and Gateway.GraphQL Fail Error

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The name `authorize` was already registered by another type. (HotChocolate.Types.DirectiveType)

   at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.<>c__DisplayClass20_0.<CompleteNames>g__CompleteName|0(RegisteredType registeredType)
   at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
   at HotChocolate.Configuration.TypeInitializer.CompleteNames(Func`1 schemaResolver)
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver, IReadOnlySchemaOptions options)
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.3.0

**Comment by ZephiroRB** [comment]
Finally he is working but commenting on the line AddAuthorization(); After AddGraphQLServer(). 

Already run the gateway, but now when executing a query, it does not recognize the past headers with Authorization but if you pass directly to microservice but not by the gateway, sorry but not existing a guide of how to implement Authorization with Federation I do not know where to ask help

**Comment by michaelstaib** [comment]
Ask this question please on slack.chillicream.com 

You need to give people time to answer on slack and might also need to repost your question.
