### ISSUE TITLE
`dotnet format` failing with `System.Reflection.ReflectionTypeLoadException`

### ISSUE THREAD

**Issue by ArinGhazarian** [ChilliCream/hotchocolate#4581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running `dotnet format --verify-no-changes` on a `Strawberry Shake` project, it raises the following error:

`Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.`

Full Stacktrace:

```c#
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.<>c.<LoadAnalyzersAndFixers>b__0_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.LoadAnalyzersAndFixers(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Project project)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource element)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Solution solution, FormatOptions formatOptions, ILogger logger)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
```

### Steps to reproduce

1. Create a `Strawberry Shake` demo project as described in the [Get Started Doc](https://chillicream.com/docs/strawberryshake/get-started/console)
2. After finishing the [Step4 - 5. Compile your project](https://chillicream.com/docs/strawberryshake/get-started/console#step-4-add-a-graphql-client-to-your-project-using-the-cli-tools), once the project in fully compiled, run the following command: `dotnet format --verify-no-changes -verbosity diag`
3. It raises the aforementioned error. Here is the full log after running the command:
```c#
dotnet format --verify-no-changes --verbosity diag
  The dotnet runtime version is '6.0.1'.
  The dotnet CLI version is '6.0.101'.
  Using MSBuild.exe located in '/usr/local/share/dotnet/sdk/6.0.101/'.
  Formatting code files in workspace '/Users/arin/github/strawberry-shake-error/Demo.sln'.
  Loading workspace.
    Determining projects to restore...
  All projects are up-to-date for restore.
  Project Demo is using configuration from '/Users/arin/github/strawberry-shake-error/Demo/obj/Debug/net6.0/Demo.GeneratedMSBuildEditorConfig.editorconfig'.
  Project Demo is using configuration from '/usr/local/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/analyzers/build/config/analysislevel_6_default.editorconfig'.
  Complete in 2848ms.
  Determining formattable files.
  Complete in 362ms.
  Running formatters.
  Running Code Style analysis.
  Determining diagnostics...
  Running 1 analyzers on Demo.
  Complete in 2950ms.
  Analysis complete in 2950ms.
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.<>c.<LoadAnalyzersAndFixers>b__0_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.LoadAnalyzersAndFixers(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Project project)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource element)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Solution solution, FormatOptions formatOptions, ILogger logger)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
```

### Relevant log output

```shell
The dotnet runtime version is '6.0.1'.
  The dotnet CLI version is '6.0.101'.
  Using MSBuild.exe located in '/usr/local/share/dotnet/sdk/6.0.101/'.
  Formatting code files in workspace '/Users/arin/github/strawberry-shake-error/Demo.sln'.
  Loading workspace.
    Determining projects to restore...
  All projects are up-to-date for restore.
  Project Demo is using configuration from '/Users/arin/github/strawberry-shake-error/Demo/obj/Debug/net6.0/Demo.GeneratedMSBuildEditorConfig.editorconfig'.
  Project Demo is using configuration from '/usr/local/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/analyzers/build/config/analysislevel_6_default.editorconfig'.
  Complete in 2848ms.
  Determining formattable files.
  Complete in 362ms.
  Running formatters.
  Running Code Style analysis.
  Determining diagnostics...
  Running 1 analyzers on Demo.
  Complete in 2950ms.
  Analysis complete in 2950ms.
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.<>c.<LoadAnalyzersAndFixers>b__0_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.LoadAnalyzersAndFixers(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Project project)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource element)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Solution solution, FormatOptions formatOptions, ILogger logger)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass27_0.<<UseVersionOption>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseDebugDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'SubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'MoveNextAsync' in type 'ErrorSubscriptionEnumerator' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'DisposeAsync' in type 'Subscription' from assembly 'HotChocolate.Execution, Version=12.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Boolean> System.Collections.Generic.IAsyncEnumerator`1.MoveNextAsync()'.
```

### Additional Context?

- .NET SDK version: `6.0.101`
- .NET Runtime version: `6.0.1`
- OS: `macOS Big Sur`

### Product

Strawberry Shake

### Version

12.4.1

**Comment by tobias-tengler** [comment]
This seems to not be a Strawberry Shake related problem, but rather that `dotnet format` doesn't seem to play nicely with Source Generator generated code. I found a couple of similar issues with dotnet format, for example https://github.com/dotnet/format/issues/1461

As one of the comments there suggests try building the project before executing dotnet format.

Otherwise I would suggest you direct your feedback towards the `dotnet format` command - there's little we can do. That being said I remember there being work on  a Strawberry Shake generator not using Source Generators or something similar that might help you (CC: @michaelstaib )

**Comment by ArinGhazarian** [comment]
Thanks for the reply @tobias-tengler, I really appreciate it 🙏.
