### ISSUE TITLE
Could not resolve Char Type

### ISSUE THREAD

**Issue by Gowtham-stack** [ChilliCream/hotchocolate#4642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Could not resolve Char Type, tried descriptor.Ignore(f => f.name); still its working.
Any help would be  appreciated

`HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to infer or resolve a schema type from the type reference `Output: Char`.

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddleware.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddleware.InvokeAsync(HttpContext context)
   at HotChocolate.AspNetCore.WebSocketSubscriptionMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Agilysys.VisualOne.Common.Libraries.Middleware.CustomVersioningMiddleware.Invoke(HttpContext context, IExecutionContext executionContext, ITenantManagementServcie tenantManagementServcie, CacheStore cache)
   at Agilysys.VisualOne.Common.Libraries.Middleware.ExecutionContextMiddleware.Invoke(HttpContext context, IExecutionContext executionContext, ITenantManagementServcie tenantManagementServcie, DBContextConfig dBContextConfig, CacheStore cache)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

### Steps to reproduce

1. Define a property with char type

### Product

Banana Cake Pop

### Version

12.4.1

**Comment by michaelstaib** [comment]
In GraphQL there is no char type. You can explicitly bind it to string if you want to.

```csharp
services
    .AddGraphQLServer()
    .BindRuntimeType<char, StringType>()
```

**Comment by Gowtham-stack** [comment]
Thanks it works

**Comment by Gowtham-stack** [comment]
Hi @michaelstaib, if I use [UseFilitering] annotation, I'm getting the same issue again. 
RoomStatus is of char type
```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. The type of the member RoomStatus of the declaring type Room is unknown
 (HotChocolate.Data.Filters.FilterInputType<Agilysys.VisualOne.RoomInventory.Infrastructure.Entities.Room>)
```
