### ISSUE TITLE
The type of the member Date of the declaring type TransactionSummary is unknown

### ISSUE THREAD

**Issue by daviddesmet** [ChilliCream/hotchocolate#4648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot Chocolate 12.4 added support for `DateOnly` and `TimeOnly` [posted here](https://chillicream.com/blog/2021/12/14/hot-chocolate-12-4/#dateonly-and-timeonly) but I'm getting:

```
The type of the member Date of the declaring type TransactionSummary is unknown
 (HotChocolate.Data.Filters.FilterInputType<Domain.Entities.TransactionSummary>)
```

This is the entity class:

```csharp
public class TransactionSummary : IEntity
{
    public string Id { get; set; } = default!;

    public DateOnly Date { get; set; }

    public string ReferenceId { get; set; } = default!;
}
```

This is the query:

```csharp
public class Query
{
    [UsePaging]
    [UseProjection]
    [UseSorting]
    [UseFiltering]
    public IExecutable<TransactionSummary> GetTransactionSummary([Service] IMongoCollection<TransactionSummary> collection)
        => collection.AsExecutable();
}
```

And finally, the services DI:

```csharp
builder.Services
	   .AddGraphQLServer()
	   .AddQueryType<Query>()
	   .AddMutationType<Mutation>()
	   .AddGlobalObjectIdentification()
	   .AddMongoDbFiltering()
	   .AddMongoDbSorting()
	   .AddMongoDbProjections()
	   .AddMongoDbPagingProviders();
```

### Steps to reproduce

1. Create a class with a property using `DateOnly` type.

### Relevant log output

```shell
An unhandled exception has occurred while executing the request.
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. The type of the member Date of the declaring type TransactionSummary is unknown
 (HotChocolate.Data.Filters.FilterInputType<Domain.Entities.TransactionSummary>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Additional Context?

Using latest version of Hot Chocolate + .NET 6 + Official MongoDB integration.

### Product

Hot Chocolate

### Version

12.5.0

**Comment by daviddesmet** [comment]
I'm not familiar with the codebase but seems the BindRuntimeType are missing for DateOnly and TimeOnly in the MongoDB integration [here](https://github.com/ChilliCream/hotchocolate/blob/aca8c3edc7225cbc2266940e506582f17aea5089/src/HotChocolate/MongoDb/src/Data/Filters/Convention/Extensions/MongoDbFilterConventionDescriptorExtensions.cs#L72).

**Comment by PascalSenn** [comment]
@daviddesmet  this is correct. Would you like to create a PR?

**Comment by daviddesmet** [comment]
@PascalSenn Sure! Please have a look at the PR.
