### ISSUE TITLE
Null reference exception when using token overload

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#468]
(The following pertains to HotChocolate preview-26)
**If token is not used in Resolver**
```
protected override void Configure(IObjectTypeDescriptor<TestType> descriptor)
{
       descriptor.Field("foo").Resolver((context, token) => { return "bar"; })
}
```
will throw the following exception
```
   at HotChocolate.TypeResources.Field_Cannot_ResolveType(String typeName, String fieldName, TypeReference typeReference)
   at HotChocolate.Types.FieldHelper.ResolveFieldType[T](ITypeInitializationContext context, IField field, TypeReference typeReference)
   at HotChocolate.Types.FieldBase`1.OnCompleteType(ITypeInitializationContext context)
   at HotChocolate.Types.ObjectFieldBase.OnCompleteType(ITypeInitializationContext context)
   at HotChocolate.Types.ObjectField.OnCompleteType(ITypeInitializationContext context)
   at HotChocolate.Types.TypeSystemBase.CompleteType(ITypeInitializationContext context)
   at HotChocolate.Types.ObjectType.CompleteFields(ITypeInitializationContext context)
   at HotChocolate.Types.ObjectType.OnCompleteType(ITypeInitializationContext context)
   at HotChocolate.Types.TypeSystemBase.CompleteType(ITypeInitializationContext context)
   at HotChocolate.Configuration.SchemaContext.CompleteTypes(IEnumerable`1 types, ISet`1 processed, ICollection`1 errors)
   at HotChocolate.Configuration.SchemaContext.CompleteTypes()
   at HotChocolate.Configuration.TypeFinalizer.FinalizeTypes(SchemaContext context, String queryTypeName)
   at HotChocolate.Schema.ExecuteSchemaConfiguration(SchemaContext context, Action`1 configure, List`1 errors)
```

**The following works**
```
protected override void Configure(IObjectTypeDescriptor<TestType> descriptor)
{
       descriptor.Field("foo").Resolver((context) => { return "bar"; });
}
```

**Comment by michaelstaib** [comment]
Fixed with #487
