### ISSUE TITLE
Disable Exec timeout of 30 seconds when Debugging

### ISSUE THREAD

**Issue by drowhunter** [ChilliCream/hotchocolate#469]
when debugging and more than 30 seconds elapses you get the following exception

```
{
  "errors": [
    {
      "message": "Unexpected Execution Error",
      "extensions": {
        "stackTrace": "   at System.Threading.CancellationToken.ThrowOperationCanceledException()
        at HotChocolate.Execution.ExecutionStrategyBase.EndExecuteResolverBatchAsync(IExecutionContext executionContext, IEnumerable`1 currentBatch, Action`1 enqueueTask, CancellationToken cancellationToken)
        at HotChocolate.Execution.ExecutionStrategyBase.ExecuteResolverBatchAsync(IExecutionContext executionContext, IReadOnlyCollection`1 currentBatch, List`1 nextBatch, BatchOperationHandler batchOperationHandler, CancellationToken cancellationToken)
        at HotChocolate.Execution.ExecutionStrategyBase.ExecuteResolversAsync(IExecutionContext executionContext, IEnumerable`1 initialBatch, BatchOperationHandler batchOperationHandler, CancellationToken cancellationToken)
        at HotChocolate.Execution.ExecutionStrategyBase.ExecuteQueryAsync(IExecutionContext executionContext, BatchOperationHandler batchOperationHandler, CancellationToken cancellationToken)
        at HotChocolate.Execution.QueryExecutionStrategy.ExecuteInternalAsync(IExecutionContext executionContext, CancellationToken cancellationToken)
        at HotChocolate.Execution.ExecuteOperationMiddleware.InvokeAsync(IQueryContext context)
        at HotChocolate.Execution.ExceptionMiddleware.InvokeAsync(IQueryContext context)",
        "message": "The operation was canceled."
      }
    }
  ]
}
```

**Comment by michaelstaib** [comment]
This one is now implemented and will be included with 0.7.0-preview.27
