### ISSUE TITLE
CacheDataLoader conflict when using same key

### ISSUE THREAD

**Issue by mvestergaard** [ChilliCream/hotchocolate#4744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have two different cache data loaders
```cs
public class AllCountriesLoader : CacheDataLoader<bool, IEnumerable<ICountry>>
{
    private readonly ICountryRepository repository;

    public AllCountriesLoader(ICountryRepository repository, DataLoaderOptions? options = null)
        : base(options)
    {
        this.repository = repository;
    }

    protected override async Task<IEnumerable<ICountry>> LoadSingleAsync(bool key, CancellationToken cancellationToken)
        => await this.repository.GetAllAsync(cancellationToken);
}
```
and
```cs
public class AllCoverCausesLoader : CacheDataLoader<bool, IEnumerable<ICoverCause>>
{
    private readonly ICoverCauseRepository repository;

    public AllCoverCausesLoader(ICoverCauseRepository repository, DataLoaderOptions? options = null)
        : base(options)
    {
        this.repository = repository;
    }

    protected override async Task<IEnumerable<ICoverCause>> LoadSingleAsync(bool key, CancellationToken cancellationToken)
        => await this.repository.GetAllAsync(cancellationToken);
}
```

Occasionally (timing dependent), we're seeing errors like this:
```
Unable to cast object of type 'System.Threading.Tasks.TaskCompletionSource`1[System.Collections.Generic.IEnumerable`1[Nis.Claims.ICoverCause]]' to type 'System.Threading.Tasks.TaskCompletionSource`1[System.Collections.Generic.IEnumerable`1[Nis.Geography.ICountry]]'.
   at GreenDonut.Batch`1.GetOrCreatePromise[TValue](TKey key)
   at GreenDonut.DataLoaderBase`2.GetOrCreatePromiseUnsafe(TKey key)
   at GreenDonut.DataLoaderBase`2.<>c__DisplayClass15_0.<LoadAsync>g__CreatePromise|0()
   at GreenDonut.TaskCache.<>c__DisplayClass12_0`1.<GetOrAddTask>b__0(TaskCacheKey k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at GreenDonut.TaskCache.GetOrAddTask[T](TaskCacheKey key, Func`1 createTask)
   at GreenDonut.DataLoaderBase`2.LoadAsync(TKey key, CancellationToken cancellationToken)
   at Nordic.Application.Geography.Queries.AllCountriesQuery.Handler.Handle(AllCountriesQuery request, CancellationToken cancellationToken) in E:\actions-runner2\_work\platform\platform\src\Core\Nordic.Application\Geography\Queries\AllCountriesQuery.cs:line 26
   at Nis.Infrastructure.Messaging.RequestPerformanceBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in E:\actions-runner2\_work\platform\platform\Nis.Core.Common\Infrastructure\Messaging\RequestPerformanceBehavior`2.cs:line 42
   at Nis.Infrastructure.Messaging.RequestValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in E:\actions-runner2\_work\platform\platform\Nis.Core.Common\Infrastructure\Messaging\RequestValidationBehavior`2.cs:line 57
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at Nordic.GraphQL.Schema.Geography.GeographyQueries.GetCountries(CancellationToken cancellationToken, ISender sender, IMapper mapper) in E:\actions-runner2\_work\platform\platform\src\Nordic\Nordic.GraphQL.Schema\Geography\GeographyQueries.cs:line 22
   at HotChocolate.Resolvers.Expressions.ExpressionHelper.AwaitTaskHelper[T](Task`1 task)
   at HotChocolate.Types.Helpers.FieldMiddlewareCompiler.<>c__DisplayClass9_0.<<CreateResolverMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at HotChocolate.AspNetCore.Authorization.AuthorizeMiddleware.InvokeAsync(IDirectiveContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

We're guessing it happens because the key is the same (a boolean), even though the return type is different.

### Steps to reproduce

I hope you have enough to go on from the description above. As mentioned, it's timing dependent, so difficult to consistently reproduce.

### Product

Green Donut

### Version

12.2.2

**Comment by joelving** [comment]
One of @mvestergaard's coworkers here. I'd add to the issue, that it seems *not* to be triggered by a single query, regardless of the loaders using the same key. 
I could only reproduce the issue when introducing a delay to the repository methods (inserting a await Task.Delay(5000) into the GetAllAsync), to ensure that I would have multiple in-flight queries. This also explains why the error was only present in a test-environment with less resources and not my local dev environment.
