### ISSUE TITLE
The name `Query` was already registered by another type. (GraphQL.API.Types.QueryType)

### ISSUE THREAD

**Issue by direstrepo24** [ChilliCream/hotchocolate#4791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get this error: The name `Query` was already registered by another type. (GraphQL.API.Types.QueryType)

my QueryType is:

` public class QueryType : ObjectType<PersonQuery>
    {
        protected override void Configure(IObjectTypeDescriptor<PersonQuery> descriptor)
        {
            descriptor
                .Field(f => f.GetPersonByIdAsync(default!, default!, default!))
                .Type<PersonType>();
            descriptor
                .Field(f => f.GetPersonAsync(default!, default!))
                .Type<ListType<PersonType>>();
        }
    }`

### Steps to reproduce

1. in startup set: 

 .AddGraphQLServer(Schema.DefaultName)
                     .AddQueryType(d => d.Name("Query"))
                  .AddType<QueryType>() 

### Relevant log output

```shell
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.
      
      1. The name `Query` was already registered by another type. (GraphQL.API.Types.QueryType)
      
         at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
^Cinfo: Microsoft.Hosting.Lifetime[0]
```

### Additional Context?

i am fetch existent Rest  api

### Product

Hot Chocolate

### Version

12.0.0

**Comment by direstrepo24** [comment]
Hi, thanks for you help, this is repo: https://github.com/direstrepo24/grapqhnetcoreexample.git
Basically I create a web rest api with swagger, I generate the client to be able to consume and integrate inside graphql, following this documentation (https://chillicream.com/docs/hotchocolate/fetching-data/fetching-from-rest) but it doesn't work

**Comment by michaelstaib** [comment]
```
// .AddType<QueryType>()  ///here problem
```

if this is your issue then the issue is clear since you register to root types.
If you add the line above you can remove the following:

```
.AddQueryType(d => d.Name("Query"));
```

**Comment by direstrepo24** [comment]
if I remove "Query" I get the error: "The schema builder was unable to identify the query type of the schema". If you see the code there is a PersonQuery, this comes from the Rest api, and the "public class QueryType : ObjectType<PersonQuery>" allows you to describe it like this: descriptor
                .Field(f => f.GetPersonAsync(default!, default!))
                .Type<ListType<PersonType>>();
How can I integrate the Rest api with Graphql? Thanks
