### ISSUE TITLE
CLI: Update schema with basic authorization?

### ISSUE THREAD

**Issue by dariusz-wozniak** [ChilliCream/hotchocolate#4805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Basic Authorization enabled for the GraphQL server. I'd like to update schema by running `dotnet graphql update -u https://localhost:5001/graphql` and:

1: If Authorization is DISABLED then I get schema updated (correct behaviour):

```
dotnet graphql update -u https://localhost:5001/graphql
Download schema started.
Download schema completed in 2020 ms
```

1: If Authorization is ENABLED then I get schema updated (incorrect behaviour):

```
dotnet graphql update -u https://localhost:5001/graphql
Download schema started.
error HTTP_ERROR: Response status code does not indicate success: 500 (Internal Server Error).
```

Code for the authorization:

```csharp
services.AddGraphQLServer()
                    .AddAuthorization()
//...
```

Please allow to authorize CLI via Basic.

### Steps to reproduce

1. Run `dotnet graphql update -u https://localhost:5001/graphql` on server where Basic Auth is enabled.

### Product

Hot Chocolate

### Version

12.6.0

**Comment by tobias-tengler** [comment]
You can pass your authorization header as an argument:

```bash
dotnet graphql update -u https://localhost:5001/graphql -x Authorization="Basic xxx"
```

[Reference](https://chillicream.com/docs/strawberryshake/tooling#update-project)

**Comment by dariusz-wozniak** [comment]
When I run `dotnet graph --help`, there is nothing about `-x` param:

```
λ dotnet graphql --help
The following commands are supported:

- Initialize project and download schema
  dotnet graphql init http://localhost
  dotnet graphql init {url} [-p|--Path] [-n|--clientName] [--token] [--scheme] [--tokenEndpoint] [--clientId] [--clientSecret] [--scope]

- Update local schema
  dotnet graphql update
  dotnet graphql update [-p|--Path] [-u|--uri] [--token] [--scheme] [--tokenEndpoint] [--clientId] [--clientSecret] [--scope]

- Download the schema as GraphQL SDL
  dotnet graphql download http://localhost
  dotnet graphql download {url} [-f|--FileName] [--token] [--scheme] [--tokenEndpoint] [--clientId] [--clientSecret] [--scope]
```

And, when I try to use the above command, I get:

```
λ dotnet graphql update -u https://localhost:5001/graphql -x "Authorization=a"
>>
Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.UnrecognizedCommandParsingException: Unrecognized option '-x'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.HandleUnexpectedArg(String argTypeName, String argValue)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at StrawberryShake.Tools.Program.<Main>(String[] args)
```

**Comment by tobias-tengler** [comment]
Yes, the latest version should be 12.6.1

**Comment by dariusz-wozniak** [comment]
Yes, that resolved the issue, thank you 👏
