### ISSUE TITLE
Node resolvers do not support inherited members

### ISSUE THREAD

**Issue by Suzii** [ChilliCream/hotchocolate#5001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am trying to introduce Global identification to a project with many entities. My IDs are typically hierarchical (`projectId + entityId + optionalSecondLevelId + ...`). I want a unified approach to defining ID fields as well as to writing resolvers - ideally common interface/generic static method for node resolving. 

I tried 2 approaches:

A. Implementing the resolver as a static method in the entity base class: It seems like HC does not accept it. Looking at the code, it looks like `FlattenHierarchy` binding flag is missing when searching for an appropriate method via reflection API.
B. Another approach I tried was having an `INodeResolver` service with a generic `Get()` method inherited by a specific `IEntityService` with implementation in `EntityService` + specifying the resolver type and name for the entity via `[Node]` attribute). However, this did not work either, since the reflection does not crawls parent interfaces. (Even if it did, IoC would fail to resolve the service implementation during node resolution, as the `NodeResolverType` is ignored later in the code execution)

### Steps to reproduce

For both A & B:
```
public interface INodeResolver<TEntity, in TId>
{
    Task<TEntity> GetByNodeId([ID(typeName: nameof(TEntity))] TId id);
}
public interface IEntityService : INodeResolver<Entity, EntityNodeId>
{
}
// IoC setup
serviceCollection.AddScoped<IEntityService , EntityService>
```

A. Static resolver in entity's base class
```
[Node]
public abstract record Node<TNode, TId, TResolver> 
    where TNode: Node<TNode, TId, TResolver>
    where TResolver : INodeResolver<TNode, TId>
{
    public abstract TId Id { get; }

    public static async Task<TNode> GetAsync([ID(nameof(TNode))] TId id, [Service] TResolver resolver)
        => await resolver.GetByNodeId(id);
}
    
public record Entity: Node<Entity, EntityNodeId, IEntityService >
{
    public override EntityNodeId Id => new(ProjectId, EntityId);
    
    // other properties
}

```

B. Specifying resolver type and name which is, however, defined in the base interface.
```
[Node(NodeResolverType = typeof(IEntityService), NodeResolver = nameof(IEntityService.GetByNodeId))]
public record Entity
{
    // ... 
}
```

Note, that the B approach works, if I declare the resolver type using the EntityService implementation, which, however, feels akward and is not testable.

### Relevant log output

```shell
A: An unhandled exception has occurred while executing the request.
      System.ArgumentNullException: Value cannot be null. (Parameter 'method')
         at HotChocolate.Types.Relay.Descriptors.NodeDescriptorBase.ResolveNodeWith(MethodInfo method)
         at HotChocolate.Types.Relay.Descriptors.NodeDescriptor.ResolveNode(Type type)
         at HotChocolate.Types.Relay.NodeAttribute.<>c__DisplayClass12_0.<OnConfigure>b__1(ITypeCompletionContext descriptorContext, ObjectTypeDefinition definition)
         at HotChocolate.Types.Descriptors.DescriptorBase`1.<>c__DisplayClass25_0.<OnBeforeCompletion>b__0(ITypeCompletionContext c, IDefinition d)
         at HotChocolate.Types.TypeSystemObjectBase`1.ExecuteConfigurations(ITypeCompletionContext context, TDefinition definition, ApplyConfigurationOn on)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>g__CompleteType|27_0(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationT
oken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

B: "The specified node resolver `GetByNodeId` does not exist on `ITaxonomyService`".
```

### Additional Context?

I will submit a PR with an attempt to "fix" the issue A. 

As for the issue B, at first, it seemed like [crawling the interface hierarchy ](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DefaultTypeInspector.cs#L301) would be enough. However, if I tried changing it, runtime fails when trying to resolve INodeResolver, which is, obviously, not registered in the IoC container. `NodeResolverType` is ignored once the resolvers are initialized and then only INodeResolver is being used which is not enough.

### Product

Hot Chocolate

### Version

12.7.0

**Comment by Suzii** [comment]
The linked PR should fix the problem A. 

Problem B is harder to fix, as described in the additional context, when I added crawling all the parent interfaces it fails at runtime, since the member is defined in "helper interface" INodeResolver, which itself is not registered in the DI.
