### ISSUE TITLE
UseFiltering error when applied to both parent and nested collection

### ISSUE THREAD

**Issue by DijanaPenic** [ChilliCream/hotchocolate#5064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to add filtering to both parent and nested collection, an error is thrown. I would expect no error and the nested data to be filtered by the query.

Parent filter - CompanyFilterType
Nested collection filter - PersonFilterType

### Steps to reproduce

```
public class CompanyFilterType : FilterInputType<Company>
{
    protected override void Configure(IFilterInputTypeDescriptor<Company> descriptor)
    {
        descriptor.BindFieldsImplicitly();
        
        descriptor.Ignore(c => c.Id);
    }
}
```
```
public class PersonFilterType : FilterInputType<Person>
{
    protected override void Configure(IFilterInputTypeDescriptor<Person> descriptor)
    {
        descriptor.BindFieldsImplicitly();
        
        descriptor.Ignore(p => p.Id);
        descriptor.Ignore(p => p.CompanyId);
    }
}
```

```
[ExtendObjectType("Query")]
public class CompanyQueries
{
    [UseApplicationDbContext]
    [UsePaging]
    [UseFiltering(typeof(CompanyFilterType))] // This will cause an issue.
    [UseSorting(typeof(CompanySortType))]
    public IQueryable<Company> GetCompanies([Service] ApplicationDbContext dbContext) => dbContext.Companies;
}
```
```
public class CompanyType : ObjectType<Company>
{
    protected override void Configure(IObjectTypeDescriptor<Company> descriptor)
    {
        // ...removed for brevity...

        descriptor
            .Field(c => c.Employees)
            .UsePaging()
            .UseFiltering<PersonFilterType>() // This will cause an issue.
            .UseSorting<PersonSortType>()
            .Resolve((context, cancellationToken) =>
            {
                PersonByCompanyIdDataLoader dataloader = context.DataLoader<PersonByCompanyIdDataLoader>();
                return dataloader.LoadAsync(context.Parent<Company>().Id, cancellationToken);
            });
    }
}
```

### Relevant log output

```shell
The name `CompanyFilterInput` was already registered by another type. (GraphQLChoco.API.Companies.CompanyFilterType)

         at HotChocolate.Configuration.TypeRegistry.Register(NameString typeName, RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypeName(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyKind kind, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteNames()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, I
ServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationTok
en)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
         at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
         at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.8.2

**Comment by PascalSenn** [comment]
Can you specify the filter on the field specially ?

```csharp
public class CompanyFilterType : FilterInputType<Company>
{
    protected override void Configure(IFilterInputTypeDescriptor<Company> descriptor)
    {
        descriptor.BindFieldsImplicitly();
        descriptor.Field(x => x.Employees).Type<ListFilterInputType<PersonFilterInputType>();
        
        descriptor.Ignore(c => c.Id);
    }
}

```
and vice-verca ?

**Comment by DijanaPenic** [comment]
Yes, schema initialization is working with the additional field configuration. Thank you!
