### ISSUE TITLE
Azure Functions Support

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/hotchocolate#520]
- What do we have to do to be hosted in azure functions?
- Do we need a template for that?
- How can we use azure functions as resolvers? (this one might be worth a separate issue)

**Comment by bartecargo** [comment]
I'm interested in using Hot Chocolate on an Azure function. Can I assume from this open issue that it currently isn't possible to do so?

**Comment by nzbart** [comment]
I'm interested in using Hot Chocolate on an Azure function. Can I assume from this open issue that it currently isn't possible to do so?

**Comment by michaelstaib** [comment]
It is possible. Here is an example: https://github.com/OneCyrus/GraphQL-AzureFunctions-HotChocolate

With Version 11 we will bring out of the box support for this.

**Comment by nzbart** [comment]
The example worked perfectly for me, thanks.

**Comment by chandsalam1108** [comment]
HI,

I'm getting error while getting all characters & humans.

Also, getting error while implementing UsePaging &  UseFiltering. Please help.

**Comment by ChristianWeyer** [comment]
> With Version 11 we will bring out of the box support for this.

Is this still on track? :-)
Thanks and keep up the great work!

**Comment by michaelstaib** [comment]
@ChristianWeyer 11 will be coming at the end of October. We will decide mid October if this one makes the cut or if we move it to the December release.

**Comment by Deathrage** [comment]
Hello I tried the OneCyrus solution but I ran into an exception when I try introspection using altair (I didnt try any other qeuries but I think it's gonna end up same).

Could not load file or assembly 'Microsoft.Extensions.DiagnosticAdapter, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

   at HotChocolate.Execution.Instrumentation.QueryExecutionDiagnostics.Subscribe(DiagnosticListener observable, IEnumerable`1 observers, ISet`1 handled)
   at HotChocolate.Execution.Instrumentation.QueryExecutionDiagnostics..ctor(DiagnosticListener observable, IEnumerable`1 observers)
   at HotChocolate.Execution.QueryExecutionBuilderExtensions.<>c.<UseInstrumentation>b__9_0(IServiceProvider sp)
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4540
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6595
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7839
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7824
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6594
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6554
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6624
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7736
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 209
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 194
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 99
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 77
   at HotChocolate.Execution.ClassMiddlewareFactory.<>c__DisplayClass0_0`1.<Create>b__1(IServiceProvider s, QueryDelegate n)
   at HotChocolate.Execution.ClassMiddlewareFactory.<>c__DisplayClass2_0`1.<CreateDelegate>b__0(IQueryContext context)
   at HotChocolate.Execution.QueryExecutor.<ExecuteMiddlewareAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Reality.UI.Executor.GraphQlExecutor.<ExecuteFunctionsQueryAsync>d__15.MoveNext() in D:\Repos\git\reality\BE\Reality.UI\Executor\GraphQlExecutor.cs:line 69
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Reality.Access.Functions.UI.UI_Http_GraphQl.<RunAsync>d__3.MoveNext() in D:\Repos\git\reality\BE\Reality.Access\Functions\UI\UI_Http_GraphQl.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__10.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<InvokeAsync>d__26.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 541
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithWatchersAsync>d__25.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 486
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__24.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 432
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<ExecuteWithLoggingAsync>d__18.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 239

I'm using
<PackageReference Include="HotChocolate.AspNetCore" Version="10.5.3" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />

**Comment by michaelstaib** [comment]
@Deathrage can you please open up a proper issue?

This issue is actually meant for the feature not for issues with an example.

**Comment by Ma3yTa** [comment]
@Deathrage https://github.com/Azure/azure-functions-vs-build-sdk/issues/397#issuecomment-596315129
this should help

**Comment by michaelstaib** [comment]
Dear future reader, do not add any errors here regarding the AzF example by @OneCyrus. This feature item shall only be used regarding the Hot Chocolate integration and not for reporting errors. If you have an issue, open up a new issue.

**Comment by Deathrage** [comment]
@michaelstaib I am sorry I will ask in the other project but I find it highly innapropriate that you have deleted the reply **with solution.**

**Comment by michaelstaib** [comment]
HI @Deathrage,

I am sorry that this upset you, but it really is better to just create a new issue. For us, it is hard to organize our feature tasks when people just add some errors that actually have nothing to do with the feature item itself. This also leads to us overlooking issues since they are just dumped into feature items. 

I would not mind a new issue on our report describing your issue and even providing some help around this, but please re-post them as a separate issue so that we can keep track of these things.

**Comment by danimalx10** [comment]
> @ChristianWeyer 11 will be coming at the end of October. We will decide mid October if this one makes the cut or if we move it to the December release.

Michael, did this make the cut?

**Comment by michaelstaib** [comment]
Hi,

no, we are moving it to the December release version 11.1.0

**Comment by ngufra** [comment]
Hello

When hot chocolate can be be hosted in an azure function, will it support subscriptions (through SignalR) ? If not is there an ETA?
Thank you

-Francois

**Comment by chandsalam1108** [comment]
HI, Do we have a support for sorting & filtering on Azure function? I'm able to do that on WebApp but getting error while trying  that on AZ function app. Please help.

**Comment by michaelstaib** [comment]
It should also work in there. We for now are not officially supporting Azure Functions. But there is a package that supports this here: 

https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy#enabling-the-playground-from-azurefunctions

But still the filtering and stuff will just work in there.

At the moment native AzF support is planned for the 2021-06 release cycle with previews coming out beginning of may.

**Comment by ronaldvdv** [comment]
> At the moment native AzF support is planned for the 2021-06 release cycle with previews coming out beginning of may.

Are you also targeting the Azure Functions Functions Worker for .NET 5 ? It seems that this does not expose a `HttpContext` when using a `HttpTrigger`, which makes it impossible to adapt implementations like the unofficial package mentioned above :-)

**Comment by michaelstaib** [comment]
No, I got a small example from Anthony Chu on how we can get a fill ASP.NET core server into this. I did not yet dive into all the specifics of that. We have moved AzF support to the 2021-09 release. 

Roadmap is here:
https://github.com/ChilliCream/hotchocolate/projects/28

**Comment by Ma3yTa** [comment]
a very rough draft  which works in Azure functions .net 5 dotnet-isolated

```csharp
using HotChocolate.AspNetCore.Serialization;
using HotChocolate.Execution;
using Microsoft.Azure.Functions.Worker.Http;
using System.Threading.Tasks;
using System.Threading;
using System.Linq;
using HotChocolate;
using System.Text;

namespace Project1
{
    public class GraphQLAzureFunctionsExecutorProxyV12
    {
        private readonly IHttpRequestParser _requestParser;
        private readonly IHttpResultSerializer _resultSerializer;
        private readonly IRequestExecutorResolver _requestExecutorResolver;
        public GraphQLAzureFunctionsExecutorProxyV12(
            IHttpRequestParser requestParser,
            IHttpResultSerializer resultSerializer,
            IRequestExecutorResolver requestExecutorResolver)
        {
            _requestParser = requestParser;
            _resultSerializer = resultSerializer;
            _requestExecutorResolver = requestExecutorResolver;
        }

        public async Task<HttpResponseData> ExecuteQueryAsync(HttpRequestData req)
        {
            var requests = await _requestParser.ReadJsonRequestAsync(req.Body, CancellationToken.None).ConfigureAwait(false);
            var executor = await _requestExecutorResolver.GetRequestExecutorAsync().ConfigureAwait(false);
            var batchRequest = requests.Select(r => QueryRequestBuilder.From(r).Create());
            var result = await executor.ExecuteBatchAsync(batchRequest).ConfigureAwait(false);

            var response = req.CreateResponse();
            response.Headers.Add("Content-Type", _resultSerializer.GetContentType(result));
            response.StatusCode = _resultSerializer.GetStatusCode(result);
            // var json = await result.ToJsonAsync().ConfigureAwait(false);

            var json = new StringBuilder();

            await foreach (IQueryResult payload in result.ReadResultsAsync())
            {
                json.AppendLine(payload.ToJson());
                json.AppendLine();
            }

            await response.WriteStringAsync(json.ToString()).ConfigureAwait(false);
            return response;
        }
    }
}

```

```csharp
 public static class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureServices(s =>
                {
                    s.AddSingleton<GraphQLAzureFunctionsExecutorProxyV12>();
                    s.AddGraphQLServer().AddQueryType<Query>();

                }).Build();

            host.Run();
        }
    }
```
```csharp
 public partial class API
    {
        private readonly GraphQLAzureFunctionsExecutorProxyV12 _graphQlExecutorProxy;
        public API(GraphQLAzureFunctionsExecutorProxyV12 graphQlExecutorProxy)
        {
            _graphQlExecutorProxy = graphQlExecutorProxy;
        }

        [Function(nameof(GraphQL))]
        public async Task<HttpResponseData> GraphQL(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql")] HttpRequestData req)
            => await _graphQlExecutorProxy.ExecuteQueryAsync(req).ConfigureAwait(false);
   }
}
```

**Comment by chandsalam1108** [comment]
Thank you @maksimetsa for sharing draft code.

I tried high Level implementation of HotChocolate GraphQL Azure Function NET 5.0 (isolated process) and it's working fine. 

Git Repository: https://github.com/chandsalam1108/GraphQLAzFunctionNet5 

Article: https://chandabdulsalam.medium.com/hotchocolate-graphql-azure-function-net-5-0-isolated-process-1e16ee198ac1

**Comment by p-bojkowski** [comment]
@chandsalam1108 410? -> https://chandabdulsalam.medium.com/hotchocolate-graphql-azure-function-net-5-0-isolated-process-1e16ee198ac1

![image](https://user-images.githubusercontent.com/74313141/121804382-6d645100-cc46-11eb-9f06-89c04a857d8a.png)

**Comment by p-bojkowski** [comment]
The URL changed to: https://chandabdulsalam.medium.com/hotchocolate-graphql-azure-function-net-5-0-isolated-process-f3eae3650caf

**Comment by jfattic** [comment]
did you already work out how to get the V12 proxy working with Banana Cake Pop?

**Comment by chandsalam1108** [comment]
HI, do we have any recommended swagger document approach for graphql azure function?

**Comment by CharlieDigital** [comment]
@chandsalam1108 That would seem like the wrong way to go; you'd ideally generate the GQL clients and models directly from the schema instead rather than swagger which is geared towards REST.

**Comment by chandsalam1108** [comment]
Is **AddHttpRequestInterceptor** not supported in Azure Functions .Net 5.0? Please advice.

Also, advice on how to set GlobalState object and use the same in Query class. 

I'm using centralized JWT authorization library hence upon successful authorization I need to set claims returned from my library to some global state object so that can be used inside Query class.

Thanks.

**Comment by CharlieDigital** [comment]
If you want to intercept requests with functions, you need to use `IFunctionInvocationFilter`.  Functions has a distinct runtime from .NET Web API.

With respect to custom JWT, check this blog post on how to implement custom JWT using `IFunctionInvocationFilter`: https://charliedigital.com/2020/05/24/azure-functions-with-jwt-authentication/

**Comment by chandsalam1108** [comment]
Hi @CharlieDigital , Thanks for the help.

I'm mostly following similar approach for custom JWT but not sure how to persist ClaimsPrincipal post authorization and use that in Query class. 

I'm using .Net 5 so I've no access to HttpContext. So, please advice on how to get my Claims to Query class.

Thank you!

**Comment by CharlieDigital** [comment]
Missed that detail; if you are using .NET 5, then you should have access to middleware and can plug in a package to set the `ClaimsPrincipal`.

**Comment by chandsalam1108** [comment]
I'm using **AddHttpRequestInterceptor** but it's not getting executed. Let me know if I'm missing something.

All i need is to set ClaimsPrincipal and assess that in Query class. Appreciate if you can some github sample in this regard.

**Environment: .Net 5, Azure Function V3, HotChocolate 11.x**

```
public static class Program
    {
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults(
                builder =>
                {
                    //builder.UseMiddleware<ExceptionLoggingMiddleware>();
                })
                .ConfigureServices(s =>
                {
                    s.AddPooledDbContextFactory<HealthCenterContext>(db => db.UseSqlServer(Environment.GetEnvironmentVariable("SqlConnectionString")));

                    s.AddSingleton<GraphQLAzureFunctionsExecutorProxyV12>();

                    s.AddGraphQLServer()
                    .AddQueryType<Query>()
                    .AddProjections()
                    .AddFiltering()
                    .AddSorting()                    
                    .ModifyRequestOptions(opt => opt.IncludeExceptionDetails = true)
                    .AddHttpRequestInterceptor(
                        (context, executor, builder, ct) =>
                        { //Unable to hit the break point here...
                            if (true)
                            { // My idea is to extract the claims ad

                            }
                            return default;
                        });

                }).Build();

            host.Run();
        }
}
```

**Comment by chandsalam1108** [comment]
@CharlieDigital @michaelstaib @maksimetsa 

**Issue: Unable to pass custom object from AZ function method to **Query** class.**

**Environment: .Net 5, Azure Function V3, HotChocolate 11.x**

For better understanding of the issue, please go through the code snippets mentioned below.

**Function Logic:**

```

[Function(nameof(GraphQL))]
        public async Task<HttpResponseData> GraphQL(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "graphql")] HttpRequestData req, FunctionContext context)
        {
            var logger = context.GetLogger("HealthCenterFx");

            AuthHelper.ExecuteAuth(req, out var _submitter); \\My custom Authorization lib returns **submitter** details after authorization
\\Is there a way I can pass **_submitter** object to Query class?
            if (!_submitter.IsAuthenticated)
            {
                var authResponse = req.CreateResponse(System.Net.HttpStatusCode.Unauthorized);

                logger.LogInformation($"Unauthorized Access!!!");

                await authResponse .WriteAsJsonAsync($"Unauthorized Access!!!");

                return authResponse ;
            }

            return await _graphQlExecutorProxy.ExecuteQueryAsync(req).ConfigureAwait(false);
        }

```
**### Is there a way I can pass submitter object details from AZ function method to the Query class mentioned below?**

**Query Class Logic:**

```

        [UseDbContext(typeof(HealthCenterContext))]
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Clinic> GetClinics([ScopedService] HealthCenterContext context)
        {
\\Is there a way I can get custom object (submitter) details from AZ function method to here to use that in linq where condition?
            return context.Clinics;
        }
```

**Comment by CharlieDigital** [comment]
Can't fully answer this question as I have not worked with .NET 5 Functions, but if you find the answer, definitely share it here!

**Comment by cajuncoding** [comment]
FYI to all.... the above approach to using .Net 5 in the Azure Functions isolated process model (out-of-process) is limited to only supporting Query execution.  In addition the HC middleware do a lot of other awesome work that is likely being exluded.

I have recently had a little time to update the [AzureFunctionsProxy project](https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy) to now support the isolated process with .Net 5, and it can be used today (even if to jump start your development process ahead of the official)....

It has full parity of features as the AzureFunctionProxy has with the In-Process model.... all you have to do is use the nuget package: https://www.nuget.org/packages/GraphQL.AzureFunctionsProxy.IsolatedProcess/

This enables a new extension method now available that handles the `HttpRequestData` and returns the `HttpResponseData ` compable with the out-of-process model using .Net 5!

[Example and more details are in the readme here...](https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy#b-isolated-process-model-out-of-process-azure-function-setup-proxy-the-requests-from-the-function-into-hc-pipeline)

I successfully validated:
a series of basic queries that I also used to validate the in-process AzureFunctionProxy; which ultimately it's the SAME proxy code running for both now :slightly_smiling_face:
Banana Cake Pop is working as expected :raised_hands:
And Schema Download is working as expected 

Official Azure Functions support is still in the Pipeline for HC (which will be the go-to approach once released)....

**Comment by tobias-tengler** [comment]
Azure Functions support has officially been released with version 12.1.0. Please give it a try and raise a new issue, if you encounter any problems! :)

You can get started with our new Azure Functions template:

```bash
dotnet new -i HotChocolate.Templates::12.2.1
dotnet new graphql-azf
```

**Comment by Voskoboynik** [comment]
Hi.

Do you plan to support .NET isolated process functions any time soon?

According to the [Azure Functions Roadmap](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-roadmap/ba-p/2197916) the "isolated process" model will be the single available option starting from .NET 7. This makes the "in-process" model much less attractive (especially for new function apps) because it will require migrating to the isolated worker when upgrading to >=.NET 7.

I have seen the @cajuncoding's solution (thank you for this 🙂) but it would be nice to have it officially supported in HC.

**Comment by cajuncoding** [comment]
FYI @Voskoboynik et al,

Official support for Azure Functions _Isolated Process_ is coming soon!  It's now slated for release with **HC v12.9.0** per recent discussion with the core team, and of course will be included in v13!  It's fully functioning, and will likely be available in preview very soon:

![image](https://user-images.githubusercontent.com/20844814/164787761-91b74045-027f-4098-a29c-c9ca9552621b.png)

**Comment by source-studio** [comment]
May I ask when this is due to be released @cajuncoding ?

**Comment by cajuncoding** [comment]
@source-studio this was asked in the slack channel recently also. It has been implemented and the PR has been submitted…but still pending final approval & merging. 

I think it’s now slated for v13…not sure if it’ll get pulled into a v12 release; @michaelstaib will need to provide more info.
