### ISSUE TITLE
Cannot resolve 'HotChocolate.Execution.Processing.OperationContext'

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/hotchocolate#5244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Executing any request against a GraphQL server running the latest preview yields the following error:
```
System.InvalidOperationException: Cannot resolve 'HotChocolate.Execution.Processing.OperationContext' from root provider because it requires scoped service 'HotChocolate.Execution.DependencyInjection.IFactory`1[HotChocolate.Execution.Processing.DeferredWorkStateOwner]'.
```

### Steps to reproduce

I just switched over a working project of the latest v12 to the latest preview version and noticed this error. Couldn't narrow it down to any wrongdoing in our application code.

### Relevant log output

```shell
System.InvalidOperationException: Cannot resolve 'HotChocolate.Execution.Processing.OperationContext' from root provider because it requires scoped service 'HotChocolate.Execution.DependencyInjection.IFactory`1[HotChocolate.Execution.Processing.DeferredWorkStateOwner]'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Create()
         at Microsoft.Extensions.ObjectPool.DefaultObjectPool`1.Get()
         at HotChocolate.Execution.Pipeline.OperationExecutionMiddleware.ExecuteOperationAsync(IRequestContext context, IBatchDispatcher batchDispatcher, IOperation operation)
         at HotChocolate.Execution.Pipeline.OperationExecutionMiddleware.InvokeAsync(IRequestContext context, IBatchDispatcher batchDispatcher)
         at HotChocolate.Execution.Pipeline.OperationVariableCoercionMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.OperationComplexityMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.TimeoutMiddleware.InvokeAsync(IRequestContext context)
         at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)
```

### Product

Hot Chocolate

### Version

13.0.0-preview.28

**Comment by nikolai-mb** [comment]
Had this issue myself. Was able to narrow it down to the environment variable ASPNETCORE_ENVIRONMENT in the launch profile in launchSettings.json

![image](https://user-images.githubusercontent.com/35340657/179512860-2ddd654e-fb01-4184-9a4c-437ac9e0a27e.png)

If this value is set to Development, the issue occurs. If the value is anything else or missing, the project works fine. Not sure how helpful this information is, but posting just in case it can help point in the right direction :)

Was able to reproduce with both launch types below, both have the issue when the environment variable is set, and both work without.

![image](https://user-images.githubusercontent.com/35340657/179513275-409786d1-535d-4aa2-86c5-bbb839d35045.png)

**Comment by michaelstaib** [comment]
Thanks for your feedback ... we are currently working on fixing this issue.

**Comment by MoazAlkharfan** [comment]
Hope this gets prioritized as It makes all the preview versions after 13.0.0-preview.24 unusable

**Comment by tobias-tengler** [comment]
This is fixed in the latest preview.

**Comment by michaelstaib** [comment]
We no longer support netcore 3.1 for Data since the final release of 13 will be somewhere in December netcore 3.1 will be out of support. Full support of all 13 features is now only available with net 6 and net 7.
