### ISSUE TITLE
HotChocolate.SchemaException when add remote schema with UploadType

### ISSUE THREAD

**Issue by angel-viejobueno** [ChilliCream/hotchocolate#5302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've got a microservice that uses HotChocolate and the schema contains a UploadType, that microservice is working perfectly fine and I can upload files using it, but when I try to add this schema to a Stitching schema with other schemas that come from other microservices I receive always an error. 

I know that this error has been reported previously in the ticket: https://github.com/ChilliCream/hotchocolate/issues/3760.

Seems like the schema Stitching doesn't support UploadType

I'd like to know if there will be soon any solution, we are starting our development and maybe we can wait a little bit otherwise we will have to take another solution, thanks.

### Steps to reproduce

1.  Adding a schema that contains the UploadType to schema Stitching.

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to resolve dependencies None: DataSourceInput, None: ByIdInput, None: DataSourceInput, None: ByIdInput, None: DataSourceDetailInput, None: ByIdInput, None: DataSourceDetailInput, None: ByIdInput, None: TemplateInput, None: ByIdInput, None: TemplateInput, None: ByIdInput, None: TemplateSheetInput, None: ByIdInput, None: TemplateSheetInput, None: ByIdInput, None: TemplateSheetDetailInput, None: ByIdInput, None: TemplateSheetDetailInput, None: ByIdInput, None: Upload for type `Mutation`. (HotChocolate.Types.ObjectType)

   at HotChocolate.Configuration.TypeInitializer.EnsureNoErrors()
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at Microsoft.Extensions.DependencyInjection.HotChocolateStitchingRequestExecutorExtensions.<>c__DisplayClass5_0.<<AddRemoteSchema>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Product

Hot Chocolate

### Version

12.12.1

**Comment by michaelstaib** [comment]
Schema stitching does not support upload in version 12. We are integrating Upload into the new fusion platform that will replace schema stitching.

**Comment by angel-viejobueno** [comment]
Thanks Michael.

**Comment by Chrikmaster** [comment]
[michaelstaib](https://github.com/michaelstaib)
Are there any updates/news on upload type via gateway (stitching)? Or are they any updates on the new fusion platform?

**Comment by michaelstaib** [comment]
@Chrikmaster version 13.1 will support it ... we expect it to be sometime around March.

**Comment by Chrikmaster** [comment]
@michaelstaib thanks.
