### ISSUE TITLE
v13 preview 24 - UnexpectedEndOfStream when executing multiple queries against stitched API

### ISSUE THREAD

**Issue by be1223** [ChilliCream/hotchocolate#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are using schema federation with Redis, with several APIs stitched into a gateway.

One of these APIs uses custom scalars which (to prevent re-definition in the gateway) required us to upgrade the **gateway** to v13-preview.24 (highest supported version of the HotChocolate.Stitching.Redis package).

The downstream APIs are all still v12.x.

We are able to successfully execute a single query in a single request, however as soon as we attempt to execute 2 queries in a single request both requests encounter the UnexpectedEndOfStream exception

See [StitchingRepro.zip](https://github.com/ChilliCream/hotchocolate/files/9375183/StitchingRepro.zip).

The above expects a redis instance to be running on port 6379, I used the docker image: `docker run -p 6379:6379 redis:alpine` and uses no other external dependencies, the queries are returning in-memory DTOs only.

### Steps to reproduce

1. Run an instance of redis using `docker run -p 6379:6379 redis:alpine`
2. Run downstream.csproj
3. Run Gateway.csproj
4. execute: It should return an array of data
```
query {
  dtos {
    property1
    property2
  }
}
```
5. execute: It should return an array of data
```
query {
  otherDtos {
    property1
    property2
  }
}
```
6. Now combine them into a single request, this will produce the error
```
query {
  dtos {
    property1
    property2
  },
  otherDtos {
    property1
    property2
  }
}
```

### Relevant log output

```shell
Unexpected end of Stream, the content may have already been read by another component. 
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.MultipartReader.ReadNextSectionAsync(CancellationToken cancellationToken)
   at HotChocolate.Stitching.Execution.HttpPostBatchStream.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at HotChocolate.Stitching.Execution.HttpPostBatchStream.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at HotChocolate.Stitching.Execution.HttpPostBatchStream.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at HotChocolate.Stitching.Execution.RemoteRequestScheduler.ExecuteBufferedRequestBatchAsync(CancellationToken cancellationToken)
   at HotChocolate.Stitching.Execution.RemoteRequestScheduler.ExecuteBufferedRequestBatchAsync(CancellationToken cancellationToken)
   at HotChocolate.Stitching.Processing.DelegateResolve.ExecuteQueryAsync(IResolverContext context, IQueryRequest request, String schemaName)
   at HotChocolate.Stitching.Processing.DelegateResolve.ExecuteQueryAsync(IResolverContext context, IQueryRequest request, String schemaName)
   at HotChocolate.Stitching.Processing.DelegateResolve.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Stitching.Processing.DelegateResolve.InvokeAsync(IMiddlewareContext context)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Product

Hot Chocolate

### Version

12.x, 13-preview.24

**Comment by michaelstaib** [comment]
I am closing this issue since we are working on a new distributed schema platform called fusion which is already preset in the newest versions but still in a very early stage.
