### ISSUE TITLE
Strawberry Shake TaskCanceledException when upload multiple files

### ISSUE THREAD

**Issue by spin973** [ChilliCream/hotchocolate#5437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to upload multiple files, the request is never sent to the server throw a TaskCanceledException and a timeout error appears immediately (even if the message indicates that the timeout is 100 seconds)

Method to upload files:

        private async Task UploadMultipleImagesAsync(InputFileChangeEventArgs args)
        {
            List<Upload> files = new();
            foreach (var file in args.GetMultipleFiles())
            {
                using var stream = file.OpenReadStream();
                files.Add(new Upload(stream, file.Name));
            }

            var input = new UploadMultipleImagesInput
            {
                Files = files,
            };

            var result = await GraphQLClient.UploadMultipleImages.ExecuteAsync(input);
            if (result.IsSuccessResult())
            {
                ResponseMultiple = result.Data?.UploadMultipleImages.String;
            }
        }               

mutation:
`
mutation UploadMultipleImages($input : UploadMultipleImagesInput!) {
	uploadMultipleImages(input: $input) {
		string
	}
}
`

### Steps to reproduce

1. I have created a small repo to reproduce the error: https://github.com/spin973/StrawberryShake_FilesUpload

### Relevant log output

```shell
Uncaught (in promise) Error: System.Exception
 ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.OpenReadStreamAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.CopyFileDataIntoBuffer(Int64 sourceOffset, Memory`1 destination, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__82`2[[System.Net.Http.HttpContent, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Byte[], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at StrawberryShake.Transport.Http.ResponseEnumerator.MoveNextAsync()
   at StrawberryShake.OperationExecutor`2.<ExecuteAsync>d__6[[System.Text.Json.JsonDocument, System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[GraphQL.Client.IUploadMultipleImagesResult, GraphQL.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at StrawberryShake.OperationExecutor`2.<ExecuteAsync>d__6[[System.Text.Json.JsonDocument, System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51],[GraphQL.Client.IUploadMultipleImagesResult, GraphQL.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at GraphQL.Client.UploadMultipleImagesMutation.ExecuteAsync(UploadMultipleImagesInput input, CancellationToken cancellationToken) in C:\VS2019\source\repos\_Temp\GraphQL.Test\GraphQL.Client\obj\Debug\net6.0\berry\GraphQLClient.Client.cs:line 704
   at GraphQL.Client.Pages.Index.UploadMultipleImagesAsync(InputFileChangeEventArgs args) in C:\VS2019\source\repos\_Temp\GraphQL.Test\GraphQL.Client\Pages\Index.razor.cs:line 53
   --- End of inner exception stack trace ---
   at GraphQL.Client.Pages.Index.UploadMultipleImagesAsync(InputFileChangeEventArgs args) in C:\VS2019\source\repos\_Temp\GraphQL.Test\GraphQL.Client\Pages\Index.razor.cs:line 63
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
    at Object.endInvokeDotNetFromJS (https://localhost:7060/_framework/blazor.webassembly.js:1:3531)
    at Object.Rt [as endInvokeDotNetFromJS] (https://localhost:7060/_framework/blazor.webassembly.js:1:60651)
    at Object.St [as invokeJSFromDotNet] (https://localhost:7060/_framework/blazor.webassembly.js:1:60134)
    at _mono_wasm_invoke_js_blazor (https://localhost:7060/_framework/dotnet.6.0.9.rnz6vdon31.js:1:195300)
    at wasm://wasm/00971d1a:wasm-function[219]:0x1a492
    at wasm://wasm/00971d1a:wasm-function[167]:0xce60
    at wasm://wasm/00971d1a:wasm-function[166]:0xbd73
    at wasm://wasm/00971d1a:wasm-function[2815]:0xabebf
    at wasm://wasm/00971d1a:wasm-function[1619]:0x6fc80
    at wasm://wasm/00971d1a:wasm-function[1623]:0x702ed
```

### Product

Strawberry Shake

### Version

13.0.0-preview.63

**Comment by spin973** [comment]
@tobias-tengler You're right, without `using` it works, I have move the dispose of `stream` in the `finally` clause. Thanks.
