### ISSUE TITLE
Non-root mutations are not supported by conventions schema feature of the library

### ISSUE THREAD

**Issue by bohdan-kolomiiets** [ChilliCream/hotchocolate#5496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In company where I work we use practice called "Namespace-types" described [here](https://graphql-rules.com/rules/mutation-namespaces). Simply speaking we group mutations wrapping them by other types. We decided to stick to this practice beacuse we have preatty huge distributed graph with lots of operations. This approach helps us to organize graph structure and make it more discoverable.

Your library has greate feature you name as [Conventions](https://chillicream.com/docs/hotchocolate/v12/defining-a-schema/mutations#conventions) that autogenerates input/output types and errors schema for mutations. When we discovered it, we were happy because before we had been implementing it by ourselves before and now it saves lots of code lines and works greate out of the box. 

But for some reason you decided to limit this conventions feature only to the root mutation fields.

I understand that in your library you consider only root fields inside `Mutation` type as mutations [according to the docs](https://chillicream.com/docs/hotchocolate/v12/defining-a-schema/mutations). As far as I understand it is because you cannot guarantee [sequential execution](https://graphql.org/learn/queries/#multiple-fields-in-mutations) for deeper fields.  

But I wonder whether we need this serial execution guarantee for this convention feature? Whether there are any problems with applying these shema generation features like input/output and erorrs for operations outside of root `Mutation` type ? 
If it is possible, it would allow us to use this groupping practice on one hand and take advantage of this greate feature in your library!

### Put code to files and build project

<b>HotChocolateDemo.csproj</b>
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="12.15.0" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="12.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.9" />
  </ItemGroup>
</Project>
```

<b>Properties/launchSettings.json</b>
```
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "profiles": {
    "HotChocolateDemo": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "applicationUrl": "http://localhost:5014",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

<b>Program.cs</b>
```
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using HotChocolate.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer().AddQueryType<Query>().AddMutationType<Mutation>().AddAuthorization().AddMutationConventions(applyToAllMutations: false);
builder.Services.AddSingleton<NotesRepository>().AddSingleton<UsersRepository>();
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateAudience = false, ValidateIssuer = false, ValidateIssuerSigningKey = true, ClockSkew = TimeSpan.Zero,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("MySuperSecretKey"))
    };
});
builder.Services.AddAuthorization();

var app = builder.Build();
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQLHttp("/graphql");
    endpoints.MapGraphQLSchema("/graphql/schema");
    endpoints.MapBananaCakePop("/graphql/ui");
});
app.Run();

[ObjectType]
public class Query
{
    public NotesQueries Notes => new NotesQueries();
}
public class NotesQueries
{
    [Authorize]
    public NoteViewModel[] List(
        ClaimsPrincipal claimsPrincipal,
        [Service] NotesRepository notesRepository)
    {
        var currentUserId = claimsPrincipal.FindFirstValue("UserId");
        var viewModels = notesRepository.Value.Where(o => o.OwnerId == currentUserId).Select(o => o.ToViewModel()).ToArray();
        return viewModels;
    }
}

[ObjectType]
public class Mutation
{
    public AccountMutations Accounts => new AccountMutations();
    public NotesMutations Notes => new NotesMutations();
}

public class AccountMutations
{
    // [UseMutationConvention] // <-------------------- this results in runtime error
    [Error(typeof(UserNotFoundException))]
    public string SignIn(
        string userId, [Service] UsersRepository usersRepository)
    {
        var userDto = usersRepository.Value.SingleOrDefault(o => o.Id == userId);
        if (userDto == null)
        {
            throw new UserNotFoundException();
        }

        var tokenHandler = new JwtSecurityTokenHandler();
        var key = Encoding.ASCII.GetBytes("MySuperSecretKey");
        var tokenDescriptor = new SecurityTokenDescriptor
        {
            Subject = new ClaimsIdentity(new Claim[]
            {
                new("UserId", userId),
            }),
            IssuedAt = DateTime.UtcNow,
            Expires = DateTime.UtcNow.AddHours(1),
            SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature),
        };
        var token = tokenHandler.CreateToken(tokenDescriptor);
        var jwt = tokenHandler.WriteToken(token);
        return jwt;
    }
    
    [Authorize]
    public async Task<UserViewModel> Edit(
        string email, ClaimsPrincipal claimsPrincipal, [Service] UsersRepository usersRepository)
    {
        var currentUserId = claimsPrincipal.FindFirstValue("UserId");
        var userDto = usersRepository.Value.SingleOrDefault(o => o.Id == currentUserId);
        if (userDto == null)
        {
            throw new Exception("user is not registered");
        }
        userDto.Email = email;
        return userDto.ToViewModel();
    }
}

public class NotesMutations
{
    [Authorize]
    public async Task<NoteViewModel> Add(
        string title, string body, ClaimsPrincipal claimsPrincipal, [Service] NotesRepository notesRepository)
    {
        var currentUserId = claimsPrincipal.FindFirstValue("UserId");
        var noteDto = new NoteDto(Id: Guid.NewGuid().ToString(), OwnerId: currentUserId) {Title=title, Body=body};
        notesRepository.Value.Add(noteDto);
        return noteDto.ToViewModel();
    }

    [Authorize]
    public async Task<NoteViewModel> Edit(
        [GraphQLType(typeof(IdType))] string noteId, string title, string body, ClaimsPrincipal claimsPrincipal, [Service] NotesRepository notesRepository)
    {
        var currentUserId = claimsPrincipal.FindFirstValue("UserId");
        var existingNoteDto = notesRepository.Value.FirstOrDefault(o => o.Id == noteId && o.OwnerId == currentUserId);
        if (existingNoteDto == null)
        {
            throw new Exception("notfount");
        }
        existingNoteDto.Title = title;
        existingNoteDto.Body = body;
        return existingNoteDto.ToViewModel();
    }
    
    [Authorize]
    public async Task<string> Delete(
        [GraphQLType(typeof(IdType))] string noteId, ClaimsPrincipal claimsPrincipal, [Service] NotesRepository notesRepository)
    {
        var currentUserId = claimsPrincipal.FindFirstValue("UserId");
        var existingNoteDto = notesRepository.Value.FirstOrDefault(o => o.Id == noteId && o.OwnerId == currentUserId);
        if (existingNoteDto == null)
        {
            throw new Exception("notfount");
        }
        notesRepository.Value.Remove(existingNoteDto);
        return existingNoteDto.Id;
    }
}

public class UserNotFoundException : Exception { }


[ObjectType("Note")] public record NoteViewModel([property: GraphQLType(typeof(IdType))]string Id, string Title, string Body);

[ObjectType("User")] public record UserViewModel([property: GraphQLType(typeof(IdType))]string Id, string Email);

public class NotesRepository
{
    public readonly List<NoteDto> Value = new()
    {
        new NoteDto(Id: "1", OwnerId: "1") { Title = "user 1 note 1 title", Body = "user 1 note 1 body" },
        new NoteDto(Id: "2", OwnerId: "1") { Title = "user 1 note 2 title", Body = "user 1 note 2 body" },
        new NoteDto(Id: "3", OwnerId: "2") { Title = "user 2 note 1 title", Body = "user 2 note 1 body" },
        new NoteDto(Id: "4", OwnerId: "2") { Title = "user 2 note 2 title", Body = "user 2 note 2 body" }
    };
}
public class UsersRepository
{
    public readonly List<UserDto> Value = new()
    {
        new UserDto(Id: "1") { Email = "user1@gmail.com"},
        new UserDto(Id: "2") { Email = "user2@gmail.com"}
    };
}
public record NoteDto(string Id, string OwnerId)
{
    public string Title { get; set; }
    public string Body { get; set; }
    public NoteViewModel ToViewModel() => new(Id, Title, Body);
}

public record UserDto(string Id)
{
    public string Email { get; set; }
    public UserViewModel ToViewModel() => new(Id, Email);
}
```

### Run project
Now app should run successfully.

### Uncomment [UseMutationConvention] attribute
When you uncomment it. Application should fail during schema compilation with the following error :

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. There are mutation annotations on non mutation fields. The mutation conventions can only be applied to fields of the mutation type.

   at HotChocolate.Types.MutationConventionTypeInterceptor.OnAfterMergeTypeExtensions()
   at HotChocolate.Configuration.AggregateTypeInterceptor.OnAfterMergeTypeExtensions()
   at HotChocolate.Configuration.TypeInitializer.MergeTypeExtensions()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types, LazySchema lazySchema)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(NameString schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(NameString schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(NameString schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context, AllowedContentType contentType)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass13_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Product

Hot Chocolate

### Version

12.15.0

**Comment by michaelstaib** [comment]
This rule is not spec compliant as Mutations cannot be namespaced.

**Comment by michaelstaib** [comment]
The main thing here for me is that I do not want to allow this to be possible as I do not want to encourage people to break spec behavior. The spec is at this point very clear that mutations are only top level and that everything beneath is selecting the changed state of the server. This has many advantages and also guarantees that store updates in client applications are predictable.

Instead of graphql rules I would follow the leaders on schema design like Marc Andre:
https://productionreadygraphql.com/

**Comment by michaelstaib** [comment]
Also, its not a bug since there are no non-root mutations in GraphQL.
