### ISSUE TITLE
Issue with record input type containing methods

### ISSUE THREAD

**Issue by MoazAlkharfan** [ChilliCream/hotchocolate#5520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting `HotChocolate.SchemaException` when there is a record with Methods.

I expect HotChocolate to ignore methods contained in InputTypes.

### Steps to reproduce

1. Create record containing methods
2. Use the record as an InputType for a QueryType
3. Exception thrown when schema is being built

### Relevant log output

```shell
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. Unable to cast object of type 'System.Reflection.RuntimeMethodInfo' to type 'System.Reflection.PropertyInfo'. (HotChocolate.Types.InputObjectType<Stats.StatsFilterInput>)
```

Source: `HotChocolate.Types`

StackTrace:
```
   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.<CreateSchemaAsync>d__15.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at HotChocolate.Execution.RequestExecutorResolver.<CreateSchemaServicesAsync>d__14.MoveNext()
   at HotChocolate.Execution.RequestExecutorResolver.<GetRequestExecutorNoLockAsync>d__11.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at HotChocolate.Execution.RequestExecutorResolver.<GetRequestExecutorAsync>d__10.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at HotChocolate.Execution.RequestExecutorProxy.<GetRequestExecutorAsync>d__15.MoveNext()
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.<HandleRequestAsync>d__9.MoveNext()
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.<InvokeAsync>d__8.MoveNext()
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext()
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.<Invoke>d__10.MoveNext()
```
```


### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

13.0.0-preview.73

**Comment by michaelstaib** [comment]
Do you have a repro for this? a small project that we can use to see what the issue is?

**Comment by MoazAlkharfan** [comment]
@michaelstaib Sorry for the late reply.
I should have provided an example, Here it is and if a full reproduction is needed I might be able to provide it at a later date.
But basically what I'm assuming is that it's throwing the exception because the input has methods.

```c#

[ExtendObjectType(typeof(Queries))]
public class Stats
{
    public IQueryable<EntityStat> GetStats(AppDbContext db, StatsFilterInput input) => input.ApplyFilter(db.Set<EntityStat>());

    public record StatsFilterInput(string?[]? Labels, DateTimeOffset? From, DateTimeOffset? To)
    {
        public IQueryable<T> ApplyFilter<T, TK>(IQueryable<T> q)
            where TK : notnull
            where T : Entity<TK>, IHasLabels
        {
            return ApplyLabelsFilter(ApplyDateFilter<T, TK>(q));
        }


        public IQueryable<T> ApplyDateFilter<T, TK>(IQueryable<T> q)
            where TK : notnull
            where T : Entity<TK>
        {
            /*  Apply custom filter */
            return q;
        }

        public IQueryable<T> ApplyLabelsFilter<T>(IQueryable<T> q)
            where T : IHasLabels
            => Labels is { Length: > 0 } ? /*  Apply custom filter */ q : q;
    }
}
```

**Comment by michaelstaib** [comment]
This should be fixed already with the newest preview. Can you retest and close the issue if it's fixed. Otherwise report back.

**Comment by MoazAlkharfan** [comment]
Yes, It's been fixed already.
