### ISSUE TITLE
Support IAsyncDisposable for resolved services

### ISSUE THREAD

**Issue by BnMcG** [ChilliCream/hotchocolate#5606]
### Is your feature request related to a problem?

When injecting a service which only implements `IAsyncDisposable`, the HotChocolate DI container errors at dispose time (because the dotnet container throws its own exception):

Example code:

```
public class Foo : IFoo, IAsyncDisposable
{
    // ...
    public async ValueTask DisposeAsync()
    {
        // Do some disposing
    }
}
```

Later, in a GraphQL resolver:
```
public async Task<Baz> DoAThing([Service(ServiceKind.Resolver)] IFoo foo)
{
    return await foo.DoAThing();
}
```

At runtime:
```
'Foo.Bar' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
```

```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at HotChocolate.Resolvers.Expressions.Parameters.ServiceHelper.<>c__DisplayClass7_1`1.<<UseResolverServiceInternal>b__3>d.MoveNext()
--- End of stack trace from previous location ---
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### The solution you'd like

Support `IAsyncDisposable` where it's implemented.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Its not HotChocolate but the MS container:
` at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()`

https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync

**Comment by michaelstaib** [comment]
I am closing this issue as it is not our component that has an issue.
