### ISSUE TITLE
Unexpected ArgumentNullException on StrawberryShake on errors: Either body or exception have to be set.

### ISSUE THREAD

**Issue by repne** [ChilliCream/hotchocolate#5642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On correctly returned GraphQL errors (Status code 200 and valid errors array, I understand this is how the graphql-over-http standard now works), StrawberryShake throws an ArgumentNullException with the message "Either body or exception have to be set." and nothing relevant to be found in the exception. The first issue is the message being misleading, even though the code checks for the [right thing](https://github.com/ChilliCream/hotchocolate/blob/main/src/StrawberryShake/Client/src/Core/OperationResult.cs#L26-L29). The second issue is StrawberryShake unable to parse what I expect to be a valid error response from the server.

### Steps to reproduce

**Query** (generated by StrawberryShake 13.0.0-preview.92)
```graphql
query GetListing($id: ID!) {
    listing(id: $id) {
        __typename
        id
        created
        modified
        state
        name
    }
}
```

**Variables**
```json
{
    "id": "1nfWQ9JxdkmJqIKvLkaC2Q"
}
```

**Response 200 OK** (from HotChocolate 13.0.0-preview.92, using curl with `Content-Type: application/json` and `Accept: application/graphql-response+json` response is with `Content-Type: application/graphql-response+json;charset=utf-8`
```json
{
    "errors": [
        {
            "message": "The ID `1nfWQ9JxdkmJqIKvLkaC2Q` has an invalid format."
        }
    ],
    "data": {
        "listing": null
    }
}
```

**Stacktrace**
```
Exception has occurred: CLR/System.ArgumentNullException
Exception thrown: 'System.ArgumentNullException' in System.Private.CoreLib.dll: 'Either body or exception have to be set.'
   at StrawberryShake.OperationResult`1..ctor(T data, IOperationResultDataInfo dataInfo, IOperationResultDataFactory`1 dataFactory, IReadOnlyList`1 errors, IReadOnlyDictionary`2 extensions, IReadOnlyDictionary`2 contextData)
   at StrawberryShake.OperationResultBuilder`1.Build(Response`1 response)
   at StrawberryShake.StorelessOperationExecutor`2.<ExecuteAsync>d__4.MoveNext()
   at StrawberryShake.StorelessOperationExecutor`2.<ExecuteAsync>d__4.MoveNext()
```

**.graphqlrc.json**
```json
{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "extensions": {
    "strawberryShake": {
      "name": "GraphQLClient",
      "namespace": "MyNamespace",
      "url": "https://myhostname/graphql",
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}
```

**Relevant HotChocolate configuration**
```csharp
builder.Services
    .AddGraphQLServer()
    .AddAuthorization()
    .AddTypes()
    .AddGlobalObjectIdentification()
    .AddMutationConventions()
    .AddInMemorySubscriptions()
    ;
```

### Product

Strawberry Shake

### Version

13.0.0-preview.92

**Comment by repne** [comment]
Closing as this is a duplicate of #4906
