### ISSUE TITLE
Enums get analyzed as types automatically, but also their members aren't renamed prior to said analysis

### ISSUE THREAD

**Issue by AntonC9018** [ChilliCream/hotchocolate#6003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

This issue is in part related to [this one](https://github.com/ChilliCream/graphql-platform/issues/5926).

The problem manifests itself in my case in that HotChocolate fails to initialize my schema, because the original names of enum fields are invalid by its standards.

### Steps to reproduce

I somewhat inflate the issue here by naming the fields and the enum type in Russian, using Cyrillic letters, but at the same time providing an adequate HotChocolate `EnumType` wrapper that renames them:

```cs
public enum Статус
{
    Активный,
    Завершенный,
}

public class StatusType : EnumType<Статус>
{
    protected override void Configure(IEnumTypeDescriptor<Статус> descriptor)
    {
        descriptor.Name("Status");
        descriptor.Value(Статус.Активный).Name("ACTIVE");
        descriptor.Value(Статус.Завершенный).Name("COMPLETED");
    }
}

// ...

builder.Services.AddEndpointsApiExplorer();
{
    var graph = builder.Services.AddGraphQLServer();
    graph.InitializeOnStartup();
    graph.AddQueryType<QueryType>();
    graph.AddType<StatusType>();
    graph.AddType<Thing>();
    graph.ModifyOptions(o =>
    {
        o.DefaultBindingBehavior = BindingBehavior.Explicit;
    });
}
```

See the entire setup [here](https://github.com/AntonC9018/BackendTechExperimentation/tree/d924636f36fd7c92bb45468003c1587066018c56).

In contrast, configuration like this works fine with normal types, regardless of whether the property names are Cyrillic or not, given you rename them. See an example [here](https://github.com/AntonC9018/BackendTechExperimentation/tree/e758c6a9bf57d12221b35a0786d08e5716fe9889)

### Relevant log output

The error happens because the system ends up checking if the enum names in the original enum definition are valid GraphQL symbol names.
```
System.ArgumentException: The specified name is not a valid GraphQL name. (Parameter 'value')
   at HotChocolate.Utilities.NameUtils.EnsureGraphQLName(String name, String argumentName)
   at HotChocolate.Types.Descriptors.Definitions.DefinitionBase.set_Name(String value)
   at HotChocolate.Types.Descriptors.EnumValueDescriptor..ctor(IDescriptorContext context, Object runtimeValue)
   at HotChocolate.Types.Descriptors.EnumValueDescriptor.New(IDescriptorContext context, Object value)
   at HotChocolate.Types.Descriptors.EnumTypeDescriptor.Value[T](T value)
   at HotChocolate.Types.Descriptors.EnumTypeDescriptor`1.Value(T value)
   at efcore_transactions.StatusType.Configure(IEnumTypeDescriptor`1 descriptor) in E:\Coding\work\efcore_transactions\GraphQL.cs:line 14
   at HotChocolate.Types.EnumType`1.CreateDefinition(ITypeDiscoveryContext context)
   at HotChocolate.Types.TypeSystemObjectBase`1.Initialize(ITypeDiscoveryContext context)
   at HotChocolate.Configuration.TypeRegistrar.InitializeType(TypeSystemObjectBase typeSystemObject, String scope, Boolean isInferred)
```

### Additional Context?

I realize that the existence of Cyrillic names for symbols might seem unrealistic, but I think fixing this would be valuable.

For example, I'm working on a code base where a programmer accidentally wrote the Russian 'С' instead of the English 'C' in the name of an enum value, which ended up producing that incomprehensible error and threw me off the loop for some time.

Though improving the error message would be valuable, the problem with enums described in the linked issue should take priority, I think.

### Version

13.0.5

**Comment by nesherhh** [comment]
Also if EnumType<T> used with T that overrides ToString() and returns text that is invalid GraphQL name.

**Comment by michaelstaib** [comment]
Hey,

I have tested this on main.

Current main commit: `2d71c651ea4e257703f51c0c87e753fe344fc2d8`.

What I tested:

```csharp
public enum DayOfWeekWithInvalidName
{
    Monday,
    SÆT
}

public sealed class DayOfWeekType : EnumType<DayOfWeekWithInvalidName>
{
    protected override void Configure(IEnumTypeDescriptor<DayOfWeekWithInvalidName> descriptor)
    {
        descriptor.Value(DayOfWeekWithInvalidName.SÆT).Name("SAT");
    }
}

[Fact]
public async Task EnumValue_ExplicitName_Allows_Invalid_Clr_Enum_Member_Name()
{
    var schema = await new ServiceCollection()
        .AddGraphQLServer()
        .AddType<DayOfWeekType>()
        .BuildSchemaAsync();
}
```

Result:
- Schema initializes successfully with explicit enum value renaming.
- I could not reproduce the old enum-analysis failure on current main.
