### ISSUE TITLE
Diagnostic observers cannot use constructor injection

### ISSUE THREAD

**Issue by nigel-sampson** [ChilliCream/hotchocolate#639]
**Describe the bug**
When creating a diagnostic observer that uses constructor exception when the schema is created a dependency injection exception is thrown.

**To Reproduce**
1. Create a simple diagnostics observer that uses constructor injection.
``` csharp
public class TestDiagnosticObsever : IDiagnosticObserver
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public TestDiagnosticObsever(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }
}
```
2. Ensure the dependencies are registered.
``` csharp
services.AddHttpContextAccessor();
```
3. Register the observer.
```` csharp
AddDiagnosticObserver<TestDiagnosticObsever>()
````
4. Observe the following exception on first request.
```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'Demo.Stitching.TestDiagnosticObsever'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices[T](IServiceProvider provider)
   at HotChocolate.Execution.QueryExecutionBuilderExtensions.<>c__DisplayClass3_0.<UseInstrumentation>b__0(IServiceProvider sp) in C:\hc\src\Core\Core\Execution\Middleware\QueryExecutionBuilderExtensions.cs:line 88
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ExpressionResolverBuilder.<>c__DisplayClass17_0.<Build>b__1(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at HotChocolate.Utilities.CombinedServiceProvider.GetService(Type serviceType) in C:\hc\src\Core\Utilities\CombinedServiceProvider.cs:line 47
   at lambda_method(Closure , IServiceProvider , QueryDelegate )
   at HotChocolate.Execution.ClassMiddlewareFactory.<>c__DisplayClass2_0`1.<CreateDelegate>b__0(IQueryContext context) in C:\hc\src\Core\Core\Execution\Middleware\ClassMiddlewareFactory.cs:line 48
   at HotChocolate.Execution.ClassMiddlewareFactory.<>c__DisplayClass2_0`1.<CreateDelegate>b__0(IQueryContext context) in C:\hc\src\Core\Core\Execution\Middleware\ClassMiddlewareFactory.cs:line 53
   at HotChocolate.Execution.QueryExecutor.ExecuteMiddlewareAsync(IQueryContext context) in C:\hc\src\Core\Core\Execution\QueryExecutor.cs:line 63
   at HotChocolate.AspNetCore.QueryMiddlewareBase.HandleRequestAsync(HttpContext context, IQueryExecutor queryExecutor) in C:\hc\src\Server\AspNetCore\QueryMiddlewareBase.cs:line 190
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context) in C:\hc\src\Server\AspNetCore\QueryMiddlewareBase.cs:line 103
```

**Expected behavior**
Would expect the constructor dependencies to be populated by the dependency injection system.

**Comment by michaelstaib** [comment]
This actually works with preview.3 but you have to add the `AddDiagnosticObserver<TestDiagnosticObsever>()` to the services instead of the builder.

I will add an example today showing how that works.  I am almost through with the documentation and examples.

**Comment by michaelstaib** [comment]
Here is the example project: https://github.com/ChilliCream/hotchocolate-examples/tree/master/Instrumentation
