### ISSUE TITLE
 Unable to resolve type reference `IDictionary<String, Object> (Output)`. (HotChocolate.Types.ObjectType<HistoryEntryAllergyIntolerance>)

### ISSUE THREAD

**Issue by ManuDinicola** [ChilliCream/hotchocolate#6970]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/ManuDinicola/HotchocolateIDictionary

### Steps to reproduce

Run the application , go to http://localhost:5000/graphql/
Create a document and load the schema.

### What is expected?

The schema is loaded

### What is actually happening?

An error occured and the schema (or query) cannot be loaded (execute)

### Relevant log output

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      HotChocolate.SchemaException: For more details look at the `Errors` property.

      1. Unable to resolve type reference `IDictionary<String!, Object!>! (Output)`. (HotChocolate.Types.ObjectType<HotChocolateIDict.PageVOAllergyIntolerance>)

         at HotChocolate.Configuration.RegisteredType.GetType[T](TypeReference typeRef)
         at HotChocolate.Types.OutputFieldBase`1.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, TDefinition definition)
         at HotChocolate.Types.ObjectField.OnCompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember, ObjectFieldDefinition definition)
         at HotChocolate.Types.FieldBase`1.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Types.FieldBase`1.HotChocolate.Types.Helpers.IFieldCompletion.CompleteField(ITypeCompletionContext context, ITypeSystemMember declaringMember)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, TField[] fields)
         at HotChocolate.Internal.FieldInitHelper.CompleteFieldsInternal[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IEnumerable`1 fieldDefinitions, Func`3 fieldFactory, Int32 fieldCount)
         at HotChocolate.Internal.FieldInitHelper.CompleteFields[TFieldDefinition,TField](ITypeCompletionContext context, ITypeSystemMember declaringMember, IReadOnlyList`1 fieldDefs, Func`3 fieldFactory)
         at HotChocolate.Types.ObjectType.OnCompleteFields(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.ObjectType.OnCompleteType(ITypeCompletionContext context, ObjectTypeDefinition definition)
         at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ITypeCompletionContext context)
         at HotChocolate.Configuration.TypeInitializer.CompleteType(RegisteredType registeredType)
         at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__30_0(RegisteredType type)
         at HotChocolate.Configuration.TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
         at HotChocolate.Configuration.TypeInitializer.CompleteTypes()
         at HotChocolate.Configuration.TypeInitializer.Initialize()
         at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
         at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
         at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
         at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
```

### Additional context

The same code works on hotchocolate 13.5.1 , but since 13.6.0 it failed with this error.

**Comment by ManuDinicola** [comment]
Any news about that problem ?

**Comment by glen-84** [comment]
I used Git bisect, and the break happened in this commit: https://github.com/ChilliCream/graphql-platform/commit/15c01ad7f55f94e0115f5ea21ab5ff1ccbf80a74

I looked at the code, and it seems that it relates to the change in `src/HotChocolate/Core/src/Types/Configuration/TypeInitializer.cs`, the way that `initialTypes` is passed into the `TypeDiscoverer` constructor.

**Comment by ManuDinicola** [comment]
Is it possible that with the release 14 it will be fixed?
