### ISSUE TITLE
Format Exception when registering types

### ISSUE THREAD

**Issue by kwemou** [ChilliCream/hotchocolate#787]
**Describe the bug**
When registering some types, I get the following exception:
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at HotChocolate.Types.FieldInitHelper.CompleteFields[TTypeDef,TFieldType,TFieldDef](ICompletionContext context, TTypeDef definition, IReadOnlyCollection`1 fields) in C:\hc\src\Core\Types\Types\Helpers\FieldInitHelper.cs:line 54
   at HotChocolate.Types.TypeSystemObjectBase`1.CompleteType(ICompletionContext context) in C:\hc\src\Core\Types\Types\TypeSystemObjectBase~1.cs:line 89
   at HotChocolate.Configuration.TypeInitializer.<CompleteTypes>b__43_0(RegisteredType registeredType) in C:\hc\src\Core\Types\Configuration\TypeInitializer.cs:line 435
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes(TypeDependencyKind kind, Func`2 action) in C:\hc\src\Core\Types\Configuration\TypeInitializer.cs:line 454
   at HotChocolate.Configuration.TypeInitializer.CompleteTypes() in C:\hc\src\Core\Types\Configuration\TypeInitializer.cs:line 438
   at HotChocolate.Configuration.TypeInitializer.Initialize(Func`1 schemaResolver) in C:\hc\src\Core\Types\Configuration\TypeInitializer.cs:line 109
   at HotChocolate.SchemaBuilder.InitializeTypes(IServiceProvider services, IDescriptorContext descriptorContext, IBindingLookup bindingLookup, IEnumerable`1 types, Func`1 schemaResolver) in C:\hc\src\Core\Types\SchemaBuilder.Create.cs:line 184
   at HotChocolate.SchemaBuilder.Create() in C:\hc\src\Core\Types\SchemaBuilder.Create.cs:line 36
  

[ObjectTypeUtil.txt](https://github.com/ChilliCream/hotchocolate/files/3216837/ObjectTypeUtil.txt)

**To Reproduce**
1. Create a entities and one query class and define them is a separate assembly that the asp .net core application assembly
2. Load the assembly at runtime
3. Register the entities and types using my ObjectTypeUtils attached:
   the ObjectTypeUtils  use reflection to create ObjectType<T> from given Type t
4. Then when get the error you can see in the stack trace.

**Expected behavior**

**Desktop (please complete the following information):**
 - Version [9.0.0-preview.42]

**Additional context**
Asp.net core

**Comment by michaelstaib** [comment]
Thank you for reporting this issue.

I have fixed the error message now. It basically says that you object has no valid fields.

Since you are on V9 I recommend using the schema builder: 

```csharp
SchemaBuilder.New()
   .AddType(YOURPOCOTYPE)
   .Create()
```

The bug is fixed with 9.0.0-rc.1 which should be completed in the next 30 min.

**Comment by kwemou** [comment]
Thank you very much
COOLLL
