### ISSUE TITLE
Syntax Exception when parsing Russian (or non-Latin) characters in Strings

### ISSUE THREAD

**Issue by anadale** [ChilliCream/hotchocolate#885]
**Describe the bug**
An attempt to pass a string with non-Latin characters as a query parameter value leads to Syntax Exception:

```
query {
  field(parameter: "привет") {
    subField
  }
}
```

leads to

```
HotChocolate.Language.SyntaxException: Invalid character escape sequence: \117.
   at HotChocolate.Language.Utf8GraphQLReader.ReadStringValueToken()
   at HotChocolate.Language.Utf8GraphQLReader.Read()
   at HotChocolate.Language.Utf8GraphQLRequestParser.ParseRequestProperty(Request& request)
   at HotChocolate.Language.Utf8GraphQLRequestParser.ParseRequest()
   at HotChocolate.Language.Utf8GraphQLRequestParser.Parse()
   at HotChocolate.AspNetCore.PostQueryMiddleware.ParseRequest(Byte[] buffer, Int32 bytesBuffered)
   at HotChocolate.AspNetCore.PostQueryMiddleware.ReadRequestAsync(Stream stream, Boolean isGraphQLQuery)
   at HotChocolate.AspNetCore.PostQueryMiddleware.CreateQueryRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.CreateQueryRequestInternalAsync(HttpContext context, IServiceProvider services)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.HandleRequestAsync(HttpContext context, IQueryExecutor queryExecutor)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**To Reproduce**
Create a query and add Russian characters (or Emoji) as a string parameter, try to execute the query.

**Expected behavior**
A result or valid error is returned.

**Desktop (please complete the following information):**
 - 9.1.0-preview-17

**Comment by michaelstaib** [comment]
In the unit tests I have written in parses correctly. Can you fiddle the actual json request that is send to the server and paste it?

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/hotchocolate/tree/parser_russion_characters

**Comment by anadale** [comment]
I have found out that my client (JS GraphQL extension for IntelliJ IDEA) converts Russian characters to escaped sequences as below. Standalone GraphiQL client passes UTF characters as is and parser works correctly with them. Here is the converted request:

```json
{"query":"query {\n  field(parameter: \"\u043F\u0440\u0438\u0432\u0435\u0442\") {\n    subField\n  }\n}\n", "variables":null}
```
