### ISSUE TITLE
Double incorrectly deserialized as Int32

### ISSUE THREAD

**Issue by sandorfr** [ChilliCream/hotchocolate#892]
**Describe the bug**
When a variable is a complex type and include `Long` (.net `Double`) Scalar, it tries to deserialize it as an `Int32`.

Example schema
```graphql
directive @cost(
  complexity: Int! = 1
  multipliers: [MultiplierPath!]
) on FIELD_DEFINITION
input ItemInput {
  id: String
  originalEstimate: Float!
}

type ItemPrediction {
}

scalar MultiplierPath

input PredictionRequestInput {
  epics: [ItemInput]
}

type PredictionResult {
  predictions: [ItemPrediction]
}

type Query {
  prediction(
    algorithm: String
    request: PredictionRequestInput
  ): PredictionResult
}
```

**To Reproduce**
1. Build a service as above
2. make a request using
```graphql
query($request: PredictionRequestInput)
{
 prediction(request: $request) 
  {
   predictions
    {
     end{
      end
     }
    }
  }
}
```

```json
{
    "request": {
      "epics": [
        {
          "id": "4345",
          "originalEstimate": 345600000,
        },
        {
          "id": "545",
          "originalEstimate": 2764800000,
        }
      ]
    }
  }
```
3. Run it
4. See error in your service logs

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ThrowInt32OverflowException()
   at System.Convert.ToInt32(Int64 value)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at HotChocolate.AspNetCore.QueryMiddlewareUtilities.DeserializeScalar(JValue value)
   at HotChocolate.AspNetCore.QueryMiddlewareUtilities.DeserializeObject(Dictionary`2 input)
   at HotChocolate.AspNetCore.QueryMiddlewareUtilities.DeserializeList(JArray array)
   at HotChocolate.AspNetCore.QueryMiddlewareUtilities.DeserializeObject(Dictionary`2 input)
   at HotChocolate.AspNetCore.QueryMiddlewareUtilities.ToDictionary(Dictionary`2 input)
   at HotChocolate.AspNetCore.PostQueryMiddleware.CreateQueryRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.CreateQueryRequestInternalAsync(HttpContext context, IServiceProvider services)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.HandleRequestAsync(HttpContext context, IQueryExecutor queryExecutor)
   at HotChocolate.AspNetCore.QueryMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request.
```

If I add a decimal component to my `originalEstimate`  value it falls into the `Float` path and works. which seems to show a problem in integer/float parsing.

**Expected behavior**
It should not try to parse numbers as Int32. 

**Desktop (please complete the following information):**
 - OS: Linux/Debian
 - Version: 9

**Additional context**
.net core 2.2

**Comment by sandorfr** [comment]
After looking at HotChoc code, it appears it converts int as int32 
https://github.com/ChilliCream/hotchocolate/blob/ff3faa1e93359234084fd07dd24fae157c94a2e3/src/Server/AspNetCore/Subscriptions/QueryMiddlewareUtilities.cs#L108

The problem is that in javascript safeInt can go up to `2ˆ53`. The fix would be to actually map `JTokenType.Integer` to `long` instead of `int`.

**Comment by michaelstaib** [comment]
We have changed that with the upcoming version 9.1 preview builds.

**Comment by sandorfr** [comment]
Works for me!
